"""רשימת האמנים הגדולים בכל הזמנים, כנקודת פתיחה לחיפוש קאברים.

המקור: דירוג "Greatest of All Time Artists" של בילבורד, לפי סדר הדירוג המקורי.
זו רשימה סטטית בכוונה — היא נקודת התחלה לחיפוש, לא מדד ולא דירוג של המערכת.
מה שקובע בסוף הוא מה שנמדד מהאודיו, לא המיקום ברשימה הזאת.

השימוש: לחיצה על שם ממלאת את שדה האמן ומריצה את החיפוש. זה חוסך הקלדה ומזכיר
שמות ששווה לבדוק להם קאברים, ותו לא.
"""

GREATEST_ARTISTS = (
    "The Beatles",
    "The Rolling Stones",
    "Elton John",
    "Mariah Carey",
    "Madonna",
    "Barbra Streisand",
    "Michael Jackson",
    "Taylor Swift",
    "Stevie Wonder",
    "Chicago",
    "Whitney Houston",
    "Paul McCartney",
    "Elvis Presley",
    "Janet Jackson",
    "Rod Stewart",
    "Drake",
    "Prince",
    "Rihanna",
    "Billy Joel",
    "Garth Brooks",
    "Herb Alpert",
    "Eminem",
    "Usher",
    "Bruce Springsteen & The E Street Band",
    "Neil Diamond",
    "The Supremes",
    "Eagles",
    "Bee Gees",
    "The Beach Boys",
    "Fleetwood Mac",
    "Santana",
    "The Temptations",
    "Celine Dion",
    "Aretha Franklin",
    "Daryl Hall  John Oates",
    "Adele",
    "Beyonce",
    "Eric Clapton",
    "Lionel Richie",
    "Led Zeppelin",
    "Bruno Mars",
    "John Denver",
    "Maroon 5",
    "Olivia Newton-John",
    "Bon Jovi",
    "Phil Collins",
    "Diana Ross",
    "Bob Dylan",
    "John Mellencamp",
    "JAY-Z",
    "Donna Summer",
    "Nickelback",
    "Boyz II Men",
    "Carpenters",
    "Justin Bieber",
    "Lady Gaga",
    "Foreigner",
    "Britney Spears",
    "P!nk",
    "Alicia Keys",
    "Katy Perry",
    "Miley Cyrus",
    "The Jacksons",
    "Earth, Wind & Fire",
    "Marvin Gaye",
    "U2",
    "Linda Ronstadt",
    "Van Halen",
    "Bob Seger",
    "Aerosmith",
    "The Black Eyed Peas",
    "Nelly",
    "Carole King",
    "Justin Timberlake",
    "The Monkees",
    "Kenny Rogers",
    "Heart",
    "Tim McGraw",
    "Barry Manilow",
    "R. Kelly",
    "Journey",
    "Simon & Garfunkel",
    "Michael Bolton",
    "Ed Sheeran",
    "Kelly Clarkson",
    "Pink Floyd",
    "Queen",
    "Mary J. Blige",
    "Kanye West",
    "Three Dog Night",
    "Commodores",
    "Paula Abdul",
    "Bryan Adams",
    "Chris Brown",
    "Guns N' Roses",
    "Def Leppard",
    "Huey Lewis & The News",
    "Linkin Park",
    "James Taylor",
    "Creedence Clearwater Revival",
    "Tom Petty And The Heartbreakers",
    "Paul Simon",
    "Backstreet Boys",
    "Lil Wayne",
    "Carrie Underwood",
    "Andy Williams",
    "Styx",
    "George Michael",
    "Cher",
    "TLC",
    "Shania Twain",
    "The Doobie Brothers",
    "The 4 Seasons",
    "Peter, Paul & Mary",
    "Kenny Chesney",
    "Destiny's Child",
    "50 Cent",
    "Ray Charles",
    "Genesis",
    "The Police",
    "Rascal Flatts",
    "Ludacris",
    "Gloria Estefan",
    "George Harrison",
    "Alan Jackson",
)


def search_artists(query: str) -> list[str]:
    """סינון הרשימה לפי טקסט חופשי, בלי תלות ברישיות."""
    query = (query or "").strip().lower()
    if not query:
        return list(GREATEST_ARTISTS)
    return [name for name in GREATEST_ARTISTS if query in name.lower()]
