"""שירי המצעד המוכרים ביותר לפי עשור — נוצר, לא נערך ידנית.

נוצר על ידי `tools/build_charts.py` מתוך מצעדי Billboard Hot 100
ההיסטוריים (https://github.com/mhollingshead/billboard-hot-100).
כל עשור מדורג לפי ביצועים בפועל במצעד, עם תקרה של שני שירים לאמן.

ה-Hot 100 מתחיל ב-4 באוגוסט 1958, ולכן 1950–1957 מגיעות
מהרשימות האצורות ב-`classics.py` ולא מכאן.
"""

DECADE_HITS: dict[str, tuple[dict, ...]] = {
    "50's": (
        {"artist": "Bobby Darin", "track": "Mack The Knife", "year": 1959},
        {"artist": "Tommy Edwards", "track": "It's All In The Game", "year": 1958},
        {"artist": "Johnny Horton", "track": "The Battle Of New Orleans", "year": 1959},
        {"artist": "The Teddy Bears", "track": "To Know Him, Is To Love Him", "year": 1958},
        {"artist": "Johnny Preston", "track": "Running Bear", "year": 1959},
        {"artist": "Jim Reeves", "track": "He'll Have To Go", "year": 1959},
        {"artist": "Lloyd Price", "track": "Stagger Lee", "year": 1958},
        {"artist": "Domenico Modugno", "track": "Nel Blu Dipinto Di Blu (Volare)", "year": 1958},
        {"artist": "Frankie Avalon", "track": "Venus", "year": 1959},
        {"artist": "The Platters", "track": "Smoke Gets In Your Eyes", "year": 1958},
        {"artist": "The Kingston Trio", "track": "Tom Dooley", "year": 1958},
        {"artist": "Conway Twitty", "track": "It's Only Make Believe", "year": 1958},
        {"artist": "The Browns", "track": "The Three Bells", "year": 1959},
        {"artist": "Guy Mitchell", "track": "Heartaches By The Number", "year": 1959},
        {"artist": "Paul Anka", "track": "Lonely Boy", "year": 1959},
        {"artist": "Marty Robbins", "track": "El Paso", "year": 1959},
        {"artist": "The Fleetwoods", "track": "Mr. Blue", "year": 1959},
        {"artist": "Ritchie Valens", "track": "Donna", "year": 1958},
        {"artist": "Clyde McPhatter", "track": "A Lover's Question", "year": 1958},
        {"artist": "Bobby Day", "track": "Rock-in Robin", "year": 1958},
        {"artist": "The Fleetwoods", "track": "Come Softly To Me", "year": 1959},
        {"artist": "Big Bopper", "track": "Chantilly Lace", "year": 1958},
        {"artist": "Mark Dinning", "track": "Teen Angel", "year": 1959},
        {"artist": "Santo & Johnny", "track": "Sleep Walk", "year": 1959},
        {"artist": "Brenda Lee", "track": "Sweet Nothin's", "year": 1959},
        {"artist": "The Everly Brothers", "track": "Bird Dog", "year": 1958},
        {"artist": "Paul Anka", "track": "Put Your Head On My Shoulder", "year": 1959},
        {"artist": "Carl Dobkins, Jr.", "track": "My Heart Is An Open Book", "year": 1959},
        {"artist": "The Elegants", "track": "Little Star", "year": 1958},
        {"artist": "Lloyd Price and His Orchestra", "track": "Personality", "year": 1959},
        {"artist": "Cozy Cole", "track": "Topsy II", "year": 1958},
        {"artist": "The Crests", "track": "16 Candles", "year": 1958},
        {"artist": "Ricky Nelson", "track": "Lonesome Town", "year": 1958},
        {"artist": "Jimmy Jones", "track": "Handy Man", "year": 1959},
        {"artist": "Wilbert Harrison", "track": "Kansas City", "year": 1959},
        {"artist": "Bobby Darin", "track": "Dream Lover", "year": 1959},
        {"artist": "The Shirelles", "track": "Dedicated To The One I Love", "year": 1959},
        {"artist": "The Chipmunks", "track": "The Chipmunk Song", "year": 1958},
        {"artist": "Billy Grammer", "track": "Gotta Travel On", "year": 1958},
        {"artist": "Frankie Avalon", "track": "Why", "year": 1959},
        {"artist": "Della Reese", "track": "Don't You Know", "year": 1959},
        {"artist": "Dave \"Baby\" Cortez", "track": "The Happy Organ", "year": 1959},
        {"artist": "Jackie Wilson", "track": "Lonely Teardrops", "year": 1958},
        {"artist": "Dodie Stevens", "track": "Pink Shoe Laces", "year": 1959},
        {"artist": "Little Anthony And The Imperials", "track": "Tears On My Pillow", "year": 1958},
        {"artist": "Jerry Wallace", "track": "Primrose Lane", "year": 1959},
        {"artist": "Miss Toni Fisher", "track": "The Big Hurt", "year": 1959},
        {"artist": "The Tommy Dorsey Orchestra", "track": "Tea For Two Cha Cha", "year": 1958},
        {"artist": "Robin Luke", "track": "Susie Darlin'", "year": 1958},
        {"artist": "Connie Francis", "track": "My Happiness", "year": 1958},
        {"artist": "Elvis Presley", "track": "One Night", "year": 1958},
        {"artist": "Elvis Presley", "track": "A Big Hunk O' Love", "year": 1959},
        {"artist": "The Drifters", "track": "There Goes My Baby", "year": 1959},
        {"artist": "Phil Phillips", "track": "Sea Of Love", "year": 1959},
        {"artist": "Brook Benton", "track": "It's Just A Matter Of Time", "year": 1959},
        {"artist": "The Everly Brothers", "track": "('til) I Kissed You", "year": 1959},
        {"artist": "Steve Lawrence", "track": "Pretty Blue Eyes", "year": 1959},
        {"artist": "Jimmy Clanton And His Rockets", "track": "Just A Dream", "year": 1958},
        {"artist": "LaVern Baker", "track": "I Cried A Tear", "year": 1958},
        {"artist": "Sammy Turner", "track": "Lavender-Blue", "year": 1959},
    ),
    "60's": (
        {"artist": "Chubby Checker", "track": "The Twist", "year": 1960},
        {"artist": "The Beatles", "track": "Hey Jude", "year": 1968},
        {"artist": "Percy Faith And His Orchestra", "track": "The Theme From \"A Summer Place\"", "year": 1960},
        {"artist": "Bobby Lewis", "track": "Tossin' And Turnin'", "year": 1961},
        {"artist": "B.J. Thomas", "track": "Raindrops Keep Fallin' On My Head", "year": 1969},
        {"artist": "The Archies", "track": "Sugar, Sugar", "year": 1969},
        {"artist": "The Beatles", "track": "I Want To Hold Your Hand", "year": 1964},
        {"artist": "The Monkees", "track": "I'm A Believer", "year": 1966},
        {"artist": "Marvin Gaye", "track": "I Heard It Through The Grapevine", "year": 1968},
        {"artist": "The 5th Dimension", "track": "Aquarius/Let The Sunshine In (The Flesh Failures)", "year": 1969},
        {"artist": "Elvis Presley", "track": "It's Now Or Never", "year": 1960},
        {"artist": "Brenda Lee", "track": "I'm Sorry", "year": 1960},
        {"artist": "Elvis Presley", "track": "Are You Lonesome To-night?", "year": 1960},
        {"artist": "Ray Charles", "track": "I Can't Stop Loving You", "year": 1962},
        {"artist": "Louis Armstrong And The All Stars", "track": "Hello, Dolly!", "year": 1964},
        {"artist": "Paul Mauriat And His Orchestra", "track": "Love Is Blue (L'amour Est Bleu)", "year": 1968},
        {"artist": "The 4 Seasons", "track": "Big Girls Don't Cry", "year": 1962},
        {"artist": "Lulu", "track": "To Sir With Love", "year": 1967},
        {"artist": "Jimmy Dean", "track": "Big Bad John", "year": 1961},
        {"artist": "The Everly Brothers", "track": "Cathy's Clown", "year": 1960},
        {"artist": "Jimmy Gilmer And The Fireballs", "track": "Sugar Shack", "year": 1963},
        {"artist": "Bobby Goldsboro", "track": "Honey", "year": 1968},
        {"artist": "Joey Dee & the Starliters", "track": "Peppermint Twist - Part I", "year": 1961},
        {"artist": "Otis Redding", "track": "(Sittin' On) The Dock Of The Bay", "year": 1968},
        {"artist": "Sly & The Family Stone", "track": "Everyday People", "year": 1968},
        {"artist": "The Rolling Stones", "track": "Honky Tonk Women", "year": 1969},
        {"artist": "Chubby Checker", "track": "Limbo Rock", "year": 1962},
        {"artist": "Bert Kaempfert And His Orchestra", "track": "Wonderland By Night", "year": 1960},
        {"artist": "The Rascals", "track": "People Got To Be Free", "year": 1968},
        {"artist": "Zager & Evans", "track": "In The Year 2525", "year": 1969},
        {"artist": "Bobby Vinton", "track": "Roses Are Red (My Love)", "year": 1962},
        {"artist": "Del Shannon", "track": "Runaway", "year": 1961},
        {"artist": "Mr. Acker Bilk", "track": "Stranger On The Shore", "year": 1962},
        {"artist": "The Doors", "track": "Light My Fire", "year": 1967},
        {"artist": "Ferrante & Teicher", "track": "Exodus", "year": 1960},
        {"artist": "The Drifters", "track": "Save The Last Dance For Me", "year": 1960},
        {"artist": "Diana Ross & The Supremes", "track": "Love Child", "year": 1968},
        {"artist": "The Temptations", "track": "I Can't Get Next To You", "year": 1969},
        {"artist": "The Box Tops", "track": "The Letter", "year": 1967},
        {"artist": "Tommy Roe", "track": "Dizzy", "year": 1969},
        {"artist": "The Chiffons", "track": "He's So Fine", "year": 1963},
        {"artist": "The Association", "track": "Windy", "year": 1967},
        {"artist": "Connie Francis", "track": "Everybody's Somebody's Fool", "year": 1960},
        {"artist": "The 4 Seasons", "track": "Sherry", "year": 1962},
        {"artist": "The New Vaudeville Band", "track": "Winchester Cathedral", "year": 1966},
        {"artist": "SSgt Barry Sadler", "track": "The Ballad Of The Green Berets", "year": 1966},
        {"artist": "Tommy James And The Shondells", "track": "Crimson And Clover", "year": 1968},
        {"artist": "Connie Francis", "track": "My Heart Has A Mind Of Its Own", "year": 1960},
        {"artist": "The Rolling Stones", "track": "(I Can't Get No) Satisfaction", "year": 1965},
        {"artist": "Bobbie Gentry", "track": "Ode To Billie Joe", "year": 1967},
        {"artist": "Johnny Horton", "track": "North To Alaska", "year": 1960},
        {"artist": "Herb Alpert", "track": "This Guy's In Love With You", "year": 1968},
        {"artist": "Jackson 5", "track": "I Want You Back", "year": 1969},
        {"artist": "The Monkees", "track": "Daydream Believer", "year": 1967},
        {"artist": "The Shirelles", "track": "Will You Love Me Tomorrow", "year": 1960},
        {"artist": "The Singing Nun (Soeur Sourire)", "track": "Dominique", "year": 1963},
        {"artist": "Roy Orbison And The Candy Men", "track": "Oh, Pretty Woman", "year": 1964},
        {"artist": "Bobby Vinton", "track": "There! I've Said It Again", "year": 1963},
        {"artist": "Nancy Sinatra & Frank Sinatra", "track": "Somethin' Stupid", "year": 1967},
        {"artist": "Connie Stevens", "track": "Sixteen Reasons", "year": 1960},
        {"artist": "Lawrence Welk And His Orchestra", "track": "Calcutta", "year": 1960},
        {"artist": "The Turtles", "track": "Happy Together", "year": 1967},
        {"artist": "Floyd Cramer", "track": "Last Date", "year": 1960},
        {"artist": "The Supremes", "track": "Baby Love", "year": 1964},
        {"artist": "The 5th Dimension", "track": "Wedding Bell Blues", "year": 1969},
        {"artist": "The Young Rascals", "track": "Groovin'", "year": 1967},
        {"artist": "The Tornadoes", "track": "Telstar", "year": 1962},
        {"artist": "Peter, Paul & Mary", "track": "Leaving On A Jet Plane", "year": 1969},
        {"artist": "The Righteous Brothers", "track": "You've Lost That Lovin' Feelin'", "year": 1964},
        {"artist": "Paul and Paula", "track": "Hey Paula", "year": 1962},
        {"artist": "The Tokens", "track": "The Lion Sleeps Tonight", "year": 1961},
        {"artist": "Ricky Nelson", "track": "Travelin' Man", "year": 1961},
        {"artist": "The Marvelettes", "track": "Please Mr. Postman", "year": 1961},
        {"artist": "Steve Lawrence", "track": "Go Away Little Girl", "year": 1962},
        {"artist": "The Shirelles", "track": "Soldier Boy", "year": 1962},
        {"artist": "Bruce Channel", "track": "Hey! Baby", "year": 1962},
        {"artist": "The Angels", "track": "My Boyfriend's Back", "year": 1963},
        {"artist": "The Brothers Four", "track": "Greenfields", "year": 1960},
        {"artist": "The Beach Boys", "track": "I Get Around", "year": 1964},
        {"artist": "Diana Ross & The Supremes", "track": "Someday We'll Be Together", "year": 1969},
        {"artist": "The Highwaymen", "track": "Michael", "year": 1961},
        {"artist": "Steam", "track": "Na Na Hey Hey Kiss Him Goodbye", "year": 1969},
        {"artist": "Gene Chandler", "track": "Duke Of Earl", "year": 1962},
        {"artist": "Four Tops", "track": "I Can't Help Myself (Sugar Pie Honey Bunch)", "year": 1965},
        {"artist": "Petula Clark", "track": "Downtown", "year": 1964},
        {"artist": "Shelley Fabares", "track": "Johnny Angel", "year": 1962},
        {"artist": "Mary Wells", "track": "My Guy", "year": 1964},
        {"artist": "Kyu Sakamoto", "track": "Sukiyaki", "year": 1963},
        {"artist": "Dion", "track": "Runaround Sue", "year": 1961},
        {"artist": "Little Stevie Wonder", "track": "Fingertips - Pt 2", "year": 1963},
        {"artist": "The Supremes", "track": "Come See About Me", "year": 1964},
        {"artist": "Cream", "track": "Sunshine Of Your Love", "year": 1968},
        {"artist": "Roy Orbison", "track": "Only The Lonely (Know How I Feel)", "year": 1960},
        {"artist": "Archie Bell & The Drells", "track": "Tighten Up", "year": 1968},
        {"artist": "The Byrds", "track": "Turn! Turn! Turn! (To Everything There Is A Season)", "year": 1965},
        {"artist": "John Fred And The Playboys", "track": "Judy In Disguise (With Glasses)", "year": 1967},
        {"artist": "The Crystals", "track": "He's A Rebel", "year": 1962},
        {"artist": "The Marcels", "track": "Blue Moon", "year": 1961},
        {"artist": "Bobby Vee", "track": "Take Good Care Of My Baby", "year": 1961},
        {"artist": "Dee Dee Sharp", "track": "Mashed Potato Time", "year": 1962},
        {"artist": "Hugo Montenegro, His Orchestra And Chorus", "track": "The Good, The Bad And The Ugly", "year": 1968},
        {"artist": "Strawberry Alarm Clock", "track": "Incense And Peppermints", "year": 1967},
        {"artist": "Little Peggy March", "track": "I Will Follow Him", "year": 1963},
        {"artist": "David Rose and His Orchestra", "track": "The Stripper", "year": 1962},
        {"artist": "The Righteous Brothers", "track": "(You're My) Soul And Inspiration", "year": 1966},
        {"artist": "Simon & Garfunkel", "track": "Mrs. Robinson", "year": 1968},
        {"artist": "Sam The Sham and the Pharaohs", "track": "Wooly Bully", "year": 1965},
        {"artist": "Henry Mancini And His Orchestra", "track": "Love Theme From Romeo & Juliet", "year": 1969},
        {"artist": "Gladys Knight And The Pips", "track": "I Heard It Through The Grapevine", "year": 1967},
        {"artist": "The Association", "track": "Cherish", "year": 1966},
        {"artist": "The Ventures", "track": "Walk -- Don't Run", "year": 1960},
        {"artist": "Manfred Mann", "track": "Do Wah Diddy Diddy", "year": 1964},
        {"artist": "? (Question Mark) & The Mysterians", "track": "96 Tears", "year": 1966},
        {"artist": "Hank Ballard And The Midnighters", "track": "Finger Poppin' Time", "year": 1960},
        {"artist": "The Dixie Cups", "track": "Chapel Of Love", "year": 1964},
        {"artist": "Kathy Young", "track": "A Thousand Stars", "year": 1960},
        {"artist": "Dean Martin", "track": "Everybody Loves Somebody", "year": 1964},
        {"artist": "Four Tops", "track": "Reach Out I'll Be There", "year": 1966},
        {"artist": "U.S. Bonds", "track": "Quarter To Three", "year": 1961},
        {"artist": "Dale & Grace", "track": "I'm Leaving It Up To You", "year": 1963},
    ),
    "70's": (
        {"artist": "Debby Boone", "track": "You Light Up My Life", "year": 1977},
        {"artist": "Bee Gees", "track": "How Deep Is Your Love", "year": 1977},
        {"artist": "Andy Gibb", "track": "I Just Want To Be Your Everything", "year": 1977},
        {"artist": "Chic", "track": "Le Freak", "year": 1978},
        {"artist": "Rod Stewart", "track": "Tonight's The Night (Gonna Be Alright)", "year": 1976},
        {"artist": "Andy Gibb", "track": "Shadow Dancing", "year": 1978},
        {"artist": "Bee Gees", "track": "Night Fever", "year": 1978},
        {"artist": "The Knack", "track": "My Sharona", "year": 1979},
        {"artist": "The Emotions", "track": "Best Of My Love", "year": 1977},
        {"artist": "Captain & Tennille", "track": "Do That To Me One More Time", "year": 1979},
        {"artist": "Exile", "track": "Kiss You All Over", "year": 1978},
        {"artist": "Barbra Streisand", "track": "Evergreen (Love Theme From \"A Star Is Born\")", "year": 1976},
        {"artist": "Paul Davis", "track": "I Go Crazy", "year": 1977},
        {"artist": "Player", "track": "Baby Come Back", "year": 1977},
        {"artist": "Queen", "track": "Crazy Little Thing Called Love", "year": 1979},
        {"artist": "Gloria Gaynor", "track": "I Will Survive", "year": 1978},
        {"artist": "Roberta Flack", "track": "The First Time Ever I Saw Your Face", "year": 1972},
        {"artist": "Dawn", "track": "Tie A Yellow Ribbon Round The Ole Oak Tree", "year": 1973},
        {"artist": "Gilbert O'Sullivan", "track": "Alone Again (Naturally)", "year": 1972},
        {"artist": "Three Dog Night", "track": "Joy To The World", "year": 1971},
        {"artist": "Michael Jackson", "track": "Rock With You", "year": 1979},
        {"artist": "Donna Summer", "track": "Hot Stuff", "year": 1979},
        {"artist": "Rod Stewart", "track": "Da Ya Think I'm Sexy?", "year": 1978},
        {"artist": "Walter Murphy & The Big Apple Band", "track": "A Fifth Of Beethoven", "year": 1976},
        {"artist": "A Taste Of Honey", "track": "Boogie Oogie Oogie", "year": 1978},
        {"artist": "Wings", "track": "Silly Love Songs", "year": 1976},
        {"artist": "Donna Summer", "track": "Bad Girls", "year": 1979},
        {"artist": "Don McLean", "track": "American Pie (Parts I & II)", "year": 1971},
        {"artist": "Wild Cherry", "track": "Play That Funky Music", "year": 1976},
        {"artist": "Jackson 5", "track": "I'll Be There", "year": 1970},
        {"artist": "Village People", "track": "Y.M.C.A.", "year": 1978},
        {"artist": "Carole King", "track": "It's Too Late/I Feel The Earth Move", "year": 1971},
        {"artist": "Nick Gilder", "track": "Hot Child In The City", "year": 1978},
        {"artist": "Peaches & Herb", "track": "Reunited", "year": 1979},
        {"artist": "Barbra Streisand", "track": "The Way We Were", "year": 1973},
        {"artist": "The Partridge Family Starring Shirley Jones", "track": "I Think I Love You", "year": 1970},
        {"artist": "Simon & Garfunkel", "track": "Bridge Over Troubled Water", "year": 1970},
        {"artist": "Marvin Gaye", "track": "Let's Get It On", "year": 1973},
        {"artist": "KC And The Sunshine Band", "track": "Please Don't Go", "year": 1979},
        {"artist": "Carpenters", "track": "(They Long To Be) Close To You", "year": 1970},
        {"artist": "Robert John", "track": "Sad Eyes", "year": 1979},
        {"artist": "Glen Campbell", "track": "Rhinestone Cowboy", "year": 1975},
        {"artist": "The Captain & Tennille", "track": "Love Will Keep Us Together", "year": 1975},
        {"artist": "Rupert Holmes", "track": "Escape (The Pina Colada Song)", "year": 1979},
        {"artist": "The Manhattans", "track": "Kiss And Say Goodbye", "year": 1976},
        {"artist": "Alicia Bridges", "track": "I Love The Nightlife (Disco 'round)", "year": 1978},
        {"artist": "Dawn", "track": "Knock Three Times", "year": 1970},
        {"artist": "Roberta Flack", "track": "Killing Me Softly With His Song", "year": 1973},
        {"artist": "Commodores", "track": "Three Times A Lady", "year": 1978},
        {"artist": "M", "track": "Pop Muzik", "year": 1979},
        {"artist": "Johnny Nash", "track": "I Can See Clearly Now", "year": 1972},
        {"artist": "Marilyn McCoo & Billy Davis Jr.", "track": "You Don't Have To Be A Star (To Be In My Show)", "year": 1976},
        {"artist": "Mary Macgregor", "track": "Torn Between Two Lovers", "year": 1976},
        {"artist": "Paul McCartney And Wings", "track": "My Love", "year": 1973},
        {"artist": "Nilsson", "track": "Without You", "year": 1971},
        {"artist": "The 4 Seasons", "track": "December, 1963 (Oh, What a Night)", "year": 1975},
        {"artist": "The Miracles", "track": "Love Machine (Part 1)", "year": 1975},
        {"artist": "Elton John & Kiki Dee", "track": "Don't Go Breaking My Heart", "year": 1976},
        {"artist": "The Elton John Band", "track": "Philadelphia Freedom", "year": 1975},
        {"artist": "Crystal Gayle", "track": "Don't It Make My Brown Eyes Blue", "year": 1977},
        {"artist": "Samantha Sang", "track": "Emotion", "year": 1977},
        {"artist": "John Travolta & Olivia Newton-John", "track": "You're The One That I Want", "year": 1978},
        {"artist": "Herb Alpert", "track": "Rise", "year": 1979},
        {"artist": "Jim Croce", "track": "Bad, Bad Leroy Brown", "year": 1973},
        {"artist": "Carly Simon", "track": "You're So Vain", "year": 1972},
        {"artist": "Rick Dees & His Cast Of Idiots", "track": "Disco Duck (Part I)", "year": 1976},
        {"artist": "Commodores", "track": "Still", "year": 1979},
        {"artist": "Morris Albert", "track": "Feelings", "year": 1975},
        {"artist": "Eddie Kendricks", "track": "Keep On Truckin' (Part 1)", "year": 1973},
        {"artist": "Chicago", "track": "If You Leave Me Now", "year": 1976},
        {"artist": "Eric Clapton", "track": "Lay Down Sally", "year": 1978},
        {"artist": "Kenny Nolan", "track": "I Like Dreamin'", "year": 1976},
        {"artist": "Thelma Houston", "track": "Don't Leave Me This Way", "year": 1976},
        {"artist": "Melanie", "track": "Brand New Key", "year": 1971},
        {"artist": "Terry Jacks", "track": "Seasons In The Sun", "year": 1974},
        {"artist": "The Osmonds", "track": "One Bad Apple", "year": 1971},
        {"artist": "Anita Ward", "track": "Ring My Bell", "year": 1979},
        {"artist": "Anne Murray", "track": "You Needed Me", "year": 1978},
        {"artist": "KC And The Sunshine Band", "track": "(Shake, Shake, Shake) Shake Your Booty", "year": 1976},
        {"artist": "Johnnie Taylor", "track": "Disco Lady", "year": 1976},
        {"artist": "Frankie Valli", "track": "Grease", "year": 1978},
        {"artist": "Heatwave", "track": "Boogie Nights", "year": 1977},
        {"artist": "Styx", "track": "Babe", "year": 1979},
        {"artist": "Gary Wright", "track": "Love Is Alive", "year": 1976},
        {"artist": "Kris Kristofferson", "track": "Why Me", "year": 1973},
        {"artist": "Elton John", "track": "Crocodile Rock", "year": 1972},
        {"artist": "George Harrison", "track": "My Sweet Lord/Isn't It A Pity", "year": 1970},
        {"artist": "Sammy Davis, Jr.", "track": "The Candy Man", "year": 1972},
        {"artist": "Charlie Rich", "track": "The Most Beautiful Girl", "year": 1973},
        {"artist": "Leo Sayer", "track": "You Make Me Feel Like Dancing", "year": 1976},
        {"artist": "Dionne Warwick", "track": "I'll Never Love This Way Again", "year": 1979},
        {"artist": "Gladys Knight And The Pips", "track": "Midnight Train To Georgia", "year": 1973},
        {"artist": "Barry Manilow", "track": "I Write The Songs", "year": 1975},
        {"artist": "Carpenters", "track": "Top Of The World", "year": 1973},
        {"artist": "Yvonne Elliman", "track": "If I Can't Have You", "year": 1978},
        {"artist": "Hot", "track": "Angel In Your Arms", "year": 1977},
        {"artist": "Mac Davis", "track": "Baby Don't Get Hooked On Me", "year": 1972},
        {"artist": "Alan O'Day", "track": "Undercover Angel", "year": 1977},
        {"artist": "England Dan & John Ford Coley", "track": "I'd Really Love To See You Tonight", "year": 1976},
        {"artist": "Billy Preston", "track": "Will It Go Round In Circles", "year": 1973},
        {"artist": "Billy Joel", "track": "Just The Way You Are", "year": 1977},
        {"artist": "Barbra Streisand & Neil Diamond", "track": "You Don't Bring Me Flowers", "year": 1978},
        {"artist": "The Raiders", "track": "Indian Reservation (The Lament Of The Cherokee Reservation Indian)", "year": 1971},
        {"artist": "Olivia Newton-John", "track": "A Little More Love", "year": 1978},
        {"artist": "ABBA", "track": "Dancing Queen", "year": 1976},
        {"artist": "Bill Withers", "track": "Lean On Me", "year": 1972},
        {"artist": "Cher", "track": "Half-Breed", "year": 1973},
        {"artist": "Diana Ross", "track": "Touch Me In The Morning", "year": 1973},
        {"artist": "Chic", "track": "Dance, Dance, Dance (Yowsah, Yowsah, Yowsah)", "year": 1977},
        {"artist": "Rita Coolidge", "track": "(Your Love Has Lifted Me) Higher And Higher", "year": 1977},
        {"artist": "Joe Tex", "track": "I Gotcha", "year": 1972},
        {"artist": "Rose Royce", "track": "Car Wash", "year": 1976},
        {"artist": "Daryl Hall John Oates", "track": "Sara Smile", "year": 1976},
        {"artist": "Love Unlimited Orchestra", "track": "Love's Theme", "year": 1973},
        {"artist": "Carly Simon", "track": "Nobody Does It Better", "year": 1977},
        {"artist": "Billy Paul", "track": "Me And Mrs. Jones", "year": 1972},
        {"artist": "Smokey Robinson", "track": "Cruisin'", "year": 1979},
        {"artist": "Jackson 5", "track": "Dancing Machine", "year": 1974},
        {"artist": "Smokey Robinson & The Miracles", "track": "The Tears Of A Clown", "year": 1970},
        {"artist": "The Rolling Stones", "track": "Miss You", "year": 1978},
    ),
    "80's": (
        {"artist": "Olivia Newton-John", "track": "Physical", "year": 1981},
        {"artist": "Kim Carnes", "track": "Bette Davis Eyes", "year": 1981},
        {"artist": "Diana Ross & Lionel Richie", "track": "Endless Love", "year": 1981},
        {"artist": "The Police", "track": "Every Breath You Take", "year": 1983},
        {"artist": "Irene Cara", "track": "Flashdance...What A Feeling", "year": 1983},
        {"artist": "Survivor", "track": "Eye Of The Tiger", "year": 1982},
        {"artist": "Queen", "track": "Another One Bites The Dust", "year": 1980},
        {"artist": "The J. Geils Band", "track": "Centerfold", "year": 1981},
        {"artist": "Blondie", "track": "Call Me", "year": 1980},
        {"artist": "Kenny Rogers", "track": "Lady", "year": 1980},
        {"artist": "Michael Jackson", "track": "Billie Jean", "year": 1983},
        {"artist": "Paul McCartney And Michael Jackson", "track": "Say Say Say", "year": 1983},
        {"artist": "Rick Springfield", "track": "Jessie's Girl", "year": 1981},
        {"artist": "Diana Ross", "track": "Upside Down", "year": 1980},
        {"artist": "John Lennon", "track": "(Just Like) Starting Over", "year": 1980},
        {"artist": "Bonnie Tyler", "track": "Total Eclipse Of The Heart", "year": 1983},
        {"artist": "Lionel Richie", "track": "All Night Long (All Night)", "year": 1983},
        {"artist": "The Human League", "track": "Don't You Want Me", "year": 1982},
        {"artist": "Joan Jett & The Blackhearts", "track": "I Love Rock 'N Roll", "year": 1982},
        {"artist": "Paul McCartney And Stevie Wonder", "track": "Ebony And Ivory", "year": 1982},
        {"artist": "Pink Floyd", "track": "Another Brick In The Wall (Part II)", "year": 1980},
        {"artist": "John Cougar", "track": "Hurts So Good", "year": 1982},
        {"artist": "Men At Work", "track": "Down Under", "year": 1982},
        {"artist": "The Steve Miller Band", "track": "Abracadabra", "year": 1982},
        {"artist": "Daryl Hall John Oates", "track": "Maneater", "year": 1982},
        {"artist": "Laura Branigan", "track": "Gloria", "year": 1982},
        {"artist": "Prince", "track": "When Doves Cry", "year": 1984},
        {"artist": "Tina Turner", "track": "What's Love Got To Do With It", "year": 1984},
        {"artist": "Barbra Streisand", "track": "Woman In Love", "year": 1980},
        {"artist": "Kool & The Gang", "track": "Celebration", "year": 1980},
        {"artist": "Christopher Cross", "track": "Arthur's Theme (Best That You Can Do)", "year": 1981},
        {"artist": "Kenny Rogers", "track": "Islands In The Stream", "year": 1983},
        {"artist": "Michael Jackson", "track": "Beat It", "year": 1983},
        {"artist": "Patti Austin", "track": "Baby, Come To Me", "year": 1982},
        {"artist": "John Cougar", "track": "Jack & Diane", "year": 1982},
        {"artist": "Van Halen", "track": "Jump", "year": 1984},
        {"artist": "Dionne & Friends", "track": "That's What Friends Are For", "year": 1985},
        {"artist": "Eddie Rabbitt", "track": "I Love A Rainy Night", "year": 1980},
        {"artist": "Chicago", "track": "Hard To Say I'm Sorry", "year": 1982},
        {"artist": "Madonna", "track": "Like A Virgin", "year": 1984},
        {"artist": "Kenny Loggins", "track": "Footloose", "year": 1984},
        {"artist": "Foreigner", "track": "Waiting For A Girl Like You", "year": 1981},
        {"artist": "Phil Collins", "track": "Against All Odds (Take A Look At Me Now)", "year": 1984},
        {"artist": "Young M.C.", "track": "Bust A Move", "year": 1989},
        {"artist": "Olivia Newton-John", "track": "Magic", "year": 1980},
        {"artist": "Stevie Wonder", "track": "I Just Called To Say I Love You", "year": 1984},
        {"artist": "Dolly Parton", "track": "9 To 5", "year": 1980},
        {"artist": "The Bangles", "track": "Walk Like An Egyptian", "year": 1986},
        {"artist": "Paul McCartney And Wings", "track": "Coming Up (Live At Glasgow)", "year": 1980},
        {"artist": "Lionel Richie", "track": "Say You, Say Me", "year": 1985},
        {"artist": "REO Speedwagon", "track": "Keep On Loving You", "year": 1980},
        {"artist": "Billy Joel", "track": "It's Still Rock And Roll To Me", "year": 1980},
        {"artist": "Lipps, Inc.", "track": "Funkytown", "year": 1980},
        {"artist": "Quarterflash", "track": "Harden My Heart", "year": 1981},
        {"artist": "Toni Basil", "track": "Mickey", "year": 1982},
        {"artist": "Daryl Hall John Oates", "track": "Kiss On My List", "year": 1981},
        {"artist": "Yes", "track": "Owner Of A Lonely Heart", "year": 1983},
        {"artist": "George Michael", "track": "Faith", "year": 1987},
        {"artist": "Paula Abdul", "track": "Straight Up", "year": 1988},
        {"artist": "Culture Club", "track": "Karma Chameleon", "year": 1983},
        {"artist": "Wham!", "track": "Careless Whisper", "year": 1984},
        {"artist": "Phil Collins", "track": "Another Day In Paradise", "year": 1989},
        {"artist": "Eurythmics", "track": "Sweet Dreams (Are Made Of This)", "year": 1983},
        {"artist": "Juice Newton", "track": "Queen Of Hearts", "year": 1981},
        {"artist": "Ray Parker Jr.", "track": "Ghostbusters", "year": 1984},
        {"artist": "Wham!", "track": "Wake Me Up Before You Go-Go", "year": 1984},
        {"artist": "Air Supply", "track": "All Out Of Love", "year": 1980},
        {"artist": "Joey Scarbury", "track": "Theme From \"Greatest American Hero\" (Believe It or Not)", "year": 1981},
        {"artist": "Men At Work", "track": "Who Can It Be Now?", "year": 1982},
        {"artist": "Chicago", "track": "Look Away", "year": 1988},
        {"artist": "Joe Cocker And Jennifer Warnes", "track": "Up Where We Belong", "year": 1982},
        {"artist": "The Rolling Stones", "track": "Start Me Up", "year": 1981},
        {"artist": "Michael Sembello", "track": "Maniac", "year": 1983},
        {"artist": "Patti LaBelle & Michael McDonald", "track": "On My Own", "year": 1986},
        {"artist": "Blondie", "track": "The Tide Is High", "year": 1980},
        {"artist": "Michael Bolton", "track": "How Am I Supposed To Live Without You", "year": 1989},
        {"artist": "Dire Straits", "track": "Money For Nothing", "year": 1985},
        {"artist": "Janet Jackson", "track": "Miss You Much", "year": 1989},
        {"artist": "Mr. Mister", "track": "Broken Wings", "year": 1985},
        {"artist": "Poison", "track": "Every Rose Has Its Thorn", "year": 1988},
        {"artist": "Bon Jovi", "track": "Livin' On A Prayer", "year": 1986},
        {"artist": "Eddie Rabbitt", "track": "You And I", "year": 1982},
        {"artist": "Paula Abdul (Duet", "track": "Opposites Attract", "year": 1989},
        {"artist": "Smokey Robinson", "track": "Being With You", "year": 1981},
        {"artist": "Culture Club", "track": "Do You Really Want To Hurt Me", "year": 1982},
        {"artist": "INXS", "track": "Need You Tonight", "year": 1987},
        {"artist": "Foreigner", "track": "I Want To Know What Love Is", "year": 1984},
        {"artist": "Starship", "track": "We Built This City", "year": 1985},
        {"artist": "Toto", "track": "Rosanna", "year": 1982},
        {"artist": "The Pointer Sisters", "track": "Slow Hand", "year": 1981},
        {"artist": "Tears For Fears", "track": "Everybody Wants To Rule The World", "year": 1985},
        {"artist": "Klymaxx", "track": "I Miss You", "year": 1985},
        {"artist": "Linda Ronstadt (Featuring Aaron Neville)", "track": "Don't Know Much", "year": 1989},
        {"artist": "Heart", "track": "Alone", "year": 1987},
        {"artist": "Soul II Soul", "track": "Back To Life", "year": 1989},
        {"artist": "Grover Washington, Jr.", "track": "Just The Two Of Us", "year": 1981},
        {"artist": "John Waite", "track": "Missing You", "year": 1984},
        {"artist": "Bette Midler", "track": "Wind Beneath My Wings (From \"Beaches\")", "year": 1989},
        {"artist": "Billy Ocean", "track": "Caribbean Queen (No More Love On The Run)", "year": 1984},
        {"artist": "Vangelis", "track": "Chariots Of Fire - Titles", "year": 1981},
        {"artist": "Rick Astley", "track": "Never Gonna Give You Up", "year": 1987},
        {"artist": "Cheap Trick", "track": "The Flame", "year": 1988},
        {"artist": "Phil Collins and Marilyn Martin", "track": "Separate Lives", "year": 1985},
        {"artist": "Whitney Houston", "track": "How Will I Know", "year": 1985},
        {"artist": "Starship", "track": "Nothing's Gonna Stop Us Now", "year": 1987},
        {"artist": "Steve Winwood", "track": "Roll With It", "year": 1988},
        {"artist": "John Lennon", "track": "Woman", "year": 1981},
        {"artist": "The Escape Club", "track": "Wild, Wild West", "year": 1988},
        {"artist": "The Pointer Sisters", "track": "I'm So Excited", "year": 1982},
        {"artist": "REO Speedwagon", "track": "Can't Fight This Feeling", "year": 1985},
        {"artist": "Los Lobos", "track": "La Bamba", "year": 1987},
        {"artist": "Guns N' Roses", "track": "Sweet Child O' Mine", "year": 1988},
        {"artist": "Deniece Williams", "track": "Let's Hear It For The Boy", "year": 1984},
        {"artist": "Chaka Khan", "track": "I Feel For You", "year": 1984},
        {"artist": "Whitesnake", "track": "Here I Go Again", "year": 1987},
        {"artist": "Elton John", "track": "Little Jeannie", "year": 1980},
        {"artist": "Air Supply", "track": "Making Love Out Of Nothing At All", "year": 1983},
        {"artist": "Gloria Estefan & Miami Sound Machine", "track": "Anything For You", "year": 1988},
        {"artist": "Milli Vanilli", "track": "Blame It On The Rain", "year": 1989},
        {"artist": "Richard Marx", "track": "Right Here Waiting", "year": 1989},
    ),
    "90's": (
        {"artist": "Santana", "track": "Smooth", "year": 1999},
        {"artist": "Los Del Rio", "track": "Macarena (Bayside Boys Mix)", "year": 1995},
        {"artist": "LeAnn Rimes", "track": "How Do I Live", "year": 1997},
        {"artist": "Jewel", "track": "Foolish Games/You Were Meant For Me", "year": 1996},
        {"artist": "Next", "track": "Too Close", "year": 1998},
        {"artist": "Toni Braxton", "track": "Un-Break My Heart", "year": 1996},
        {"artist": "Savage Garden", "track": "Truly Madly Deeply", "year": 1997},
        {"artist": "Elton John", "track": "Candle In The Wind 1997/Something About The Way You Look Tonight", "year": 1997},
        {"artist": "Boyz II Men", "track": "I'll Make Love To You", "year": 1994},
        {"artist": "Mariah Carey & Boyz II Men", "track": "One Sweet Day", "year": 1995},
        {"artist": "Boyz II Men", "track": "End Of The Road (From \"Boomerang\")", "year": 1992},
        {"artist": "Ace Of Base", "track": "The Sign", "year": 1994},
        {"artist": "Faith Hill", "track": "Breathe", "year": 1999},
        {"artist": "Tag Team", "track": "Whoomp! (There It Is)", "year": 1993},
        {"artist": "Puff Daddy & Faith Evans", "track": "I'll Be Missing You", "year": 1997},
        {"artist": "Lonestar", "track": "Amazed", "year": 1999},
        {"artist": "Usher", "track": "You Make Me Wanna...", "year": 1997},
        {"artist": "Brandy & Monica", "track": "The Boy Is Mine", "year": 1998},
        {"artist": "The Tony Rich Project", "track": "Nobody Knows", "year": 1995},
        {"artist": "Whitney Houston", "track": "I Will Always Love You", "year": 1992},
        {"artist": "Real McCoy", "track": "Another Night", "year": 1994},
        {"artist": "Shania Twain", "track": "You're Still The One", "year": 1998},
        {"artist": "All-4-One", "track": "I Swear", "year": 1994},
        {"artist": "Coolio", "track": "Gangsta's Paradise (From \"Dangerous Minds\")", "year": 1995},
        {"artist": "TLC", "track": "Waterfalls", "year": 1995},
        {"artist": "Toni Braxton", "track": "You're Makin' Me High/Let It Flow", "year": 1996},
        {"artist": "Celine Dion", "track": "Because You Loved Me (From \"Up Close & Personal\")", "year": 1996},
        {"artist": "Janet", "track": "Together Again", "year": 1997},
        {"artist": "Everything But The Girl", "track": "Missing", "year": 1995},
        {"artist": "702", "track": "Where My Girls At?", "year": 1999},
        {"artist": "Backstreet Boys", "track": "Quit Playing Games (With My Heart)", "year": 1997},
        {"artist": "Paula Cole", "track": "I Don't Want To Wait", "year": 1997},
        {"artist": "TLC", "track": "Creep", "year": 1994},
        {"artist": "Madonna", "track": "Take A Bow", "year": 1994},
        {"artist": "Third Eye Blind", "track": "Semi-Charmed Life", "year": 1997},
        {"artist": "Eric Clapton", "track": "Change The World", "year": 1996},
        {"artist": "Donna Lewis", "track": "I Love You Always Forever", "year": 1996},
        {"artist": "Keith Sweat", "track": "Twisted", "year": 1996},
        {"artist": "Mariah Carey", "track": "Dreamlover", "year": 1993},
        {"artist": "Marc Anthony", "track": "I Need To Know", "year": 1999},
        {"artist": "Blues Traveler", "track": "Run-Around", "year": 1995},
        {"artist": "Savage Garden", "track": "I Knew I Loved You", "year": 1999},
        {"artist": "Creed", "track": "Higher", "year": 1999},
        {"artist": "Tracy Chapman", "track": "Give Me One Reason", "year": 1996},
        {"artist": "Mark Morrison", "track": "Return Of The Mack", "year": 1997},
        {"artist": "Puff Daddy (Featuring Mase)", "track": "Can't Nobody Hold Me Down", "year": 1997},
        {"artist": "BLACKstreet (Featuring Dr. Dre)", "track": "No Diggity", "year": 1996},
        {"artist": "Faith Hill", "track": "This Kiss", "year": 1998},
        {"artist": "Mariah Carey", "track": "Fantasy", "year": 1995},
        {"artist": "K-Ci & JoJo", "track": "All My Life", "year": 1998},
        {"artist": "Celine Dion", "track": "The Power Of Love", "year": 1993},
        {"artist": "UB40", "track": "Can't Help Falling In Love (From \"Sliver\")", "year": 1993},
        {"artist": "Seal", "track": "Kiss From A Rose", "year": 1995},
        {"artist": "Duncan Sheik", "track": "Barely Breathing", "year": 1996},
        {"artist": "Gin Blossoms", "track": "Follow You Down/Til I Hear It From You", "year": 1996},
        {"artist": "Montell Jordan", "track": "This Is How We Do It", "year": 1995},
        {"artist": "Third Eye Blind", "track": "How's It Going To Be", "year": 1997},
        {"artist": "John Mellencamp", "track": "Wild Night", "year": 1994},
        {"artist": "En Vogue", "track": "Don't Let Go (Love)", "year": 1996},
        {"artist": "Keith Sweat", "track": "Nobody", "year": 1996},
        {"artist": "Ace Of Base", "track": "All That She Wants", "year": 1993},
        {"artist": "Brian McKnight", "track": "Back At One", "year": 1999},
        {"artist": "No Mercy", "track": "Where Do You Go", "year": 1996},
        {"artist": "Cher", "track": "Believe", "year": 1998},
        {"artist": "Sir Mix-A-Lot", "track": "Baby Got Back", "year": 1992},
        {"artist": "Goo Goo Dolls", "track": "Name", "year": 1995},
        {"artist": "Quad City DJ's", "track": "C'mon N' Ride It (The Train)", "year": 1996},
        {"artist": "Janet Jackson", "track": "That's The Way Love Goes", "year": 1993},
        {"artist": "Britney Spears", "track": "...Baby One More Time", "year": 1998},
        {"artist": "R. Kelly", "track": "I Believe I Can Fly (From \"Space Jam\")", "year": 1996},
        {"artist": "Lisa Loeb & Nine Stories", "track": "Stay (I Missed You) (From \"Reality Bites\")", "year": 1994},
        {"artist": "Monica", "track": "Angel Of Mine", "year": 1998},
        {"artist": "Des'ree", "track": "You Gotta Be", "year": 1994},
        {"artist": "Snap!", "track": "Rhythm Is A Dancer", "year": 1992},
        {"artist": "Bon Jovi", "track": "Always", "year": 1994},
        {"artist": "Destiny's Child", "track": "Say My Name", "year": 1999},
        {"artist": "Monica", "track": "The First Night", "year": 1998},
        {"artist": "Deborah Cox", "track": "Nobody's Supposed To Be Here", "year": 1998},
        {"artist": "Snow", "track": "Informer", "year": 1993},
        {"artist": "Christina Aguilera", "track": "Genie In A Bottle", "year": 1999},
        {"artist": "Dionne Farris", "track": "I Know", "year": 1995},
        {"artist": "Kris Kross", "track": "Jump", "year": 1992},
        {"artist": "Vanessa Williams", "track": "Save The Best For Last", "year": 1992},
        {"artist": "Sixpence None The Richer", "track": "Kiss Me", "year": 1998},
        {"artist": "Jennifer Lopez", "track": "If You Had My Love", "year": 1999},
        {"artist": "Goo Goo Dolls", "track": "Slide", "year": 1998},
        {"artist": "Alanis Morissette", "track": "Ironic", "year": 1996},
        {"artist": "Sophie B. Hawkins", "track": "As I Lay Me Down", "year": 1995},
        {"artist": "Jon Secada", "track": "Just Another Day", "year": 1992},
        {"artist": "Babyface", "track": "When Can I See You", "year": 1994},
        {"artist": "Ini Kamoze", "track": "Here Comes The Hotstepper (From \"Ready To Wear\")", "year": 1994},
        {"artist": "The Notorious B.I.G.", "track": "Mo Money Mo Problems", "year": 1997},
        {"artist": "Sheryl Crow", "track": "All I Wanna Do", "year": 1994},
        {"artist": "Crystal Waters", "track": "100% Pure Love", "year": 1994},
        {"artist": "The Verve Pipe", "track": "The Freshmen", "year": 1997},
        {"artist": "Spice Girls", "track": "Wannabe", "year": 1997},
        {"artist": "Jade", "track": "Don't Walk Away", "year": 1992},
        {"artist": "Hootie & The Blowfish", "track": "Hold My Hand", "year": 1994},
        {"artist": "Brandy", "track": "Sittin' Up In My Room (From \"Waiting To Exhale\")", "year": 1995},
        {"artist": "Bone Thugs-N-Harmony", "track": "Tha Crossroads", "year": 1996},
        {"artist": "All-4-One", "track": "I Can Love You Like That", "year": 1995},
        {"artist": "Bryan Adams", "track": "Have You Ever Really Loved A Woman?", "year": 1995},
        {"artist": "Will Smith", "track": "Gettin' Jiggy Wit It", "year": 1998},
        {"artist": "Dishwalla", "track": "Counting Blue Cars", "year": 1996},
        {"artist": "La Bouche", "track": "Be My Lover", "year": 1995},
        {"artist": "SWV", "track": "Weak", "year": 1993},
        {"artist": "Destiny's Child", "track": "No, No, No", "year": 1997},
        {"artist": "R. Kelly", "track": "Bump N' Grind", "year": 1994},
        {"artist": "Sugar Ray", "track": "Every Morning", "year": 1999},
        {"artist": "Hootie & The Blowfish", "track": "Only Wanna Be With You", "year": 1995},
        {"artist": "Merril Bainbridge", "track": "Mouth", "year": 1996},
        {"artist": "Sister Hazel", "track": "All For You", "year": 1997},
        {"artist": "Meat Loaf", "track": "I'd Do Anything For Love (But I Won't Do That)", "year": 1993},
        {"artist": "Melissa Etheridge", "track": "I'm The Only One", "year": 1994},
        {"artist": "Silk", "track": "Freak Me", "year": 1993},
        {"artist": "Divine", "track": "Lately", "year": 1998},
        {"artist": "Whitney Houston", "track": "My Love Is Your Love", "year": 1999},
        {"artist": "Color Me Badd", "track": "All 4 Love", "year": 1991},
        {"artist": "Backstreet Boys", "track": "I Want It That Way", "year": 1999},
        {"artist": "P.M. Dawn", "track": "I'd Die Without You (From \"Boomerang\")", "year": 1992},
    ),
    "2000's": (
        {"artist": "The Black Eyed Peas", "track": "I Gotta Feeling", "year": 2009},
        {"artist": "Usher", "track": "Yeah!", "year": 2004},
        {"artist": "Mariah Carey", "track": "We Belong Together", "year": 2005},
        {"artist": "Jason Mraz", "track": "I'm Yours", "year": 2008},
        {"artist": "Flo Rida", "track": "Low", "year": 2007},
        {"artist": "Nickelback", "track": "How You Remind Me", "year": 2001},
        {"artist": "Lady Antebellum", "track": "Need You Now", "year": 2009},
        {"artist": "Kanye West", "track": "Gold Digger", "year": 2005},
        {"artist": "Ke$ha", "track": "TiK ToK", "year": 2009},
        {"artist": "Lifehouse", "track": "Hanging By A Moment", "year": 2001},
        {"artist": "The Black Eyed Peas", "track": "Boom Boom Pow", "year": 2009},
        {"artist": "Alicia Keys", "track": "No One", "year": 2007},
        {"artist": "Mario", "track": "Let Me Love You", "year": 2004},
        {"artist": "Mary J. Blige", "track": "Family Affair", "year": 2001},
        {"artist": "Fergie", "track": "Big Girls Don't Cry", "year": 2007},
        {"artist": "Train", "track": "Hey, Soul Sister", "year": 2009},
        {"artist": "Coldplay", "track": "Viva La Vida", "year": 2008},
        {"artist": "matchbox twenty", "track": "Unwell", "year": 2003},
        {"artist": "Timbaland", "track": "Apologize", "year": 2007},
        {"artist": "Carrie Underwood", "track": "Before He Cheats", "year": 2006},
        {"artist": "Lady Gaga", "track": "Just Dance", "year": 2008},
        {"artist": "3 Doors Down", "track": "Kryptonite", "year": 2000},
        {"artist": "Taylor Swift", "track": "You Belong With Me", "year": 2008},
        {"artist": "3 Doors Down", "track": "Here Without You", "year": 2003},
        {"artist": "Taylor Swift", "track": "Love Story", "year": 2008},
        {"artist": "Ciara", "track": "Goodies", "year": 2004},
        {"artist": "Nelly", "track": "Dilemma", "year": 2002},
        {"artist": "Ashanti", "track": "Foolish", "year": 2002},
        {"artist": "Kelly Clarkson", "track": "Since U Been Gone", "year": 2004},
        {"artist": "Jay Sean", "track": "Down", "year": 2009},
        {"artist": "Train", "track": "Drops Of Jupiter (Tell Me)", "year": 2001},
        {"artist": "OutKast", "track": "Hey Ya!", "year": 2003},
        {"artist": "Leona Lewis", "track": "Bleeding Love", "year": 2008},
        {"artist": "The Fray", "track": "How To Save A Life", "year": 2006},
        {"artist": "Lifehouse", "track": "You And Me", "year": 2005},
        {"artist": "Destiny's Child", "track": "Independent Women Part I", "year": 2000},
        {"artist": "Beyonce", "track": "Irreplaceable", "year": 2006},
        {"artist": "Faith Hill", "track": "The Way You Love Me", "year": 2000},
        {"artist": "Soulja Boy Tell'em", "track": "Crank That (Soulja Boy)", "year": 2007},
        {"artist": "50 Cent", "track": "In Da Club", "year": 2003},
        {"artist": "OutKast", "track": "The Way You Move", "year": 2003},
        {"artist": "Usher", "track": "Burn", "year": 2004},
        {"artist": "Santana", "track": "Maria Maria", "year": 2000},
        {"artist": "Chris Brown", "track": "Run It!", "year": 2005},
        {"artist": "Kings Of Leon", "track": "Use Somebody", "year": 2008},
        {"artist": "T.I.", "track": "Whatever You Like", "year": 2008},
        {"artist": "Alicia Keys", "track": "If I Ain't Got You", "year": 2004},
        {"artist": "Beyonce", "track": "Baby Boy", "year": 2003},
        {"artist": "Eminem", "track": "Lose Yourself", "year": 2002},
        {"artist": "Joe", "track": "I Wanna Know", "year": 2000},
        {"artist": "Vertical Horizon", "track": "Everything You Want", "year": 2000},
        {"artist": "Justin Timberlake", "track": "SexyBack", "year": 2006},
        {"artist": "Jennifer Lopez", "track": "I'm Real", "year": 2001},
        {"artist": "Maroon 5", "track": "This Love", "year": 2004},
        {"artist": "Creed", "track": "With Arms Wide Open", "year": 2000},
        {"artist": "Lil Jon & The East Side Boyz", "track": "Get Low", "year": 2003},
        {"artist": "Kelly Clarkson", "track": "Breakaway", "year": 2004},
        {"artist": "Lady Gaga", "track": "Poker Face", "year": 2009},
        {"artist": "The Calling", "track": "Wherever You Will Go", "year": 2001},
        {"artist": "Colbie Caillat", "track": "Bubbly", "year": 2007},
        {"artist": "Rihanna", "track": "Disturbia", "year": 2008},
        {"artist": "Rihanna", "track": "Umbrella", "year": 2007},
        {"artist": "Nelly", "track": "Hot In Herre", "year": 2002},
        {"artist": "matchbox twenty", "track": "Bent", "year": 2000},
        {"artist": "Vanessa Carlton", "track": "A Thousand Miles", "year": 2002},
        {"artist": "Timbaland", "track": "The Way I Are", "year": 2007},
        {"artist": "Staind", "track": "It's Been Awhile", "year": 2001},
        {"artist": "T.I.", "track": "Live Your Life", "year": 2008},
        {"artist": "Ciara", "track": "1, 2 Step", "year": 2004},
        {"artist": "Jay-Z + Alicia Keys", "track": "Empire State Of Mind", "year": 2009},
        {"artist": "Usher And Alicia Keys", "track": "My Boo", "year": 2004},
        {"artist": "Daniel Powter", "track": "Bad Day", "year": 2006},
        {"artist": "Katy Perry", "track": "Hot N Cold", "year": 2008},
        {"artist": "Gwen Stefani", "track": "Hollaback Girl", "year": 2005},
        {"artist": "Lil Wayne", "track": "Lollipop", "year": 2008},
        {"artist": "R. Kelly", "track": "Ignition", "year": 2002},
        {"artist": "Sara Bareilles", "track": "Love Song", "year": 2007},
        {"artist": "Maroon 5", "track": "She Will Be Loved", "year": 2004},
        {"artist": "Natasha Bedingfield", "track": "Unwritten", "year": 2005},
        {"artist": "Gwen Stefani", "track": "The Sweet Escape", "year": 2006},
        {"artist": "Terror Squad", "track": "Lean Back", "year": 2004},
        {"artist": "Hoobastank", "track": "The Reason", "year": 2004},
        {"artist": "Nelly Furtado", "track": "Promiscuous", "year": 2006},
        {"artist": "Sean Paul", "track": "Get Busy", "year": 2003},
        {"artist": "Snoop Dogg", "track": "Drop It Like It's Hot", "year": 2004},
        {"artist": "50 Cent", "track": "Candy Shop", "year": 2005},
        {"artist": "T-Pain", "track": "Buy U A Drank (Shawty Snappin')", "year": 2007},
        {"artist": "The Pussycat Dolls", "track": "Don't Cha", "year": 2005},
        {"artist": "James Blunt", "track": "You're Beautiful", "year": 2005},
        {"artist": "Nickelback", "track": "Someday", "year": 2003},
        {"artist": "Finger Eleven", "track": "Paralyzer", "year": 2007},
        {"artist": "Snow Patrol", "track": "Chasing Cars", "year": 2006},
        {"artist": "Jennifer Lopez", "track": "Ain't It Funny", "year": 2001},
        {"artist": "Plain White T's", "track": "Hey There Delilah", "year": 2007},
        {"artist": "Jason Derulo", "track": "Whatcha Say", "year": 2009},
        {"artist": "Green Day", "track": "Boulevard Of Broken Dreams", "year": 2004},
        {"artist": "David Guetta", "track": "Sexy Chick", "year": 2009},
        {"artist": "Puddle Of Mudd", "track": "Blurry", "year": 2001},
        {"artist": "Linkin Park", "track": "In The End", "year": 2001},
        {"artist": "Aaliyah", "track": "Try Again", "year": 2000},
        {"artist": "Nelly, P. Diddy & Murphy Lee", "track": "Shake Ya Tailfeather", "year": 2003},
        {"artist": "Eve", "track": "Let Me Blow Ya Mind", "year": 2001},
        {"artist": "Flo Rida", "track": "Right Round", "year": 2009},
        {"artist": "Sean Paul", "track": "Temperature", "year": 2006},
        {"artist": "Chris Brown", "track": "Forever", "year": 2008},
        {"artist": "Weezer", "track": "Beverly Hills", "year": 2005},
        {"artist": "The All-American Rejects", "track": "Gives You Hell", "year": 2008},
        {"artist": "Jordin Sparks", "track": "No Air", "year": 2008},
        {"artist": "The Fray", "track": "Over My Head (Cable Car)", "year": 2006},
        {"artist": "Katy Perry", "track": "I Kissed A Girl", "year": 2008},
        {"artist": "P!nk", "track": "So What", "year": 2008},
        {"artist": "Dido", "track": "Thank You", "year": 2001},
        {"artist": "Santana", "track": "The Game Of Love", "year": 2002},
        {"artist": "Justin Timberlake", "track": "My Love", "year": 2006},
        {"artist": "Janet", "track": "All For You", "year": 2001},
        {"artist": "Chingy", "track": "Right Thurr", "year": 2003},
        {"artist": "Fall Out Boy", "track": "Sugar, We're Goin' Down", "year": 2005},
        {"artist": "Avril Lavigne", "track": "Complicated", "year": 2002},
        {"artist": "Enrique Iglesias", "track": "Hero", "year": 2001},
        {"artist": "Joe", "track": "Stutter", "year": 2001},
    ),
    "2010's": (
        {"artist": "The Weeknd", "track": "Blinding Lights", "year": 2019},
        {"artist": "Dua Lipa", "track": "Levitating", "year": 2020},
        {"artist": "Ed Sheeran", "track": "Shape Of You", "year": 2017},
        {"artist": "Mark Ronson", "track": "Uptown Funk!", "year": 2014},
        {"artist": "Post Malone", "track": "Circles", "year": 2019},
        {"artist": "The Chainsmokers", "track": "Closer", "year": 2016},
        {"artist": "Lil Nas X", "track": "Old Town Road", "year": 2019},
        {"artist": "LMFAO", "track": "Party Rock Anthem", "year": 2011},
        {"artist": "The Weeknd & Ariana Grande", "track": "Save Your Tears", "year": 2020},
        {"artist": "Luis Fonsi & Daddy Yankee", "track": "Despacito", "year": 2017},
        {"artist": "Maroon 5", "track": "Girls Like You", "year": 2018},
        {"artist": "Imagine Dragons", "track": "Radioactive", "year": 2012},
        {"artist": "24kGoldn", "track": "Mood", "year": 2020},
        {"artist": "Adele", "track": "Rolling In The Deep", "year": 2010},
        {"artist": "Gotye", "track": "Somebody That I Used To Know", "year": 2012},
        {"artist": "Ed Sheeran", "track": "Perfect", "year": 2017},
        {"artist": "Post Malone & Swae Lee", "track": "Sunflower (Spider-Man: Into The Spider-Verse)", "year": 2018},
        {"artist": "Wiz Khalifa", "track": "See You Again", "year": 2015},
        {"artist": "Carly Rae Jepsen", "track": "Call Me Maybe", "year": 2012},
        {"artist": "Robin Thicke", "track": "Blurred Lines", "year": 2013},
        {"artist": "OneRepublic", "track": "Counting Stars", "year": 2013},
        {"artist": "Halsey", "track": "Without Me", "year": 2018},
        {"artist": "Pharrell Williams", "track": "Happy", "year": 2014},
        {"artist": "Katy Perry", "track": "Dark Horse", "year": 2013},
        {"artist": "Lewis Capaldi", "track": "Someone You Loved", "year": 2019},
        {"artist": "Meghan Trainor", "track": "All About That Bass", "year": 2014},
        {"artist": "Travis Scott", "track": "Sicko Mode", "year": 2018},
        {"artist": "The Weeknd", "track": "The Hills", "year": 2015},
        {"artist": "Rihanna", "track": "We Found Love", "year": 2011},
        {"artist": "Billie Eilish", "track": "Bad Guy", "year": 2019},
        {"artist": "Roddy Ricch", "track": "The Box", "year": 2019},
        {"artist": "Lorde", "track": "Royals", "year": 2013},
        {"artist": "Drake", "track": "God's Plan", "year": 2018},
        {"artist": "John Legend", "track": "All Of Me", "year": 2013},
        {"artist": "Marshmello & Bastille", "track": "Happier", "year": 2018},
        {"artist": "Taylor Swift", "track": "Shake It Off", "year": 2014},
        {"artist": "DaBaby", "track": "Rockstar", "year": 2020},
        {"artist": "Post Malone", "track": "Rockstar", "year": 2017},
        {"artist": "Bruno Mars", "track": "That's What I Like", "year": 2016},
        {"artist": "Gabby Barrett", "track": "I Hope", "year": 2020},
        {"artist": "Macklemore & Ryan Lewis", "track": "Thrift Shop", "year": 2012},
        {"artist": "Fetty Wap", "track": "Trap Queen", "year": 2015},
        {"artist": "Bruno Mars", "track": "Just The Way You Are", "year": 2010},
        {"artist": "Lizzo", "track": "Truth Hurts", "year": 2019},
        {"artist": "Maroon 5", "track": "Moves Like Jagger", "year": 2011},
        {"artist": "Drake", "track": "One Dance", "year": 2016},
        {"artist": "Cardi B, Bad Bunny & J Balvin", "track": "I Like It", "year": 2018},
        {"artist": "Juice WRLD", "track": "Lucid Dreams", "year": 2018},
        {"artist": "The Chainsmokers", "track": "Don't Let Me Down", "year": 2016},
        {"artist": "Avicii", "track": "Wake Me Up!", "year": 2013},
        {"artist": "Sam Smith", "track": "Stay With Me", "year": 2014},
        {"artist": "Sia", "track": "Cheap Thrills", "year": 2016},
        {"artist": "Dua Lipa", "track": "Don't Start Now", "year": 2019},
        {"artist": "Justin Timberlake", "track": "Can't Stop The Feeling!", "year": 2016},
        {"artist": "Jonas Brothers", "track": "Sucker", "year": 2019},
        {"artist": "Bebe Rexha & Florida Georgia Line", "track": "Meant To Be", "year": 2017},
        {"artist": "fun.", "track": "We Are Young", "year": 2011},
        {"artist": "The Lumineers", "track": "Ho Hey", "year": 2012},
        {"artist": "Rihanna", "track": "Work", "year": 2016},
        {"artist": "Chris Brown", "track": "No Guidance", "year": 2019},
        {"artist": "Justin Bieber", "track": "Love Yourself", "year": 2015},
        {"artist": "Chris Brown & Young Thug", "track": "Go Crazy", "year": 2020},
        {"artist": "Justin Bieber", "track": "Sorry", "year": 2015},
        {"artist": "fun.", "track": "Some Nights", "year": 2012},
        {"artist": "Shawn Mendes", "track": "Stitches", "year": 2015},
        {"artist": "Silento", "track": "Watch Me", "year": 2015},
        {"artist": "MAGIC!", "track": "Rude", "year": 2014},
        {"artist": "Taylor Swift", "track": "Blank Space", "year": 2014},
        {"artist": "Pitbull", "track": "Give Me Everything", "year": 2011},
        {"artist": "Taio Cruz", "track": "Dynamite", "year": 2010},
        {"artist": "Florida Georgia Line", "track": "Cruise", "year": 2012},
        {"artist": "Camila Cabello", "track": "Havana", "year": 2017},
        {"artist": "LMFAO", "track": "Sexy And I Know It", "year": 2011},
        {"artist": "Panic! At The Disco", "track": "High Hopes", "year": 2018},
        {"artist": "Iggy Azalea", "track": "Fancy", "year": 2014},
        {"artist": "Adele", "track": "Someone Like You", "year": 2011},
        {"artist": "Imagine Dragons", "track": "Believer", "year": 2017},
        {"artist": "Ariana Grande", "track": "7 Rings", "year": 2019},
        {"artist": "Khalid", "track": "Talk", "year": 2019},
        {"artist": "Katy Perry", "track": "Firework", "year": 2010},
        {"artist": "Shawn Mendes & Camila Cabello", "track": "Senorita", "year": 2019},
        {"artist": "Harry Styles", "track": "Adore You", "year": 2019},
        {"artist": "WALK THE MOON", "track": "Shut Up And Dance", "year": 2014},
        {"artist": "CeeLo Green", "track": "F**k You! (Forget You)", "year": 2010},
        {"artist": "Macklemore & Ryan Lewis", "track": "Can't Hold Us", "year": 2013},
        {"artist": "twenty one pilots", "track": "Stressed Out", "year": 2015},
        {"artist": "Pitbull", "track": "Timber", "year": 2013},
        {"artist": "Ellie Goulding", "track": "Lights", "year": 2011},
        {"artist": "OMI", "track": "Cheerleader", "year": 2015},
        {"artist": "Bastille", "track": "Pompeii", "year": 2013},
        {"artist": "benny blanco, Halsey & Khalid", "track": "Eastside", "year": 2018},
        {"artist": "Jack Harlow", "track": "Whats Poppin", "year": 2020},
        {"artist": "twenty one pilots", "track": "Heathens", "year": 2016},
        {"artist": "Desiigner", "track": "Panda", "year": 2016},
        {"artist": "Cardi B", "track": "Bodak Yellow (Money Moves)", "year": 2017},
        {"artist": "Eminem", "track": "Love The Way You Lie", "year": 2010},
        {"artist": "Major Lazer & DJ Snake", "track": "Lean On", "year": 2015},
        {"artist": "Ariana Grande", "track": "Thank U, Next", "year": 2018},
        {"artist": "Zedd, Maren Morris & Grey", "track": "The Middle", "year": 2018},
        {"artist": "Fetty Wap", "track": "679", "year": 2015},
        {"artist": "Kelly Clarkson", "track": "Stronger (What Doesn't Kill You)", "year": 2011},
        {"artist": "Justin Timberlake", "track": "Mirrors", "year": 2013},
        {"artist": "Ed Sheeran & Justin Bieber", "track": "I Don't Care", "year": 2019},
        {"artist": "The Chainsmokers & Coldplay", "track": "Something Just Like This", "year": 2017},
        {"artist": "Future", "track": "Life Is Good", "year": 2020},
        {"artist": "Sam Smith & Normani", "track": "Dancing With A Stranger", "year": 2019},
        {"artist": "Hozier", "track": "Take Me To Church", "year": 2014},
        {"artist": "French Montana", "track": "Unforgettable", "year": 2017},
        {"artist": "5 Seconds Of Summer", "track": "Youngblood", "year": 2018},
        {"artist": "P!nk", "track": "Just Give Me A Reason", "year": 2013},
        {"artist": "Migos", "track": "Bad And Boujee", "year": 2016},
        {"artist": "Nicki Minaj", "track": "Super Bass", "year": 2011},
        {"artist": "Usher", "track": "OMG", "year": 2010},
        {"artist": "Lady Gaga & Bradley Cooper", "track": "Shallow", "year": 2018},
        {"artist": "Kendrick Lamar", "track": "Humble.", "year": 2017},
        {"artist": "Sia", "track": "Chandelier", "year": 2014},
        {"artist": "Miley Cyrus", "track": "Wrecking Ball", "year": 2013},
        {"artist": "Passenger", "track": "Let Her Go", "year": 2013},
        {"artist": "Sam Hunt", "track": "Body Like A Back Road", "year": 2017},
        {"artist": "Khalid & Normani", "track": "Love Lies", "year": 2018},
    ),
}
