"""רשימות קלאסיקות סטטיות — פופ, רוק ובלוז, 1950–2020.

מחליפות את מצעד ה-Deezer החי באינדקס המצעדים: מצעד "חי" מציג טרנדים
עדכניים שהמשתמש לרוב לא מזהה, בעוד שהמטרה כאן היא נקודת פתיחה של שירים
מוכרים לחיפוש קאברים. הרשימות מוכנות מראש בקוד — באותה שיטה כמו
`artists.GREATEST_ARTISTS` — ולא נשלפות מ-API חי, כדי שיהיו יציבות,
מוכרות וזמינות בלי תלות ברשת.

כל רשומה: {"artist": ..., "track": ..., "year": ...}. השנה היא הערכה
(שנת יציאה/שיא הצלחה) ומיועדת להצגה בלבד, לא לדיוק ארכיוני.
"""

POP_CLASSICS: tuple[dict, ...] = (
    # 1950s
    {"artist": "Patti Page", "track": "Tennessee Waltz", "year": 1950},
    {"artist": "Nat King Cole", "track": "Unforgettable", "year": 1951},
    {"artist": "Frank Sinatra", "track": "Love and Marriage", "year": 1955},
    {"artist": "The Platters", "track": "Only You (And You Alone)", "year": 1955},
    {"artist": "The Platters", "track": "The Great Pretender", "year": 1955},
    {"artist": "The Platters", "track": "Smoke Gets in Your Eyes", "year": 1958},
    {"artist": "Doris Day", "track": "Que Sera, Sera (Whatever Will Be, Will Be)", "year": 1956},
    {"artist": "Perry Como", "track": "Magic Moments", "year": 1957},
    {"artist": "Pat Boone", "track": "Love Letters in the Sand", "year": 1957},
    {"artist": "The Everly Brothers", "track": "All I Have to Do Is Dream", "year": 1958},
    {"artist": "Connie Francis", "track": "Who's Sorry Now", "year": 1958},
    {"artist": "Bobby Darin", "track": "Mack the Knife", "year": 1959},
    # 1960s
    {"artist": "Elvis Presley", "track": "Can't Help Falling in Love", "year": 1961},
    {"artist": "The Shirelles", "track": "Will You Love Me Tomorrow", "year": 1960},
    {"artist": "Roy Orbison", "track": "Only the Lonely", "year": 1960},
    {"artist": "Ray Charles", "track": "Georgia on My Mind", "year": 1960},
    {"artist": "The Beach Boys", "track": "Surfin' USA", "year": 1963},
    {"artist": "The Supremes", "track": "Where Did Our Love Go", "year": 1964},
    {"artist": "The Supremes", "track": "Baby Love", "year": 1964},
    {"artist": "The Supremes", "track": "Stop! In the Name of Love", "year": 1965},
    {"artist": "Dionne Warwick", "track": "Walk On By", "year": 1964},
    {"artist": "Petula Clark", "track": "Downtown", "year": 1964},
    {"artist": "The Mamas & the Papas", "track": "California Dreamin'", "year": 1965},
    {"artist": "The Righteous Brothers", "track": "You've Lost That Lovin' Feelin'", "year": 1964},
    {"artist": "Frank Sinatra", "track": "Strangers in the Night", "year": 1966},
    {"artist": "The Turtles", "track": "Happy Together", "year": 1967},
    {"artist": "Aretha Franklin", "track": "Respect", "year": 1967},
    {"artist": "Otis Redding", "track": "(Sittin' On) The Dock of the Bay", "year": 1968},
    {"artist": "Marvin Gaye", "track": "I Heard It Through the Grapevine", "year": 1968},
    {"artist": "The 5th Dimension", "track": "Aquarius / Let the Sunshine In", "year": 1969},
    {"artist": "Simon & Garfunkel", "track": "The Sound of Silence", "year": 1965},
    {"artist": "Simon & Garfunkel", "track": "Mrs. Robinson", "year": 1968},
    {"artist": "Dusty Springfield", "track": "Son of a Preacher Man", "year": 1968},
    {"artist": "Nancy Sinatra", "track": "These Boots Are Made for Walkin'", "year": 1966},
    {"artist": "The Beatles", "track": "Yesterday", "year": 1965},
    {"artist": "The Beatles", "track": "Hey Jude", "year": 1968},
    {"artist": "The Beatles", "track": "Let It Be", "year": 1970},
    {"artist": "Neil Diamond", "track": "Sweet Caroline", "year": 1969},
    {"artist": "The Monkees", "track": "I'm a Believer", "year": 1966},
    {"artist": "Sam Cooke", "track": "A Change Is Gonna Come", "year": 1964},
    {"artist": "Stevie Wonder", "track": "My Cherie Amour", "year": 1969},
    {"artist": "The Association", "track": "Cherish", "year": 1966},
    # 1970s
    {"artist": "Carole King", "track": "It's Too Late", "year": 1971},
    {"artist": "Carly Simon", "track": "You're So Vain", "year": 1972},
    {"artist": "Roberta Flack", "track": "Killing Me Softly with His Song", "year": 1973},
    {"artist": "The Carpenters", "track": "(They Long to Be) Close to You", "year": 1970},
    {"artist": "The Carpenters", "track": "Rainy Days and Mondays", "year": 1971},
    {"artist": "Elton John", "track": "Your Song", "year": 1970},
    {"artist": "Elton John", "track": "Rocket Man", "year": 1972},
    {"artist": "Elton John", "track": "Goodbye Yellow Brick Road", "year": 1973},
    {"artist": "Stevie Wonder", "track": "Superstition", "year": 1972},
    {"artist": "Stevie Wonder", "track": "Isn't She Lovely", "year": 1976},
    {"artist": "Marvin Gaye", "track": "Let's Get It On", "year": 1973},
    {"artist": "Al Green", "track": "Let's Stay Together", "year": 1972},
    {"artist": "Gladys Knight & the Pips", "track": "Midnight Train to Georgia", "year": 1973},
    {"artist": "ABBA", "track": "Dancing Queen", "year": 1976},
    {"artist": "ABBA", "track": "Mamma Mia", "year": 1975},
    {"artist": "Bee Gees", "track": "Stayin' Alive", "year": 1977},
    {"artist": "Bee Gees", "track": "How Deep Is Your Love", "year": 1977},
    {"artist": "Donna Summer", "track": "Hot Stuff", "year": 1979},
    {"artist": "Donna Summer", "track": "I Feel Love", "year": 1977},
    {"artist": "Chic", "track": "Le Freak", "year": 1978},
    {"artist": "Gloria Gaynor", "track": "I Will Survive", "year": 1978},
    {"artist": "Billy Joel", "track": "Piano Man", "year": 1973},
    {"artist": "Billy Joel", "track": "Just the Way You Are", "year": 1977},
    {"artist": "Barry Manilow", "track": "Mandy", "year": 1974},
    {"artist": "Fleetwood Mac", "track": "Dreams", "year": 1977},
    {"artist": "Barbra Streisand", "track": "The Way We Were", "year": 1973},
    {"artist": "John Denver", "track": "Take Me Home, Country Roads", "year": 1971},
    {"artist": "Boz Scaggs", "track": "Lowdown", "year": 1976},
    {"artist": "Player", "track": "Baby Come Back", "year": 1977},
    {"artist": "Rod Stewart", "track": "Da Ya Think I'm Sexy?", "year": 1978},
    # 1980s
    {"artist": "Michael Jackson", "track": "Billie Jean", "year": 1983},
    {"artist": "Michael Jackson", "track": "Thriller", "year": 1982},
    {"artist": "Michael Jackson", "track": "Beat It", "year": 1983},
    {"artist": "Michael Jackson", "track": "Bad", "year": 1987},
    {"artist": "Madonna", "track": "Like a Virgin", "year": 1984},
    {"artist": "Madonna", "track": "Material Girl", "year": 1985},
    {"artist": "Whitney Houston", "track": "I Wanna Dance with Somebody", "year": 1987},
    {"artist": "Whitney Houston", "track": "Greatest Love of All", "year": 1985},
    {"artist": "Prince", "track": "When Doves Cry", "year": 1984},
    {"artist": "Prince", "track": "Purple Rain", "year": 1984},
    {"artist": "Cyndi Lauper", "track": "Girls Just Want to Have Fun", "year": 1983},
    {"artist": "Cyndi Lauper", "track": "Time After Time", "year": 1984},
    {"artist": "Tears for Fears", "track": "Everybody Wants to Rule the World", "year": 1985},
    {"artist": "Duran Duran", "track": "Hungry Like the Wolf", "year": 1982},
    {"artist": "Culture Club", "track": "Karma Chameleon", "year": 1983},
    {"artist": "Wham!", "track": "Wake Me Up Before You Go-Go", "year": 1984},
    {"artist": "George Michael", "track": "Careless Whisper", "year": 1984},
    {"artist": "George Michael", "track": "Faith", "year": 1987},
    {"artist": "Lionel Richie", "track": "All Night Long (All Night)", "year": 1983},
    {"artist": "Lionel Richie", "track": "Hello", "year": 1984},
    {"artist": "Phil Collins", "track": "Against All Odds (Take a Look at Me Now)", "year": 1984},
    {"artist": "Phil Collins", "track": "In the Air Tonight", "year": 1981},
    {"artist": "Hall & Oates", "track": "Maneater", "year": 1982},
    {"artist": "The Human League", "track": "Don't You Want Me", "year": 1981},
    {"artist": "a-ha", "track": "Take On Me", "year": 1985},
    {"artist": "Whitney Houston", "track": "How Will I Know", "year": 1985},
    {"artist": "Simple Minds", "track": "Don't You (Forget About Me)", "year": 1985},
    {"artist": "Kenny Loggins", "track": "Footloose", "year": 1984},
    {"artist": "Kool & the Gang", "track": "Celebration", "year": 1980},
    {"artist": "Stevie Wonder", "track": "I Just Called to Say I Love You", "year": 1984},
    {"artist": "Bonnie Tyler", "track": "Total Eclipse of the Heart", "year": 1983},
    {"artist": "Irene Cara", "track": "Flashdance... What a Feeling", "year": 1983},
    {"artist": "Diana Ross & Lionel Richie", "track": "Endless Love", "year": 1981},
    {"artist": "Toto", "track": "Africa", "year": 1982},
    # 1990s
    {"artist": "Whitney Houston", "track": "I Will Always Love You", "year": 1992},
    {"artist": "Mariah Carey", "track": "Vision of Love", "year": 1990},
    {"artist": "Mariah Carey", "track": "Fantasy", "year": 1995},
    {"artist": "Mariah Carey", "track": "Hero", "year": 1993},
    {"artist": "Celine Dion", "track": "My Heart Will Go On", "year": 1997},
    {"artist": "Celine Dion", "track": "Because You Loved Me", "year": 1996},
    {"artist": "Madonna", "track": "Vogue", "year": 1990},
    {"artist": "Madonna", "track": "Frozen", "year": 1998},
    {"artist": "Whitney Houston", "track": "I'm Every Woman", "year": 1993},
    {"artist": "TLC", "track": "Waterfalls", "year": 1995},
    {"artist": "TLC", "track": "No Scrubs", "year": 1999},
    {"artist": "Spice Girls", "track": "Wannabe", "year": 1996},
    {"artist": "Backstreet Boys", "track": "I Want It That Way", "year": 1999},
    {"artist": "Britney Spears", "track": "...Baby One More Time", "year": 1998},
    {"artist": "Christina Aguilera", "track": "Genie in a Bottle", "year": 1999},
    {"artist": "Boyz II Men", "track": "End of the Road", "year": 1992},
    {"artist": "Boyz II Men", "track": "I'll Make Love to You", "year": 1994},
    {"artist": "Toni Braxton", "track": "Un-Break My Heart", "year": 1996},
    {"artist": "Alanis Morissette", "track": "Ironic", "year": 1996},
    {"artist": "Sheryl Crow", "track": "All I Wanna Do", "year": 1994},
    {"artist": "Shania Twain", "track": "Man! I Feel Like a Woman!", "year": 1997},
    {"artist": "Savage Garden", "track": "Truly Madly Deeply", "year": 1997},
    {"artist": "Robyn", "track": "Show Me Love", "year": 1997},
    {"artist": "En Vogue", "track": "My Lovin' (You're Never Gonna Get It)", "year": 1992},
    {"artist": "Ace of Base", "track": "The Sign", "year": 1993},
    {"artist": "Des'ree", "track": "You Gotta Be", "year": 1994},
    {"artist": "Vanessa Williams", "track": "Save the Best for Last", "year": 1992},
    {"artist": "Lauryn Hill", "track": "Doo Wop (That Thing)", "year": 1998},
    {"artist": "Cher", "track": "Believe", "year": 1998},
    {"artist": "Destiny's Child", "track": "Say My Name", "year": 2000},
    # 2000s
    {"artist": "Beyoncé", "track": "Crazy in Love", "year": 2003},
    {"artist": "Beyoncé", "track": "Single Ladies (Put a Ring on It)", "year": 2008},
    {"artist": "Beyoncé", "track": "Halo", "year": 2008},
    {"artist": "Rihanna", "track": "Umbrella", "year": 2007},
    {"artist": "Justin Timberlake", "track": "Cry Me a River", "year": 2002},
    {"artist": "Justin Timberlake", "track": "SexyBack", "year": 2006},
    {"artist": "Kelly Clarkson", "track": "Since U Been Gone", "year": 2004},
    {"artist": "Christina Aguilera", "track": "Beautiful", "year": 2002},
    {"artist": "Usher", "track": "Yeah!", "year": 2004},
    {"artist": "Alicia Keys", "track": "Fallin'", "year": 2001},
    {"artist": "Alicia Keys", "track": "No One", "year": 2007},
    {"artist": "Amy Winehouse", "track": "Rehab", "year": 2006},
    {"artist": "Amy Winehouse", "track": "Back to Black", "year": 2006},
    {"artist": "Adele", "track": "Chasing Pavements", "year": 2008},
    {"artist": "Katy Perry", "track": "I Kissed a Girl", "year": 2008},
    {"artist": "Lady Gaga", "track": "Just Dance", "year": 2008},
    {"artist": "Lady Gaga", "track": "Poker Face", "year": 2008},
    {"artist": "Black Eyed Peas", "track": "I Gotta Feeling", "year": 2009},
    {"artist": "Black Eyed Peas", "track": "Boom Boom Pow", "year": 2009},
    {"artist": "Fergie", "track": "Glamorous", "year": 2007},
    {"artist": "Gwen Stefani", "track": "Hollaback Girl", "year": 2005},
    {"artist": "Nelly Furtado", "track": "Say It Right", "year": 2006},
    {"artist": "Colbie Caillat", "track": "Bubbly", "year": 2007},
    {"artist": "Leona Lewis", "track": "Bleeding Love", "year": 2007},
    {"artist": "OutKast", "track": "Hey Ya!", "year": 2003},
    {"artist": "Norah Jones", "track": "Don't Know Why", "year": 2002},
    {"artist": "John Mayer", "track": "Your Body Is a Wonderland", "year": 2001},
    {"artist": "Maroon 5", "track": "This Love", "year": 2004},
    # 2010s
    {"artist": "Adele", "track": "Rolling in the Deep", "year": 2011},
    {"artist": "Adele", "track": "Someone Like You", "year": 2011},
    {"artist": "Adele", "track": "Hello", "year": 2015},
    {"artist": "Bruno Mars", "track": "Just the Way You Are", "year": 2010},
    {"artist": "Bruno Mars", "track": "Uptown Funk", "year": 2014},
    {"artist": "Katy Perry", "track": "Firework", "year": 2010},
    {"artist": "Katy Perry", "track": "Roar", "year": 2013},
    {"artist": "Lady Gaga", "track": "Bad Romance", "year": 2010},
    {"artist": "Rihanna", "track": "We Found Love", "year": 2011},
    {"artist": "Rihanna", "track": "Diamonds", "year": 2012},
    {"artist": "Taylor Swift", "track": "Shake It Off", "year": 2014},
    {"artist": "Taylor Swift", "track": "Blank Space", "year": 2014},
    {"artist": "Ed Sheeran", "track": "Thinking Out Loud", "year": 2014},
    {"artist": "Ed Sheeran", "track": "Shape of You", "year": 2017},
    {"artist": "Sam Smith", "track": "Stay with Me", "year": 2014},
    {"artist": "Sia", "track": "Chandelier", "year": 2014},
    {"artist": "Meghan Trainor", "track": "All About That Bass", "year": 2014},
    {"artist": "Pharrell Williams", "track": "Happy", "year": 2013},
    {"artist": "Justin Timberlake", "track": "Can't Stop the Feeling!", "year": 2016},
    {"artist": "Ariana Grande", "track": "Thank U, Next", "year": 2018},
    {"artist": "Ariana Grande", "track": "7 rings", "year": 2019},
    {"artist": "Dua Lipa", "track": "New Rules", "year": 2017},
    {"artist": "Billie Eilish", "track": "Bad Guy", "year": 2019},
    {"artist": "Camila Cabello", "track": "Havana", "year": 2017},
    {"artist": "Shawn Mendes", "track": "Stitches", "year": 2015},
    {"artist": "The Weeknd", "track": "Can't Feel My Face", "year": 2015},
    {"artist": "The Weeknd", "track": "Blinding Lights", "year": 2019},
    {"artist": "Post Malone", "track": "Circles", "year": 2019},
    {"artist": "Lizzo", "track": "Truth Hurts", "year": 2019},
    # 2020
    {"artist": "Dua Lipa", "track": "Don't Start Now", "year": 2020},
    {"artist": "Harry Styles", "track": "Watermelon Sugar", "year": 2020},
    {"artist": "Doja Cat", "track": "Say So", "year": 2020},
    {"artist": "Ariana Grande", "track": "Positions", "year": 2020},
    {"artist": "Billie Eilish", "track": "Therefore I Am", "year": 2020},
)

ROCK_CLASSICS: tuple[dict, ...] = (
    # 1950s
    {"artist": "Bill Haley & His Comets", "track": "Rock Around the Clock", "year": 1954},
    {"artist": "Chuck Berry", "track": "Maybellene", "year": 1955},
    {"artist": "Chuck Berry", "track": "Johnny B. Goode", "year": 1958},
    {"artist": "Elvis Presley", "track": "Hound Dog", "year": 1956},
    {"artist": "Elvis Presley", "track": "Jailhouse Rock", "year": 1957},
    {"artist": "Little Richard", "track": "Tutti Frutti", "year": 1955},
    {"artist": "Little Richard", "track": "Long Tall Sally", "year": 1956},
    {"artist": "Buddy Holly", "track": "That'll Be the Day", "year": 1957},
    {"artist": "Buddy Holly", "track": "Peggy Sue", "year": 1957},
    {"artist": "Jerry Lee Lewis", "track": "Great Balls of Fire", "year": 1957},
    {"artist": "Eddie Cochran", "track": "Summertime Blues", "year": 1958},
    {"artist": "The Everly Brothers", "track": "Bye Bye Love", "year": 1957},
    # 1960s
    {"artist": "The Beatles", "track": "I Want to Hold Your Hand", "year": 1963},
    {"artist": "The Beatles", "track": "Twist and Shout", "year": 1963},
    {"artist": "The Beatles", "track": "Come Together", "year": 1969},
    {"artist": "The Beatles", "track": "Helter Skelter", "year": 1968},
    {"artist": "The Rolling Stones", "track": "(I Can't Get No) Satisfaction", "year": 1965},
    {"artist": "The Rolling Stones", "track": "Paint It Black", "year": 1966},
    {"artist": "The Rolling Stones", "track": "Jumpin' Jack Flash", "year": 1968},
    {"artist": "The Rolling Stones", "track": "Sympathy for the Devil", "year": 1968},
    {"artist": "The Who", "track": "My Generation", "year": 1965},
    {"artist": "The Kinks", "track": "You Really Got Me", "year": 1964},
    {"artist": "The Animals", "track": "House of the Rising Sun", "year": 1964},
    {"artist": "The Beach Boys", "track": "Good Vibrations", "year": 1966},
    {"artist": "Jimi Hendrix", "track": "Purple Haze", "year": 1967},
    {"artist": "Jimi Hendrix", "track": "All Along the Watchtower", "year": 1968},
    {"artist": "Cream", "track": "Sunshine of Your Love", "year": 1968},
    {"artist": "Led Zeppelin", "track": "Whole Lotta Love", "year": 1969},
    {"artist": "Led Zeppelin", "track": "Communication Breakdown", "year": 1969},
    {"artist": "Steppenwolf", "track": "Born to Be Wild", "year": 1968},
    {"artist": "Creedence Clearwater Revival", "track": "Bad Moon Rising", "year": 1969},
    {"artist": "Creedence Clearwater Revival", "track": "Proud Mary", "year": 1969},
    {"artist": "The Doors", "track": "Light My Fire", "year": 1967},
    {"artist": "The Doors", "track": "Break On Through (To the Other Side)", "year": 1967},
    {"artist": "Deep Purple", "track": "Hush", "year": 1968},
    {"artist": "Van Morrison", "track": "Brown Eyed Girl", "year": 1967},
    {"artist": "The Byrds", "track": "Mr. Tambourine Man", "year": 1965},
    {"artist": "Bob Dylan", "track": "Like a Rolling Stone", "year": 1965},
    {"artist": "Big Brother and the Holding Company", "track": "Piece of My Heart", "year": 1968},
    {"artist": "Fleetwood Mac", "track": "Albatross", "year": 1968},
    {"artist": "The Yardbirds", "track": "For Your Love", "year": 1965},
    # 1970s
    {"artist": "Led Zeppelin", "track": "Stairway to Heaven", "year": 1971},
    {"artist": "Led Zeppelin", "track": "Black Dog", "year": 1971},
    {"artist": "Led Zeppelin", "track": "Kashmir", "year": 1975},
    {"artist": "Deep Purple", "track": "Smoke on the Water", "year": 1972},
    {"artist": "Black Sabbath", "track": "Paranoid", "year": 1970},
    {"artist": "Black Sabbath", "track": "Iron Man", "year": 1970},
    {"artist": "Queen", "track": "Bohemian Rhapsody", "year": 1975},
    {"artist": "Queen", "track": "We Will Rock You", "year": 1977},
    {"artist": "Queen", "track": "We Are the Champions", "year": 1977},
    {"artist": "Pink Floyd", "track": "Another Brick in the Wall", "year": 1979},
    {"artist": "Pink Floyd", "track": "Money", "year": 1973},
    {"artist": "Pink Floyd", "track": "Wish You Were Here", "year": 1975},
    {"artist": "Eagles", "track": "Hotel California", "year": 1976},
    {"artist": "Eagles", "track": "Take It Easy", "year": 1972},
    {"artist": "Fleetwood Mac", "track": "Go Your Own Way", "year": 1977},
    {"artist": "Fleetwood Mac", "track": "The Chain", "year": 1977},
    {"artist": "Aerosmith", "track": "Dream On", "year": 1973},
    {"artist": "Aerosmith", "track": "Sweet Emotion", "year": 1975},
    {"artist": "Boston", "track": "More Than a Feeling", "year": 1976},
    {"artist": "Journey", "track": "Wheel in the Sky", "year": 1978},
    {"artist": "Kansas", "track": "Carry On Wayward Son", "year": 1976},
    {"artist": "Lynyrd Skynyrd", "track": "Sweet Home Alabama", "year": 1974},
    {"artist": "Lynyrd Skynyrd", "track": "Free Bird", "year": 1973},
    {"artist": "The Who", "track": "Baba O'Riley", "year": 1971},
    {"artist": "The Who", "track": "Won't Get Fooled Again", "year": 1971},
    {"artist": "David Bowie", "track": "Ziggy Stardust", "year": 1972},
    {"artist": "David Bowie", "track": "Heroes", "year": 1977},
    {"artist": "Elton John", "track": "Saturday Night's Alright for Fighting", "year": 1973},
    {"artist": "Bruce Springsteen", "track": "Born to Run", "year": 1975},
    {"artist": "Rod Stewart", "track": "Maggie May", "year": 1971},
    {"artist": "Bob Seger", "track": "Night Moves", "year": 1976},
    {"artist": "Thin Lizzy", "track": "The Boys Are Back in Town", "year": 1976},
    {"artist": "AC/DC", "track": "T.N.T.", "year": 1975},
    {"artist": "AC/DC", "track": "Highway to Hell", "year": 1979},
    # 1980s
    {"artist": "AC/DC", "track": "Back in Black", "year": 1980},
    {"artist": "AC/DC", "track": "You Shook Me All Night Long", "year": 1980},
    {"artist": "Journey", "track": "Don't Stop Believin'", "year": 1981},
    {"artist": "Def Leppard", "track": "Pour Some Sugar on Me", "year": 1987},
    {"artist": "Def Leppard", "track": "Photograph", "year": 1983},
    {"artist": "Guns N' Roses", "track": "Sweet Child o' Mine", "year": 1987},
    {"artist": "Guns N' Roses", "track": "Welcome to the Jungle", "year": 1987},
    {"artist": "Bon Jovi", "track": "Livin' on a Prayer", "year": 1986},
    {"artist": "Bon Jovi", "track": "Wanted Dead or Alive", "year": 1986},
    {"artist": "Van Halen", "track": "Jump", "year": 1984},
    {"artist": "Van Halen", "track": "Panama", "year": 1984},
    {"artist": "U2", "track": "Sunday Bloody Sunday", "year": 1983},
    {"artist": "U2", "track": "With or Without You", "year": 1987},
    {"artist": "U2", "track": "I Still Haven't Found What I'm Looking For", "year": 1987},
    {"artist": "The Police", "track": "Every Breath You Take", "year": 1983},
    {"artist": "Dire Straits", "track": "Money for Nothing", "year": 1985},
    {"artist": "Queen", "track": "Another One Bites the Dust", "year": 1980},
    {"artist": "Queen", "track": "Radio Ga Ga", "year": 1984},
    {"artist": "Survivor", "track": "Eye of the Tiger", "year": 1982},
    {"artist": "Twisted Sister", "track": "We're Not Gonna Take It", "year": 1984},
    {"artist": "Scorpions", "track": "Rock You Like a Hurricane", "year": 1984},
    {"artist": "Iron Maiden", "track": "The Number of the Beast", "year": 1982},
    {"artist": "Judas Priest", "track": "Breaking the Law", "year": 1980},
    {"artist": "Metallica", "track": "Master of Puppets", "year": 1986},
    {"artist": "Metallica", "track": "One", "year": 1988},
    {"artist": "Poison", "track": "Every Rose Has Its Thorn", "year": 1988},
    {"artist": "Whitesnake", "track": "Here I Go Again", "year": 1987},
    {"artist": "ZZ Top", "track": "Sharp Dressed Man", "year": 1983},
    {"artist": "ZZ Top", "track": "Legs", "year": 1983},
    {"artist": "Talking Heads", "track": "Once in a Lifetime", "year": 1980},
    {"artist": "The Cars", "track": "Drive", "year": 1984},
    {"artist": "INXS", "track": "Need You Tonight", "year": 1987},
    {"artist": "R.E.M.", "track": "The One I Love", "year": 1987},
    {"artist": "Bryan Adams", "track": "Summer of '69", "year": 1985},
    # 1990s
    {"artist": "Nirvana", "track": "Smells Like Teen Spirit", "year": 1991},
    {"artist": "Nirvana", "track": "Come as You Are", "year": 1991},
    {"artist": "Pearl Jam", "track": "Alive", "year": 1991},
    {"artist": "Pearl Jam", "track": "Jeremy", "year": 1992},
    {"artist": "Soundgarden", "track": "Black Hole Sun", "year": 1994},
    {"artist": "Alice in Chains", "track": "Man in the Box", "year": 1990},
    {"artist": "Stone Temple Pilots", "track": "Plush", "year": 1993},
    {"artist": "Red Hot Chili Peppers", "track": "Under the Bridge", "year": 1991},
    {"artist": "Red Hot Chili Peppers", "track": "Give It Away", "year": 1991},
    {"artist": "Guns N' Roses", "track": "November Rain", "year": 1991},
    {"artist": "Metallica", "track": "Enter Sandman", "year": 1991},
    {"artist": "Metallica", "track": "Nothing Else Matters", "year": 1991},
    {"artist": "Green Day", "track": "Basket Case", "year": 1994},
    {"artist": "Green Day", "track": "Good Riddance (Time of Your Life)", "year": 1997},
    {"artist": "Oasis", "track": "Wonderwall", "year": 1995},
    {"artist": "Oasis", "track": "Don't Look Back in Anger", "year": 1995},
    {"artist": "Blur", "track": "Song 2", "year": 1997},
    {"artist": "Radiohead", "track": "Creep", "year": 1992},
    {"artist": "Radiohead", "track": "Karma Police", "year": 1997},
    {"artist": "R.E.M.", "track": "Losing My Religion", "year": 1991},
    {"artist": "U2", "track": "One", "year": 1991},
    {"artist": "Foo Fighters", "track": "Everlong", "year": 1997},
    {"artist": "Smashing Pumpkins", "track": "1979", "year": 1995},
    {"artist": "Smashing Pumpkins", "track": "Bullet with Butterfly Wings", "year": 1995},
    {"artist": "Weezer", "track": "Buddy Holly", "year": 1994},
    {"artist": "Third Eye Blind", "track": "Semi-Charmed Life", "year": 1997},
    {"artist": "Bush", "track": "Glycerine", "year": 1995},
    {"artist": "Live", "track": "Lightning Crashes", "year": 1995},
    {"artist": "Matchbox Twenty", "track": "3AM", "year": 1997},
    {"artist": "Counting Crows", "track": "Mr. Jones", "year": 1993},
    {"artist": "Alanis Morissette", "track": "You Oughta Know", "year": 1995},
    {"artist": "Scorpions", "track": "Wind of Change", "year": 1990},
    {"artist": "Extreme", "track": "More Than Words", "year": 1990},
    {"artist": "Rage Against the Machine", "track": "Killing in the Name", "year": 1992},
    {"artist": "Korn", "track": "Freak on a Leash", "year": 1998},
    # 2000s
    {"artist": "Linkin Park", "track": "In the End", "year": 2001},
    {"artist": "Linkin Park", "track": "Numb", "year": 2003},
    {"artist": "Coldplay", "track": "Yellow", "year": 2000},
    {"artist": "Coldplay", "track": "Clocks", "year": 2002},
    {"artist": "Coldplay", "track": "Viva la Vida", "year": 2008},
    {"artist": "The White Stripes", "track": "Seven Nation Army", "year": 2003},
    {"artist": "The Strokes", "track": "Last Nite", "year": 2001},
    {"artist": "Foo Fighters", "track": "The Pretender", "year": 2007},
    {"artist": "Foo Fighters", "track": "Learn to Fly", "year": 1999},
    {"artist": "Nickelback", "track": "How You Remind Me", "year": 2001},
    {"artist": "Evanescence", "track": "Bring Me to Life", "year": 2003},
    {"artist": "System of a Down", "track": "Chop Suey!", "year": 2001},
    {"artist": "System of a Down", "track": "Toxicity", "year": 2001},
    {"artist": "Green Day", "track": "American Idiot", "year": 2004},
    {"artist": "Green Day", "track": "Boulevard of Broken Dreams", "year": 2004},
    {"artist": "Muse", "track": "Starlight", "year": 2006},
    {"artist": "Muse", "track": "Knights of Cydonia", "year": 2006},
    {"artist": "Kings of Leon", "track": "Sex on Fire", "year": 2008},
    {"artist": "Kings of Leon", "track": "Use Somebody", "year": 2008},
    {"artist": "Arctic Monkeys", "track": "I Bet You Look Good on the Dancefloor", "year": 2005},
    {"artist": "Franz Ferdinand", "track": "Take Me Out", "year": 2004},
    {"artist": "The Killers", "track": "Mr. Brightside", "year": 2004},
    {"artist": "Red Hot Chili Peppers", "track": "Californication", "year": 1999},
    {"artist": "Red Hot Chili Peppers", "track": "Can't Stop", "year": 2002},
    {"artist": "Three Days Grace", "track": "Animal I Have Become", "year": 2006},
    {"artist": "Disturbed", "track": "Down with the Sickness", "year": 2000},
    {"artist": "My Chemical Romance", "track": "Welcome to the Black Parade", "year": 2006},
    {"artist": "Fall Out Boy", "track": "Sugar, We're Goin Down", "year": 2005},
    {"artist": "Panic! at the Disco", "track": "I Write Sins Not Tragedies", "year": 2005},
    {"artist": "Paramore", "track": "Misery Business", "year": 2007},
    # 2010s
    {"artist": "Imagine Dragons", "track": "Radioactive", "year": 2012},
    {"artist": "Imagine Dragons", "track": "Believer", "year": 2017},
    {"artist": "Twenty One Pilots", "track": "Stressed Out", "year": 2015},
    {"artist": "Twenty One Pilots", "track": "Heathens", "year": 2016},
    {"artist": "Foo Fighters", "track": "Walk", "year": 2011},
    {"artist": "Fall Out Boy", "track": "My Songs Know What You Did in the Dark", "year": 2013},
    {"artist": "Arctic Monkeys", "track": "Do I Wanna Know?", "year": 2013},
    {"artist": "Muse", "track": "Madness", "year": 2012},
    {"artist": "The Black Keys", "track": "Lonely Boy", "year": 2011},
    {"artist": "Kings of Leon", "track": "Waste a Moment", "year": 2016},
    {"artist": "Panic! at the Disco", "track": "High Hopes", "year": 2018},
    {"artist": "Portugal. The Man", "track": "Feel It Still", "year": 2017},
    {"artist": "Cage the Elephant", "track": "Ain't No Rest for the Wicked", "year": 2011},
    {"artist": "Royal Blood", "track": "Figure It Out", "year": 2014},
    {"artist": "Greta Van Fleet", "track": "Highway Tune", "year": 2017},
    {"artist": "Bring Me the Horizon", "track": "Can You Feel My Heart", "year": 2015},
    {"artist": "Nothing but Thieves", "track": "Amsterdam", "year": 2018},
    {"artist": "Judah & the Lion", "track": "Suit and Jacket", "year": 2016},
    {"artist": "Walk the Moon", "track": "Shut Up and Dance", "year": 2014},
    {"artist": "The Lumineers", "track": "Ho Hey", "year": 2012},
    {"artist": "Mumford & Sons", "track": "I Will Wait", "year": 2012},
    {"artist": "Bastille", "track": "Pompeii", "year": 2013},
    {"artist": "AWOLNATION", "track": "Sail", "year": 2011},
    {"artist": "X Ambassadors", "track": "Renegades", "year": 2015},
    # 2020
    {"artist": "Glass Animals", "track": "Heat Waves", "year": 2020},
    {"artist": "Machine Gun Kelly", "track": "Bloody Valentine", "year": 2020},
    {"artist": "Fontaines D.C.", "track": "A Hero's Death", "year": 2020},
    {"artist": "The Strokes", "track": "Bad Decisions", "year": 2020},
    {"artist": "AC/DC", "track": "Shot in the Dark", "year": 2020},
)

BLUES_CLASSICS: tuple[dict, ...] = (
    # 1950s
    {"artist": "Muddy Waters", "track": "Hoochie Coochie Man", "year": 1954},
    {"artist": "Muddy Waters", "track": "I Just Want to Make Love to You", "year": 1954},
    {"artist": "Muddy Waters", "track": "Mannish Boy", "year": 1955},
    {"artist": "Howlin' Wolf", "track": "Evil", "year": 1954},
    {"artist": "Howlin' Wolf", "track": "Smokestack Lightnin'", "year": 1956},
    {"artist": "B.B. King", "track": "Three O'Clock Blues", "year": 1951},
    {"artist": "B.B. King", "track": "Every Day I Have the Blues", "year": 1955},
    {"artist": "Elmore James", "track": "Dust My Broom", "year": 1951},
    {"artist": "Big Mama Thornton", "track": "Hound Dog", "year": 1952},
    {"artist": "Little Walter", "track": "Juke", "year": 1952},
    {"artist": "Little Walter", "track": "My Babe", "year": 1955},
    {"artist": "Ray Charles", "track": "I Got a Woman", "year": 1954},
    {"artist": "Ray Charles", "track": "What'd I Say", "year": 1959},
    {"artist": "Bo Diddley", "track": "Bo Diddley", "year": 1955},
    {"artist": "Screamin' Jay Hawkins", "track": "I Put a Spell on You", "year": 1956},
    {"artist": "Jimmy Reed", "track": "Baby What You Want Me to Do", "year": 1959},
    {"artist": "Guitar Slim", "track": "The Things That I Used to Do", "year": 1954},
    {"artist": "Willie Dixon", "track": "Little Red Rooster", "year": 1961},
    # 1960s
    {"artist": "Etta James", "track": "At Last", "year": 1960},
    {"artist": "Etta James", "track": "I'd Rather Go Blind", "year": 1968},
    {"artist": "Howlin' Wolf", "track": "Spoonful", "year": 1960},
    {"artist": "Howlin' Wolf", "track": "Killing Floor", "year": 1964},
    {"artist": "John Lee Hooker", "track": "Boom Boom", "year": 1962},
    {"artist": "Freddie King", "track": "Hide Away", "year": 1961},
    {"artist": "Buddy Guy", "track": "Stone Crazy", "year": 1962},
    {"artist": "Junior Wells", "track": "Messin' with the Kid", "year": 1960},
    {"artist": "B.B. King", "track": "Sweet Little Angel", "year": 1964},
    {"artist": "Albert King", "track": "Born Under a Bad Sign", "year": 1967},
    {"artist": "Albert King", "track": "Crosscut Saw", "year": 1967},
    {"artist": "Paul Butterfield Blues Band", "track": "Born in Chicago", "year": 1965},
    {"artist": "John Mayall & the Bluesbreakers", "track": "All Your Love", "year": 1966},
    {"artist": "Cream", "track": "Crossroads", "year": 1968},
    {"artist": "Cream", "track": "Born Under a Bad Sign", "year": 1968},
    {"artist": "Jimi Hendrix", "track": "Red House", "year": 1967},
    {"artist": "Canned Heat", "track": "On the Road Again", "year": 1968},
    {"artist": "Fleetwood Mac", "track": "Black Magic Woman", "year": 1968},
    {"artist": "Fleetwood Mac", "track": "Oh Well", "year": 1969},
    {"artist": "Led Zeppelin", "track": "You Shook Me", "year": 1969},
    {"artist": "Janis Joplin", "track": "Ball and Chain", "year": 1968},
    {"artist": "Ten Years After", "track": "I'm Going Home", "year": 1969},
    {"artist": "Taj Mahal", "track": "Statesboro Blues", "year": 1968},
    {"artist": "Otis Rush", "track": "I Can't Quit You Baby", "year": 1966},
    {"artist": "Magic Sam", "track": "All Your Love", "year": 1967},
    # 1970s
    {"artist": "B.B. King", "track": "The Thrill Is Gone", "year": 1970},
    {"artist": "The Allman Brothers Band", "track": "Statesboro Blues", "year": 1971},
    {"artist": "The Allman Brothers Band", "track": "Whipping Post", "year": 1971},
    {"artist": "Derek and the Dominos", "track": "Layla", "year": 1970},
    {"artist": "Freddie King", "track": "Going Down", "year": 1971},
    {"artist": "Johnny Winter", "track": "Highway 61 Revisited", "year": 1970},
    {"artist": "ZZ Top", "track": "La Grange", "year": 1973},
    {"artist": "ZZ Top", "track": "Tush", "year": 1975},
    {"artist": "Bobby Bland", "track": "Ain't No Love in the Heart of the City", "year": 1974},
    {"artist": "Albert Collins", "track": "Frosty", "year": 1978},
    {"artist": "Rory Gallagher", "track": "Bullfrog Blues", "year": 1972},
    {"artist": "George Thorogood", "track": "One Bourbon, One Scotch, One Beer", "year": 1977},
    {"artist": "The J. Geils Band", "track": "Whammer Jammer", "year": 1972},
    {"artist": "Little Feat", "track": "Dixie Chicken", "year": 1973},
    {"artist": "Eric Clapton", "track": "Cocaine", "year": 1977},
    {"artist": "Muddy Waters", "track": "I'm Ready", "year": 1978},
    {"artist": "Peter Green", "track": "In the Skies", "year": 1979},
    # 1980s
    {"artist": "Stevie Ray Vaughan", "track": "Pride and Joy", "year": 1983},
    {"artist": "Stevie Ray Vaughan", "track": "Texas Flood", "year": 1983},
    {"artist": "Stevie Ray Vaughan", "track": "Cold Shot", "year": 1984},
    {"artist": "Stevie Ray Vaughan", "track": "Crossfire", "year": 1989},
    {"artist": "George Thorogood", "track": "Bad to the Bone", "year": 1982},
    {"artist": "Robert Cray", "track": "Smoking Gun", "year": 1986},
    {"artist": "Robert Cray", "track": "Phone Booth", "year": 1983},
    {"artist": "The Fabulous Thunderbirds", "track": "Tuff Enuff", "year": 1986},
    {"artist": "John Lee Hooker", "track": "The Healer", "year": 1989},
    {"artist": "Bonnie Raitt", "track": "Thing Called Love", "year": 1989},
    {"artist": "Gary Moore", "track": "Oh Pretty Woman", "year": 1990},
    {"artist": "Albert Collins", "track": "Same Old Thing", "year": 1986},
    # 1990s
    {"artist": "Gary Moore", "track": "Still Got the Blues", "year": 1990},
    {"artist": "Buddy Guy", "track": "Damn Right, I've Got the Blues", "year": 1991},
    {"artist": "Bonnie Raitt", "track": "I Can't Make You Love Me", "year": 1991},
    {"artist": "Eric Clapton", "track": "Tears in Heaven", "year": 1992},
    {"artist": "Eric Clapton", "track": "Change the World", "year": 1996},
    {"artist": "Keb' Mo'", "track": "Am I Wrong", "year": 1994},
    {"artist": "Jonny Lang", "track": "Lie to Me", "year": 1997},
    {"artist": "Kenny Wayne Shepherd", "track": "Blue on Black", "year": 1997},
    {"artist": "Susan Tedeschi", "track": "It Hurt So Bad", "year": 1998},
    {"artist": "Ben Harper", "track": "Ground on Down", "year": 1997},
    {"artist": "John Lee Hooker", "track": "Chill Out", "year": 1995},
    {"artist": "Corey Harris", "track": "Between Midnight and Day", "year": 1995},
    # 2000s
    {"artist": "The White Stripes", "track": "Ball and Biscuit", "year": 2003},
    {"artist": "The Black Keys", "track": "Thickfreakness", "year": 2003},
    {"artist": "The Black Keys", "track": "Your Touch", "year": 2006},
    {"artist": "Joe Bonamassa", "track": "Sloe Gin", "year": 2007},
    {"artist": "North Mississippi Allstars", "track": "Shake 'Em On Down", "year": 2000},
    {"artist": "The Derek Trucks Band", "track": "Down in the Flood", "year": 2002},
    {"artist": "Susan Tedeschi", "track": "Alone", "year": 2002},
    {"artist": "Seasick Steve", "track": "Dog House Boogie", "year": 2006},
    {"artist": "Buddy Guy", "track": "Skin Deep", "year": 2008},
    {"artist": "Eric Clapton", "track": "Riding with the King", "year": 2000},
    # 2010s–2020
    {"artist": "Gary Clark Jr.", "track": "Bright Lights", "year": 2011},
    {"artist": "Gary Clark Jr.", "track": "This Land", "year": 2019},
    {"artist": "Joe Bonamassa", "track": "Dust Bowl", "year": 2011},
    {"artist": "Tedeschi Trucks Band", "track": "Midnight in Harlem", "year": 2011},
    {"artist": "Rival Sons", "track": "Keep On Swinging", "year": 2011},
    {"artist": "Larkin Poe", "track": "Preachin' Blues", "year": 2018},
    {"artist": "Christone \"Kingfish\" Ingram", "track": "Outside of This Town", "year": 2019},
    {"artist": "Fantastic Negrito", "track": "Plastic Hamburgers", "year": 2018},
    {"artist": "Marcus King", "track": "The Well", "year": 2020},
    {"artist": "Samantha Fish", "track": "Bulletproof", "year": 2017},
)


# ---------- קטגוריות ----------

# העשורים והקטגוריות ה"קלאסיות" אינן רשימות נפרדות אלא חתכים של אותם נתונים:
# לכל רשומה יש `year`, ולכן "אולדיס" או "80's" הם סינון ולא תחזוקה כפולה.
# רק ז'אנר חדש דורש רשימה חדשה.
ALL_CLASSICS: tuple[dict, ...] = POP_CLASSICS + ROCK_CLASSICS + BLUES_CLASSICS


def in_years(entries: tuple, first: int, last: int) -> tuple:
    return tuple(entry for entry in entries if first <= entry["year"] <= last)


# הגבולות אינם שרירותיים אלא פורמטי רדיו מקובלים: "אולדיס" הוא 50s–60s,
# "רוק קלאסי" הוא הרוק שבין הפלישה הבריטית לגראנג', ו"פופ קלאסי" הוא הפופ
# שלפני עידן ה-CD. מי שרוצה חתך אחר יכול לבחור עשור ישירות.
CATEGORIES: dict[str, tuple] = {
    "🎤 פופ": POP_CLASSICS,
    "🎸 רוק": ROCK_CLASSICS,
    "🎺 בלוז": BLUES_CLASSICS,
    "🎤 פופ קלאסי": in_years(POP_CLASSICS, 1950, 1989),
    "🎸 רוק קלאסי": in_years(ROCK_CLASSICS, 1965, 1995),
    "📻 אולדיס": in_years(ALL_CLASSICS, 1950, 1969),
    "50's": in_years(ALL_CLASSICS, 1950, 1959),
    "60's": in_years(ALL_CLASSICS, 1960, 1969),
    "70's": in_years(ALL_CLASSICS, 1970, 1979),
    "80's": in_years(ALL_CLASSICS, 1980, 1989),
    "90's": in_years(ALL_CLASSICS, 1990, 1999),
    "2000's": in_years(ALL_CLASSICS, 2000, 2009),
    "2010's": in_years(ALL_CLASSICS, 2010, 2020),
}
