"""רשימות קלאסיקות סטטיות — פופ, רוק ובלוז, 1950–2020.

מחליפות את מצעד ה-Deezer החי באינדקס המצעדים: מצעד "חי" מציג טרנדים
עדכניים שהמשתמש לרוב לא מזהה, בעוד שהמטרה כאן היא נקודת פתיחה של שירים
מוכרים לחיפוש קאברים. הרשימות מוכנות מראש בקוד — באותה שיטה כמו
`artists.GREATEST_ARTISTS` — ולא נשלפות מ-API חי, כדי שיהיו יציבות,
מוכרות וזמינות בלי תלות ברשת.

קטגוריות העשורים מגיעות מ-`chart_data` — נתוני Billboard Hot 100
היסטוריים, שם ההיכרות נמדדת מהופעות בפועל במצעד ולא מהזיכרון. הרשימות
כאן משרתות את קטגוריות הז'אנר, שאין להן מקבילה במצעד.

כל רשומה: {"artist": ..., "track": ..., "year": ...}. השנה היא הערכה
(שנת יציאה/שיא הצלחה) ומיועדת להצגה בלבד, לא לדיוק ארכיוני.
"""
import chart_data

POP_CLASSICS: tuple[dict, ...] = (
    # 1950s
    {"artist": "Patti Page", "track": "Tennessee Waltz", "year": 1950},
    {"artist": "Nat King Cole", "track": "Unforgettable", "year": 1951},
    {"artist": "Frank Sinatra", "track": "Love and Marriage", "year": 1955},
    {"artist": "The Platters", "track": "Only You (And You Alone)", "year": 1955},
    {"artist": "The Platters", "track": "The Great Pretender", "year": 1955},
    {"artist": "The Platters", "track": "Smoke Gets in Your Eyes", "year": 1958},
    {"artist": "Doris Day", "track": "Que Sera, Sera (Whatever Will Be, Will Be)", "year": 1956},
    {"artist": "Perry Como", "track": "Magic Moments", "year": 1957},
    {"artist": "Pat Boone", "track": "Love Letters in the Sand", "year": 1957},
    {"artist": "The Everly Brothers", "track": "All I Have to Do Is Dream", "year": 1958},
    {"artist": "Connie Francis", "track": "Who's Sorry Now", "year": 1958},
    {"artist": "Bobby Darin", "track": "Mack the Knife", "year": 1959},
    # 1960s
    {"artist": "Elvis Presley", "track": "Can't Help Falling in Love", "year": 1961},
    {"artist": "The Shirelles", "track": "Will You Love Me Tomorrow", "year": 1960},
    {"artist": "Roy Orbison", "track": "Only the Lonely", "year": 1960},
    {"artist": "Ray Charles", "track": "Georgia on My Mind", "year": 1960},
    {"artist": "The Beach Boys", "track": "Surfin' USA", "year": 1963},
    {"artist": "The Supremes", "track": "Where Did Our Love Go", "year": 1964},
    {"artist": "The Supremes", "track": "Baby Love", "year": 1964},
    {"artist": "The Supremes", "track": "Stop! In the Name of Love", "year": 1965},
    {"artist": "Dionne Warwick", "track": "Walk On By", "year": 1964},
    {"artist": "Petula Clark", "track": "Downtown", "year": 1964},
    {"artist": "The Mamas & the Papas", "track": "California Dreamin'", "year": 1965},
    {"artist": "The Righteous Brothers", "track": "You've Lost That Lovin' Feelin'", "year": 1964},
    {"artist": "Frank Sinatra", "track": "Strangers in the Night", "year": 1966},
    {"artist": "The Turtles", "track": "Happy Together", "year": 1967},
    {"artist": "Aretha Franklin", "track": "Respect", "year": 1967},
    {"artist": "Otis Redding", "track": "(Sittin' On) The Dock of the Bay", "year": 1968},
    {"artist": "Marvin Gaye", "track": "I Heard It Through the Grapevine", "year": 1968},
    {"artist": "The 5th Dimension", "track": "Aquarius / Let the Sunshine In", "year": 1969},
    {"artist": "Simon & Garfunkel", "track": "The Sound of Silence", "year": 1965},
    {"artist": "Simon & Garfunkel", "track": "Mrs. Robinson", "year": 1968},
    {"artist": "Dusty Springfield", "track": "Son of a Preacher Man", "year": 1968},
    {"artist": "Nancy Sinatra", "track": "These Boots Are Made for Walkin'", "year": 1966},
    {"artist": "The Beatles", "track": "Yesterday", "year": 1965},
    {"artist": "The Beatles", "track": "Hey Jude", "year": 1968},
    {"artist": "The Beatles", "track": "Let It Be", "year": 1970},
    {"artist": "Neil Diamond", "track": "Sweet Caroline", "year": 1969},
    {"artist": "The Monkees", "track": "I'm a Believer", "year": 1966},
    {"artist": "Sam Cooke", "track": "A Change Is Gonna Come", "year": 1964},
    {"artist": "Stevie Wonder", "track": "My Cherie Amour", "year": 1969},
    {"artist": "The Association", "track": "Cherish", "year": 1966},
    # 1970s
    {"artist": "Carole King", "track": "It's Too Late", "year": 1971},
    {"artist": "Carly Simon", "track": "You're So Vain", "year": 1972},
    {"artist": "Roberta Flack", "track": "Killing Me Softly with His Song", "year": 1973},
    {"artist": "The Carpenters", "track": "(They Long to Be) Close to You", "year": 1970},
    {"artist": "The Carpenters", "track": "Rainy Days and Mondays", "year": 1971},
    {"artist": "Elton John", "track": "Your Song", "year": 1970},
    {"artist": "Elton John", "track": "Rocket Man", "year": 1972},
    {"artist": "Elton John", "track": "Goodbye Yellow Brick Road", "year": 1973},
    {"artist": "Stevie Wonder", "track": "Superstition", "year": 1972},
    {"artist": "Stevie Wonder", "track": "Isn't She Lovely", "year": 1976},
    {"artist": "Marvin Gaye", "track": "Let's Get It On", "year": 1973},
    {"artist": "Al Green", "track": "Let's Stay Together", "year": 1972},
    {"artist": "Gladys Knight & the Pips", "track": "Midnight Train to Georgia", "year": 1973},
    {"artist": "ABBA", "track": "Dancing Queen", "year": 1976},
    {"artist": "ABBA", "track": "Mamma Mia", "year": 1975},
    {"artist": "Bee Gees", "track": "Stayin' Alive", "year": 1977},
    {"artist": "Bee Gees", "track": "How Deep Is Your Love", "year": 1977},
    {"artist": "Donna Summer", "track": "Hot Stuff", "year": 1979},
    {"artist": "Donna Summer", "track": "I Feel Love", "year": 1977},
    {"artist": "Chic", "track": "Le Freak", "year": 1978},
    {"artist": "Gloria Gaynor", "track": "I Will Survive", "year": 1978},
    {"artist": "Billy Joel", "track": "Piano Man", "year": 1973},
    {"artist": "Billy Joel", "track": "Just the Way You Are", "year": 1977},
    {"artist": "Barry Manilow", "track": "Mandy", "year": 1974},
    {"artist": "Fleetwood Mac", "track": "Dreams", "year": 1977},
    {"artist": "Barbra Streisand", "track": "The Way We Were", "year": 1973},
    {"artist": "John Denver", "track": "Take Me Home, Country Roads", "year": 1971},
    {"artist": "Boz Scaggs", "track": "Lowdown", "year": 1976},
    {"artist": "Player", "track": "Baby Come Back", "year": 1977},
    {"artist": "Rod Stewart", "track": "Da Ya Think I'm Sexy?", "year": 1978},
    # 1980s
    {"artist": "Michael Jackson", "track": "Billie Jean", "year": 1983},
    {"artist": "Michael Jackson", "track": "Thriller", "year": 1982},
    {"artist": "Michael Jackson", "track": "Beat It", "year": 1983},
    {"artist": "Michael Jackson", "track": "Bad", "year": 1987},
    {"artist": "Madonna", "track": "Like a Virgin", "year": 1984},
    {"artist": "Madonna", "track": "Material Girl", "year": 1985},
    {"artist": "Whitney Houston", "track": "I Wanna Dance with Somebody", "year": 1987},
    {"artist": "Whitney Houston", "track": "Greatest Love of All", "year": 1985},
    {"artist": "Prince", "track": "When Doves Cry", "year": 1984},
    {"artist": "Prince", "track": "Purple Rain", "year": 1984},
    {"artist": "Cyndi Lauper", "track": "Girls Just Want to Have Fun", "year": 1983},
    {"artist": "Cyndi Lauper", "track": "Time After Time", "year": 1984},
    {"artist": "Tears for Fears", "track": "Everybody Wants to Rule the World", "year": 1985},
    {"artist": "Duran Duran", "track": "Hungry Like the Wolf", "year": 1982},
    {"artist": "Culture Club", "track": "Karma Chameleon", "year": 1983},
    {"artist": "Wham!", "track": "Wake Me Up Before You Go-Go", "year": 1984},
    {"artist": "George Michael", "track": "Careless Whisper", "year": 1984},
    {"artist": "George Michael", "track": "Faith", "year": 1987},
    {"artist": "Lionel Richie", "track": "All Night Long (All Night)", "year": 1983},
    {"artist": "Lionel Richie", "track": "Hello", "year": 1984},
    {"artist": "Phil Collins", "track": "Against All Odds (Take a Look at Me Now)", "year": 1984},
    {"artist": "Phil Collins", "track": "In the Air Tonight", "year": 1981},
    {"artist": "Hall & Oates", "track": "Maneater", "year": 1982},
    {"artist": "The Human League", "track": "Don't You Want Me", "year": 1981},
    {"artist": "a-ha", "track": "Take On Me", "year": 1985},
    {"artist": "Whitney Houston", "track": "How Will I Know", "year": 1985},
    {"artist": "Simple Minds", "track": "Don't You (Forget About Me)", "year": 1985},
    {"artist": "Kenny Loggins", "track": "Footloose", "year": 1984},
    {"artist": "Kool & the Gang", "track": "Celebration", "year": 1980},
    {"artist": "Stevie Wonder", "track": "I Just Called to Say I Love You", "year": 1984},
    {"artist": "Bonnie Tyler", "track": "Total Eclipse of the Heart", "year": 1983},
    {"artist": "Irene Cara", "track": "Flashdance... What a Feeling", "year": 1983},
    {"artist": "Diana Ross & Lionel Richie", "track": "Endless Love", "year": 1981},
    {"artist": "Toto", "track": "Africa", "year": 1982},
    # 1990s
    {"artist": "Whitney Houston", "track": "I Will Always Love You", "year": 1992},
    {"artist": "Mariah Carey", "track": "Vision of Love", "year": 1990},
    {"artist": "Mariah Carey", "track": "Fantasy", "year": 1995},
    {"artist": "Mariah Carey", "track": "Hero", "year": 1993},
    {"artist": "Celine Dion", "track": "My Heart Will Go On", "year": 1997},
    {"artist": "Celine Dion", "track": "Because You Loved Me", "year": 1996},
    {"artist": "Madonna", "track": "Vogue", "year": 1990},
    {"artist": "Madonna", "track": "Frozen", "year": 1998},
    {"artist": "Whitney Houston", "track": "I'm Every Woman", "year": 1993},
    {"artist": "TLC", "track": "Waterfalls", "year": 1995},
    {"artist": "TLC", "track": "No Scrubs", "year": 1999},
    {"artist": "Spice Girls", "track": "Wannabe", "year": 1996},
    {"artist": "Backstreet Boys", "track": "I Want It That Way", "year": 1999},
    {"artist": "Britney Spears", "track": "...Baby One More Time", "year": 1998},
    {"artist": "Christina Aguilera", "track": "Genie in a Bottle", "year": 1999},
    {"artist": "Boyz II Men", "track": "End of the Road", "year": 1992},
    {"artist": "Boyz II Men", "track": "I'll Make Love to You", "year": 1994},
    {"artist": "Toni Braxton", "track": "Un-Break My Heart", "year": 1996},
    {"artist": "Alanis Morissette", "track": "Ironic", "year": 1996},
    {"artist": "Sheryl Crow", "track": "All I Wanna Do", "year": 1994},
    {"artist": "Shania Twain", "track": "Man! I Feel Like a Woman!", "year": 1997},
    {"artist": "Savage Garden", "track": "Truly Madly Deeply", "year": 1997},
    {"artist": "Robyn", "track": "Show Me Love", "year": 1997},
    {"artist": "En Vogue", "track": "My Lovin' (You're Never Gonna Get It)", "year": 1992},
    {"artist": "Ace of Base", "track": "The Sign", "year": 1993},
    {"artist": "Des'ree", "track": "You Gotta Be", "year": 1994},
    {"artist": "Vanessa Williams", "track": "Save the Best for Last", "year": 1992},
    {"artist": "Lauryn Hill", "track": "Doo Wop (That Thing)", "year": 1998},
    {"artist": "Cher", "track": "Believe", "year": 1998},
    {"artist": "Destiny's Child", "track": "Say My Name", "year": 2000},
    # 2000s
    {"artist": "Beyoncé", "track": "Crazy in Love", "year": 2003},
    {"artist": "Beyoncé", "track": "Single Ladies (Put a Ring on It)", "year": 2008},
    {"artist": "Beyoncé", "track": "Halo", "year": 2008},
    {"artist": "Rihanna", "track": "Umbrella", "year": 2007},
    {"artist": "Justin Timberlake", "track": "Cry Me a River", "year": 2002},
    {"artist": "Justin Timberlake", "track": "SexyBack", "year": 2006},
    {"artist": "Kelly Clarkson", "track": "Since U Been Gone", "year": 2004},
    {"artist": "Christina Aguilera", "track": "Beautiful", "year": 2002},
    {"artist": "Usher", "track": "Yeah!", "year": 2004},
    {"artist": "Alicia Keys", "track": "Fallin'", "year": 2001},
    {"artist": "Alicia Keys", "track": "No One", "year": 2007},
    {"artist": "Amy Winehouse", "track": "Rehab", "year": 2006},
    {"artist": "Amy Winehouse", "track": "Back to Black", "year": 2006},
    {"artist": "Adele", "track": "Chasing Pavements", "year": 2008},
    {"artist": "Katy Perry", "track": "I Kissed a Girl", "year": 2008},
    {"artist": "Lady Gaga", "track": "Just Dance", "year": 2008},
    {"artist": "Lady Gaga", "track": "Poker Face", "year": 2008},
    {"artist": "Black Eyed Peas", "track": "I Gotta Feeling", "year": 2009},
    {"artist": "Black Eyed Peas", "track": "Boom Boom Pow", "year": 2009},
    {"artist": "Fergie", "track": "Glamorous", "year": 2007},
    {"artist": "Gwen Stefani", "track": "Hollaback Girl", "year": 2005},
    {"artist": "Nelly Furtado", "track": "Say It Right", "year": 2006},
    {"artist": "Colbie Caillat", "track": "Bubbly", "year": 2007},
    {"artist": "Leona Lewis", "track": "Bleeding Love", "year": 2007},
    {"artist": "OutKast", "track": "Hey Ya!", "year": 2003},
    {"artist": "Norah Jones", "track": "Don't Know Why", "year": 2002},
    {"artist": "John Mayer", "track": "Your Body Is a Wonderland", "year": 2001},
    {"artist": "Maroon 5", "track": "This Love", "year": 2004},
    # 2010s
    {"artist": "Adele", "track": "Rolling in the Deep", "year": 2011},
    {"artist": "Adele", "track": "Someone Like You", "year": 2011},
    {"artist": "Adele", "track": "Hello", "year": 2015},
    {"artist": "Bruno Mars", "track": "Just the Way You Are", "year": 2010},
    {"artist": "Bruno Mars", "track": "Uptown Funk", "year": 2014},
    {"artist": "Katy Perry", "track": "Firework", "year": 2010},
    {"artist": "Katy Perry", "track": "Roar", "year": 2013},
    {"artist": "Lady Gaga", "track": "Bad Romance", "year": 2010},
    {"artist": "Rihanna", "track": "We Found Love", "year": 2011},
    {"artist": "Rihanna", "track": "Diamonds", "year": 2012},
    {"artist": "Taylor Swift", "track": "Shake It Off", "year": 2014},
    {"artist": "Taylor Swift", "track": "Blank Space", "year": 2014},
    {"artist": "Ed Sheeran", "track": "Thinking Out Loud", "year": 2014},
    {"artist": "Ed Sheeran", "track": "Shape of You", "year": 2017},
    {"artist": "Sam Smith", "track": "Stay with Me", "year": 2014},
    {"artist": "Sia", "track": "Chandelier", "year": 2014},
    {"artist": "Meghan Trainor", "track": "All About That Bass", "year": 2014},
    {"artist": "Pharrell Williams", "track": "Happy", "year": 2013},
    {"artist": "Justin Timberlake", "track": "Can't Stop the Feeling!", "year": 2016},
    {"artist": "Ariana Grande", "track": "Thank U, Next", "year": 2018},
    {"artist": "Ariana Grande", "track": "7 rings", "year": 2019},
    {"artist": "Dua Lipa", "track": "New Rules", "year": 2017},
    {"artist": "Billie Eilish", "track": "Bad Guy", "year": 2019},
    {"artist": "Camila Cabello", "track": "Havana", "year": 2017},
    {"artist": "Shawn Mendes", "track": "Stitches", "year": 2015},
    {"artist": "The Weeknd", "track": "Can't Feel My Face", "year": 2015},
    {"artist": "The Weeknd", "track": "Blinding Lights", "year": 2019},
    {"artist": "Post Malone", "track": "Circles", "year": 2019},
    {"artist": "Lizzo", "track": "Truth Hurts", "year": 2019},
    # 2020
    {"artist": "Dua Lipa", "track": "Don't Start Now", "year": 2020},
    {"artist": "Harry Styles", "track": "Watermelon Sugar", "year": 2020},
    {"artist": "Doja Cat", "track": "Say So", "year": 2020},
    {"artist": "Ariana Grande", "track": "Positions", "year": 2020},
    {"artist": "Billie Eilish", "track": "Therefore I Am", "year": 2020},
)

ROCK_CLASSICS: tuple[dict, ...] = (
    # 1950s
    {"artist": "Bill Haley & His Comets", "track": "Rock Around the Clock", "year": 1954},
    {"artist": "Chuck Berry", "track": "Maybellene", "year": 1955},
    {"artist": "Chuck Berry", "track": "Johnny B. Goode", "year": 1958},
    {"artist": "Elvis Presley", "track": "Hound Dog", "year": 1956},
    {"artist": "Elvis Presley", "track": "Jailhouse Rock", "year": 1957},
    {"artist": "Little Richard", "track": "Tutti Frutti", "year": 1955},
    {"artist": "Little Richard", "track": "Long Tall Sally", "year": 1956},
    {"artist": "Buddy Holly", "track": "That'll Be the Day", "year": 1957},
    {"artist": "Buddy Holly", "track": "Peggy Sue", "year": 1957},
    {"artist": "Jerry Lee Lewis", "track": "Great Balls of Fire", "year": 1957},
    {"artist": "Eddie Cochran", "track": "Summertime Blues", "year": 1958},
    {"artist": "The Everly Brothers", "track": "Bye Bye Love", "year": 1957},
    # 1960s
    {"artist": "The Beatles", "track": "I Want to Hold Your Hand", "year": 1963},
    {"artist": "The Beatles", "track": "Twist and Shout", "year": 1963},
    {"artist": "The Beatles", "track": "Come Together", "year": 1969},
    {"artist": "The Beatles", "track": "Helter Skelter", "year": 1968},
    {"artist": "The Rolling Stones", "track": "(I Can't Get No) Satisfaction", "year": 1965},
    {"artist": "The Rolling Stones", "track": "Paint It Black", "year": 1966},
    {"artist": "The Rolling Stones", "track": "Jumpin' Jack Flash", "year": 1968},
    {"artist": "The Rolling Stones", "track": "Sympathy for the Devil", "year": 1968},
    {"artist": "The Who", "track": "My Generation", "year": 1965},
    {"artist": "The Kinks", "track": "You Really Got Me", "year": 1964},
    {"artist": "The Animals", "track": "House of the Rising Sun", "year": 1964},
    {"artist": "The Beach Boys", "track": "Good Vibrations", "year": 1966},
    {"artist": "Jimi Hendrix", "track": "Purple Haze", "year": 1967},
    {"artist": "Jimi Hendrix", "track": "All Along the Watchtower", "year": 1968},
    {"artist": "Cream", "track": "Sunshine of Your Love", "year": 1968},
    {"artist": "Led Zeppelin", "track": "Whole Lotta Love", "year": 1969},
    {"artist": "Led Zeppelin", "track": "Communication Breakdown", "year": 1969},
    {"artist": "Steppenwolf", "track": "Born to Be Wild", "year": 1968},
    {"artist": "Creedence Clearwater Revival", "track": "Bad Moon Rising", "year": 1969},
    {"artist": "Creedence Clearwater Revival", "track": "Proud Mary", "year": 1969},
    {"artist": "The Doors", "track": "Light My Fire", "year": 1967},
    {"artist": "The Doors", "track": "Break On Through (To the Other Side)", "year": 1967},
    {"artist": "Deep Purple", "track": "Hush", "year": 1968},
    {"artist": "Van Morrison", "track": "Brown Eyed Girl", "year": 1967},
    {"artist": "The Byrds", "track": "Mr. Tambourine Man", "year": 1965},
    {"artist": "Bob Dylan", "track": "Like a Rolling Stone", "year": 1965},
    {"artist": "Big Brother and the Holding Company", "track": "Piece of My Heart", "year": 1968},
    {"artist": "Fleetwood Mac", "track": "Albatross", "year": 1968},
    {"artist": "The Yardbirds", "track": "For Your Love", "year": 1965},
    # 1970s
    {"artist": "Led Zeppelin", "track": "Stairway to Heaven", "year": 1971},
    {"artist": "Led Zeppelin", "track": "Black Dog", "year": 1971},
    {"artist": "Led Zeppelin", "track": "Kashmir", "year": 1975},
    {"artist": "Deep Purple", "track": "Smoke on the Water", "year": 1972},
    {"artist": "Black Sabbath", "track": "Paranoid", "year": 1970},
    {"artist": "Black Sabbath", "track": "Iron Man", "year": 1970},
    {"artist": "Queen", "track": "Bohemian Rhapsody", "year": 1975},
    {"artist": "Queen", "track": "We Will Rock You", "year": 1977},
    {"artist": "Queen", "track": "We Are the Champions", "year": 1977},
    {"artist": "Pink Floyd", "track": "Another Brick in the Wall", "year": 1979},
    {"artist": "Pink Floyd", "track": "Money", "year": 1973},
    {"artist": "Pink Floyd", "track": "Wish You Were Here", "year": 1975},
    {"artist": "Eagles", "track": "Hotel California", "year": 1976},
    {"artist": "Eagles", "track": "Take It Easy", "year": 1972},
    {"artist": "Fleetwood Mac", "track": "Go Your Own Way", "year": 1977},
    {"artist": "Fleetwood Mac", "track": "The Chain", "year": 1977},
    {"artist": "Aerosmith", "track": "Dream On", "year": 1973},
    {"artist": "Aerosmith", "track": "Sweet Emotion", "year": 1975},
    {"artist": "Boston", "track": "More Than a Feeling", "year": 1976},
    {"artist": "Journey", "track": "Wheel in the Sky", "year": 1978},
    {"artist": "Kansas", "track": "Carry On Wayward Son", "year": 1976},
    {"artist": "Lynyrd Skynyrd", "track": "Sweet Home Alabama", "year": 1974},
    {"artist": "Lynyrd Skynyrd", "track": "Free Bird", "year": 1973},
    {"artist": "The Who", "track": "Baba O'Riley", "year": 1971},
    {"artist": "The Who", "track": "Won't Get Fooled Again", "year": 1971},
    {"artist": "David Bowie", "track": "Ziggy Stardust", "year": 1972},
    {"artist": "David Bowie", "track": "Heroes", "year": 1977},
    {"artist": "Elton John", "track": "Saturday Night's Alright for Fighting", "year": 1973},
    {"artist": "Bruce Springsteen", "track": "Born to Run", "year": 1975},
    {"artist": "Rod Stewart", "track": "Maggie May", "year": 1971},
    {"artist": "Bob Seger", "track": "Night Moves", "year": 1976},
    {"artist": "Thin Lizzy", "track": "The Boys Are Back in Town", "year": 1976},
    {"artist": "AC/DC", "track": "T.N.T.", "year": 1975},
    {"artist": "AC/DC", "track": "Highway to Hell", "year": 1979},
    # 1980s
    {"artist": "AC/DC", "track": "Back in Black", "year": 1980},
    {"artist": "AC/DC", "track": "You Shook Me All Night Long", "year": 1980},
    {"artist": "Journey", "track": "Don't Stop Believin'", "year": 1981},
    {"artist": "Def Leppard", "track": "Pour Some Sugar on Me", "year": 1987},
    {"artist": "Def Leppard", "track": "Photograph", "year": 1983},
    {"artist": "Guns N' Roses", "track": "Sweet Child o' Mine", "year": 1987},
    {"artist": "Guns N' Roses", "track": "Welcome to the Jungle", "year": 1987},
    {"artist": "Bon Jovi", "track": "Livin' on a Prayer", "year": 1986},
    {"artist": "Bon Jovi", "track": "Wanted Dead or Alive", "year": 1986},
    {"artist": "Van Halen", "track": "Jump", "year": 1984},
    {"artist": "Van Halen", "track": "Panama", "year": 1984},
    {"artist": "U2", "track": "Sunday Bloody Sunday", "year": 1983},
    {"artist": "U2", "track": "With or Without You", "year": 1987},
    {"artist": "U2", "track": "I Still Haven't Found What I'm Looking For", "year": 1987},
    {"artist": "The Police", "track": "Every Breath You Take", "year": 1983},
    {"artist": "Dire Straits", "track": "Money for Nothing", "year": 1985},
    {"artist": "Queen", "track": "Another One Bites the Dust", "year": 1980},
    {"artist": "Queen", "track": "Radio Ga Ga", "year": 1984},
    {"artist": "Survivor", "track": "Eye of the Tiger", "year": 1982},
    {"artist": "Twisted Sister", "track": "We're Not Gonna Take It", "year": 1984},
    {"artist": "Scorpions", "track": "Rock You Like a Hurricane", "year": 1984},
    {"artist": "Iron Maiden", "track": "The Number of the Beast", "year": 1982},
    {"artist": "Judas Priest", "track": "Breaking the Law", "year": 1980},
    {"artist": "Metallica", "track": "Master of Puppets", "year": 1986},
    {"artist": "Metallica", "track": "One", "year": 1988},
    {"artist": "Poison", "track": "Every Rose Has Its Thorn", "year": 1988},
    {"artist": "Whitesnake", "track": "Here I Go Again", "year": 1987},
    {"artist": "ZZ Top", "track": "Sharp Dressed Man", "year": 1983},
    {"artist": "ZZ Top", "track": "Legs", "year": 1983},
    {"artist": "Talking Heads", "track": "Once in a Lifetime", "year": 1980},
    {"artist": "The Cars", "track": "Drive", "year": 1984},
    {"artist": "INXS", "track": "Need You Tonight", "year": 1987},
    {"artist": "R.E.M.", "track": "The One I Love", "year": 1987},
    {"artist": "Bryan Adams", "track": "Summer of '69", "year": 1985},
    # 1990s
    {"artist": "Nirvana", "track": "Smells Like Teen Spirit", "year": 1991},
    {"artist": "Nirvana", "track": "Come as You Are", "year": 1991},
    {"artist": "Pearl Jam", "track": "Alive", "year": 1991},
    {"artist": "Pearl Jam", "track": "Jeremy", "year": 1992},
    {"artist": "Soundgarden", "track": "Black Hole Sun", "year": 1994},
    {"artist": "Alice in Chains", "track": "Man in the Box", "year": 1990},
    {"artist": "Stone Temple Pilots", "track": "Plush", "year": 1993},
    {"artist": "Red Hot Chili Peppers", "track": "Under the Bridge", "year": 1991},
    {"artist": "Red Hot Chili Peppers", "track": "Give It Away", "year": 1991},
    {"artist": "Guns N' Roses", "track": "November Rain", "year": 1991},
    {"artist": "Metallica", "track": "Enter Sandman", "year": 1991},
    {"artist": "Metallica", "track": "Nothing Else Matters", "year": 1991},
    {"artist": "Green Day", "track": "Basket Case", "year": 1994},
    {"artist": "Green Day", "track": "Good Riddance (Time of Your Life)", "year": 1997},
    {"artist": "Oasis", "track": "Wonderwall", "year": 1995},
    {"artist": "Oasis", "track": "Don't Look Back in Anger", "year": 1995},
    {"artist": "Blur", "track": "Song 2", "year": 1997},
    {"artist": "Radiohead", "track": "Creep", "year": 1992},
    {"artist": "Radiohead", "track": "Karma Police", "year": 1997},
    {"artist": "R.E.M.", "track": "Losing My Religion", "year": 1991},
    {"artist": "U2", "track": "One", "year": 1991},
    {"artist": "Foo Fighters", "track": "Everlong", "year": 1997},
    {"artist": "Smashing Pumpkins", "track": "1979", "year": 1995},
    {"artist": "Smashing Pumpkins", "track": "Bullet with Butterfly Wings", "year": 1995},
    {"artist": "Weezer", "track": "Buddy Holly", "year": 1994},
    {"artist": "Third Eye Blind", "track": "Semi-Charmed Life", "year": 1997},
    {"artist": "Bush", "track": "Glycerine", "year": 1995},
    {"artist": "Live", "track": "Lightning Crashes", "year": 1995},
    {"artist": "Matchbox Twenty", "track": "3AM", "year": 1997},
    {"artist": "Counting Crows", "track": "Mr. Jones", "year": 1993},
    {"artist": "Alanis Morissette", "track": "You Oughta Know", "year": 1995},
    {"artist": "Scorpions", "track": "Wind of Change", "year": 1990},
    {"artist": "Extreme", "track": "More Than Words", "year": 1990},
    {"artist": "Rage Against the Machine", "track": "Killing in the Name", "year": 1992},
    {"artist": "Korn", "track": "Freak on a Leash", "year": 1998},
    # 2000s
    {"artist": "Linkin Park", "track": "In the End", "year": 2001},
    {"artist": "Linkin Park", "track": "Numb", "year": 2003},
    {"artist": "Coldplay", "track": "Yellow", "year": 2000},
    {"artist": "Coldplay", "track": "Clocks", "year": 2002},
    {"artist": "Coldplay", "track": "Viva la Vida", "year": 2008},
    {"artist": "The White Stripes", "track": "Seven Nation Army", "year": 2003},
    {"artist": "The Strokes", "track": "Last Nite", "year": 2001},
    {"artist": "Foo Fighters", "track": "The Pretender", "year": 2007},
    {"artist": "Foo Fighters", "track": "Learn to Fly", "year": 1999},
    {"artist": "Nickelback", "track": "How You Remind Me", "year": 2001},
    {"artist": "Evanescence", "track": "Bring Me to Life", "year": 2003},
    {"artist": "System of a Down", "track": "Chop Suey!", "year": 2001},
    {"artist": "System of a Down", "track": "Toxicity", "year": 2001},
    {"artist": "Green Day", "track": "American Idiot", "year": 2004},
    {"artist": "Green Day", "track": "Boulevard of Broken Dreams", "year": 2004},
    {"artist": "Muse", "track": "Starlight", "year": 2006},
    {"artist": "Muse", "track": "Knights of Cydonia", "year": 2006},
    {"artist": "Kings of Leon", "track": "Sex on Fire", "year": 2008},
    {"artist": "Kings of Leon", "track": "Use Somebody", "year": 2008},
    {"artist": "Arctic Monkeys", "track": "I Bet You Look Good on the Dancefloor", "year": 2005},
    {"artist": "Franz Ferdinand", "track": "Take Me Out", "year": 2004},
    {"artist": "The Killers", "track": "Mr. Brightside", "year": 2004},
    {"artist": "Red Hot Chili Peppers", "track": "Californication", "year": 1999},
    {"artist": "Red Hot Chili Peppers", "track": "Can't Stop", "year": 2002},
    {"artist": "Three Days Grace", "track": "Animal I Have Become", "year": 2006},
    {"artist": "Disturbed", "track": "Down with the Sickness", "year": 2000},
    {"artist": "My Chemical Romance", "track": "Welcome to the Black Parade", "year": 2006},
    {"artist": "Fall Out Boy", "track": "Sugar, We're Goin Down", "year": 2005},
    {"artist": "Panic! at the Disco", "track": "I Write Sins Not Tragedies", "year": 2005},
    {"artist": "Paramore", "track": "Misery Business", "year": 2007},
    # 2010s
    {"artist": "Imagine Dragons", "track": "Radioactive", "year": 2012},
    {"artist": "Imagine Dragons", "track": "Believer", "year": 2017},
    {"artist": "Twenty One Pilots", "track": "Stressed Out", "year": 2015},
    {"artist": "Twenty One Pilots", "track": "Heathens", "year": 2016},
    {"artist": "Foo Fighters", "track": "Walk", "year": 2011},
    {"artist": "Fall Out Boy", "track": "My Songs Know What You Did in the Dark", "year": 2013},
    {"artist": "Arctic Monkeys", "track": "Do I Wanna Know?", "year": 2013},
    {"artist": "Muse", "track": "Madness", "year": 2012},
    {"artist": "The Black Keys", "track": "Lonely Boy", "year": 2011},
    {"artist": "Kings of Leon", "track": "Waste a Moment", "year": 2016},
    {"artist": "Panic! at the Disco", "track": "High Hopes", "year": 2018},
    {"artist": "Portugal. The Man", "track": "Feel It Still", "year": 2017},
    {"artist": "Cage the Elephant", "track": "Ain't No Rest for the Wicked", "year": 2011},
    {"artist": "Royal Blood", "track": "Figure It Out", "year": 2014},
    {"artist": "Greta Van Fleet", "track": "Highway Tune", "year": 2017},
    {"artist": "Bring Me the Horizon", "track": "Can You Feel My Heart", "year": 2015},
    {"artist": "Nothing but Thieves", "track": "Amsterdam", "year": 2018},
    {"artist": "Judah & the Lion", "track": "Suit and Jacket", "year": 2016},
    {"artist": "Walk the Moon", "track": "Shut Up and Dance", "year": 2014},
    {"artist": "The Lumineers", "track": "Ho Hey", "year": 2012},
    {"artist": "Mumford & Sons", "track": "I Will Wait", "year": 2012},
    {"artist": "Bastille", "track": "Pompeii", "year": 2013},
    {"artist": "AWOLNATION", "track": "Sail", "year": 2011},
    {"artist": "X Ambassadors", "track": "Renegades", "year": 2015},
    # 2020
    {"artist": "Glass Animals", "track": "Heat Waves", "year": 2020},
    {"artist": "Machine Gun Kelly", "track": "Bloody Valentine", "year": 2020},
    {"artist": "Fontaines D.C.", "track": "A Hero's Death", "year": 2020},
    {"artist": "The Strokes", "track": "Bad Decisions", "year": 2020},
    {"artist": "AC/DC", "track": "Shot in the Dark", "year": 2020},
)

BLUES_CLASSICS: tuple[dict, ...] = (
    # 1950s
    {"artist": "Muddy Waters", "track": "Hoochie Coochie Man", "year": 1954},
    {"artist": "Muddy Waters", "track": "I Just Want to Make Love to You", "year": 1954},
    {"artist": "Muddy Waters", "track": "Mannish Boy", "year": 1955},
    {"artist": "Howlin' Wolf", "track": "Evil", "year": 1954},
    {"artist": "Howlin' Wolf", "track": "Smokestack Lightnin'", "year": 1956},
    {"artist": "B.B. King", "track": "Three O'Clock Blues", "year": 1951},
    {"artist": "B.B. King", "track": "Every Day I Have the Blues", "year": 1955},
    {"artist": "Elmore James", "track": "Dust My Broom", "year": 1951},
    {"artist": "Big Mama Thornton", "track": "Hound Dog", "year": 1952},
    {"artist": "Little Walter", "track": "Juke", "year": 1952},
    {"artist": "Little Walter", "track": "My Babe", "year": 1955},
    {"artist": "Ray Charles", "track": "I Got a Woman", "year": 1954},
    {"artist": "Ray Charles", "track": "What'd I Say", "year": 1959},
    {"artist": "Bo Diddley", "track": "Bo Diddley", "year": 1955},
    {"artist": "Screamin' Jay Hawkins", "track": "I Put a Spell on You", "year": 1956},
    {"artist": "Jimmy Reed", "track": "Baby What You Want Me to Do", "year": 1959},
    {"artist": "Guitar Slim", "track": "The Things That I Used to Do", "year": 1954},
    {"artist": "Willie Dixon", "track": "Little Red Rooster", "year": 1961},
    # 1960s
    {"artist": "Etta James", "track": "At Last", "year": 1960},
    {"artist": "Etta James", "track": "I'd Rather Go Blind", "year": 1968},
    {"artist": "Howlin' Wolf", "track": "Spoonful", "year": 1960},
    {"artist": "Howlin' Wolf", "track": "Killing Floor", "year": 1964},
    {"artist": "John Lee Hooker", "track": "Boom Boom", "year": 1962},
    {"artist": "Freddie King", "track": "Hide Away", "year": 1961},
    {"artist": "Buddy Guy", "track": "Stone Crazy", "year": 1962},
    {"artist": "Junior Wells", "track": "Messin' with the Kid", "year": 1960},
    {"artist": "B.B. King", "track": "Sweet Little Angel", "year": 1964},
    {"artist": "Albert King", "track": "Born Under a Bad Sign", "year": 1967},
    {"artist": "Albert King", "track": "Crosscut Saw", "year": 1967},
    {"artist": "Paul Butterfield Blues Band", "track": "Born in Chicago", "year": 1965},
    {"artist": "John Mayall & the Bluesbreakers", "track": "All Your Love", "year": 1966},
    {"artist": "Cream", "track": "Crossroads", "year": 1968},
    {"artist": "Cream", "track": "Born Under a Bad Sign", "year": 1968},
    {"artist": "Jimi Hendrix", "track": "Red House", "year": 1967},
    {"artist": "Canned Heat", "track": "On the Road Again", "year": 1968},
    {"artist": "Fleetwood Mac", "track": "Black Magic Woman", "year": 1968},
    {"artist": "Fleetwood Mac", "track": "Oh Well", "year": 1969},
    {"artist": "Led Zeppelin", "track": "You Shook Me", "year": 1969},
    {"artist": "Janis Joplin", "track": "Ball and Chain", "year": 1968},
    {"artist": "Ten Years After", "track": "I'm Going Home", "year": 1969},
    {"artist": "Taj Mahal", "track": "Statesboro Blues", "year": 1968},
    {"artist": "Otis Rush", "track": "I Can't Quit You Baby", "year": 1966},
    {"artist": "Magic Sam", "track": "All Your Love", "year": 1967},
    # 1970s
    {"artist": "B.B. King", "track": "The Thrill Is Gone", "year": 1970},
    {"artist": "The Allman Brothers Band", "track": "Statesboro Blues", "year": 1971},
    {"artist": "The Allman Brothers Band", "track": "Whipping Post", "year": 1971},
    {"artist": "Derek and the Dominos", "track": "Layla", "year": 1970},
    {"artist": "Freddie King", "track": "Going Down", "year": 1971},
    {"artist": "Johnny Winter", "track": "Highway 61 Revisited", "year": 1970},
    {"artist": "ZZ Top", "track": "La Grange", "year": 1973},
    {"artist": "ZZ Top", "track": "Tush", "year": 1975},
    {"artist": "Bobby Bland", "track": "Ain't No Love in the Heart of the City", "year": 1974},
    {"artist": "Albert Collins", "track": "Frosty", "year": 1978},
    {"artist": "Rory Gallagher", "track": "Bullfrog Blues", "year": 1972},
    {"artist": "George Thorogood", "track": "One Bourbon, One Scotch, One Beer", "year": 1977},
    {"artist": "The J. Geils Band", "track": "Whammer Jammer", "year": 1972},
    {"artist": "Little Feat", "track": "Dixie Chicken", "year": 1973},
    {"artist": "Eric Clapton", "track": "Cocaine", "year": 1977},
    {"artist": "Muddy Waters", "track": "I'm Ready", "year": 1978},
    {"artist": "Peter Green", "track": "In the Skies", "year": 1979},
    # 1980s
    {"artist": "Stevie Ray Vaughan", "track": "Pride and Joy", "year": 1983},
    {"artist": "Stevie Ray Vaughan", "track": "Texas Flood", "year": 1983},
    {"artist": "Stevie Ray Vaughan", "track": "Cold Shot", "year": 1984},
    {"artist": "Stevie Ray Vaughan", "track": "Crossfire", "year": 1989},
    {"artist": "George Thorogood", "track": "Bad to the Bone", "year": 1982},
    {"artist": "Robert Cray", "track": "Smoking Gun", "year": 1986},
    {"artist": "Robert Cray", "track": "Phone Booth", "year": 1983},
    {"artist": "The Fabulous Thunderbirds", "track": "Tuff Enuff", "year": 1986},
    {"artist": "John Lee Hooker", "track": "The Healer", "year": 1989},
    {"artist": "Bonnie Raitt", "track": "Thing Called Love", "year": 1989},
    {"artist": "Gary Moore", "track": "Oh Pretty Woman", "year": 1990},
    {"artist": "Albert Collins", "track": "Same Old Thing", "year": 1986},
    # 1990s
    {"artist": "Gary Moore", "track": "Still Got the Blues", "year": 1990},
    {"artist": "Buddy Guy", "track": "Damn Right, I've Got the Blues", "year": 1991},
    {"artist": "Bonnie Raitt", "track": "I Can't Make You Love Me", "year": 1991},
    {"artist": "Eric Clapton", "track": "Tears in Heaven", "year": 1992},
    {"artist": "Eric Clapton", "track": "Change the World", "year": 1996},
    {"artist": "Keb' Mo'", "track": "Am I Wrong", "year": 1994},
    {"artist": "Jonny Lang", "track": "Lie to Me", "year": 1997},
    {"artist": "Kenny Wayne Shepherd", "track": "Blue on Black", "year": 1997},
    {"artist": "Susan Tedeschi", "track": "It Hurt So Bad", "year": 1998},
    {"artist": "Ben Harper", "track": "Ground on Down", "year": 1997},
    {"artist": "John Lee Hooker", "track": "Chill Out", "year": 1995},
    {"artist": "Corey Harris", "track": "Between Midnight and Day", "year": 1995},
    # 2000s
    {"artist": "The White Stripes", "track": "Ball and Biscuit", "year": 2003},
    {"artist": "The Black Keys", "track": "Thickfreakness", "year": 2003},
    {"artist": "The Black Keys", "track": "Your Touch", "year": 2006},
    {"artist": "Joe Bonamassa", "track": "Sloe Gin", "year": 2007},
    {"artist": "North Mississippi Allstars", "track": "Shake 'Em On Down", "year": 2000},
    {"artist": "The Derek Trucks Band", "track": "Down in the Flood", "year": 2002},
    {"artist": "Susan Tedeschi", "track": "Alone", "year": 2002},
    {"artist": "Seasick Steve", "track": "Dog House Boogie", "year": 2006},
    {"artist": "Buddy Guy", "track": "Skin Deep", "year": 2008},
    {"artist": "Eric Clapton", "track": "Riding with the King", "year": 2000},
    # 2010s–2020
    {"artist": "Gary Clark Jr.", "track": "Bright Lights", "year": 2011},
    {"artist": "Gary Clark Jr.", "track": "This Land", "year": 2019},
    {"artist": "Joe Bonamassa", "track": "Dust Bowl", "year": 2011},
    {"artist": "Tedeschi Trucks Band", "track": "Midnight in Harlem", "year": 2011},
    {"artist": "Rival Sons", "track": "Keep On Swinging", "year": 2011},
    {"artist": "Larkin Poe", "track": "Preachin' Blues", "year": 2018},
    {"artist": "Christone \"Kingfish\" Ingram", "track": "Outside of This Town", "year": 2019},
    {"artist": "Fantastic Negrito", "track": "Plastic Hamburgers", "year": 2018},
    {"artist": "Marcus King", "track": "The Well", "year": 2020},
    {"artist": "Samantha Fish", "track": "Bulletproof", "year": 2017},
)


# ---------- קטגוריות ----------

# קטגוריות העשורים מגיעות מנתוני מצעד אמיתיים (`chart_data.DECADE_HITS`,
# נוצר מ-Billboard Hot 100 ההיסטורי) ולא מהרשימות האצורות כאן: לרשימה
# שנכתבה מהזיכרון אין מדד ל"כמה השיר מוכר", וזו הייתה התלונה. הז'אנרים
# נשארים אצורים — ל-Hot 100 אין שדה ז'אנר, ובלוז כמעט לא מצעד בו.
ALL_CLASSICS: tuple[dict, ...] = POP_CLASSICS + ROCK_CLASSICS + BLUES_CLASSICS


def in_years(entries: tuple, first: int, last: int) -> tuple:
    return tuple(entry for entry in entries if first <= entry["year"] <= last)


def cap_by_artist(entries: tuple, limit: int = 2) -> tuple:
    """לכל היותר `limit` שירים לאמן, בשמירה על סדר הקלט.

    בלי זה 53%–64% מהשירים בכל רשימת ז'אנר שייכים לאמנים שחוזרים בה —
    חמישה שירים של Led Zeppelin ברוק, חמישה של Whitney Houston בפופ.
    זה סינון תצוגה: השיר נשאר בקוד, פשוט לא נדחס לאותה קטגוריה.
    """
    kept, seen = [], {}
    for entry in entries:
        name = entry["artist"].strip().casefold()
        if seen.get(name, 0) >= limit:
            continue
        seen[name] = seen.get(name, 0) + 1
        kept.append(entry)
    return tuple(kept)


# הגבולות אינם שרירותיים אלא פורמטי רדיו מקובלים: "אולדיס" הוא 50s–60s,
# "רוק קלאסי" הוא הרוק שבין הפלישה הבריטית לגראנג', ו"פופ קלאסי" הוא הפופ
# שלפני עידן ה-CD. מי שרוצה חתך אחר יכול לבחור עשור ישירות.
#
# ה-Hot 100 מתחיל באוגוסט 1958, ולכן 1950–1957 מגיעות מהרשימות האצורות
# ומשלימות את עשור ה-50 ואת "אולדיס".
_PRE_HOT100 = in_years(ALL_CLASSICS, 1950, 1957)

CATEGORIES: dict[str, tuple] = {
    "Pop": cap_by_artist(POP_CLASSICS),
    "Rock": cap_by_artist(ROCK_CLASSICS),
    "Blues": cap_by_artist(BLUES_CLASSICS),
    "Classic pop": cap_by_artist(in_years(POP_CLASSICS, 1950, 1989)),
    "Classic rock": cap_by_artist(in_years(ROCK_CLASSICS, 1965, 1995)),
    "Oldies": cap_by_artist(
        _PRE_HOT100 + chart_data.DECADE_HITS["50's"] + chart_data.DECADE_HITS["60's"]),
    "50's": cap_by_artist(_PRE_HOT100 + chart_data.DECADE_HITS["50's"]),
    "60's": chart_data.DECADE_HITS["60's"],
    "70's": chart_data.DECADE_HITS["70's"],
    "80's": chart_data.DECADE_HITS["80's"],
    "90's": chart_data.DECADE_HITS["90's"],
    "2000's": chart_data.DECADE_HITS["2000's"],
    "2010's": chart_data.DECADE_HITS["2010's"],
}


# Billboard, "The 500 Best Pop Songs" (10/19/2023) — https://www.billboard.com/
# lists/best-pop-songs-all-time-hits/. רשימה מדורגת שאינה נגזרת מה-Hot 100 עצמו
# (chart_data), ולכן לא סובלת מהטיית-אורך-שהייה שגזרה שם שנים שלמות: כל שיר
# 500-1 מדורג בעצמו, לא לפי ביצועים במצעד. שנת השיא נלקחה מ"Hot 100 Peak" בכתבה
# (כשהופיע) או מהתאריך הידוע של השיר. סדר: 500 (הכי חלש ברשימה) עד 1 (הטוב ביותר).
BILLBOARD_500_POP: tuple[dict, ...] = (
    {"artist": "Los Del Rio", "track": "Macarena (Bayside Boys Mix)", "year": 1996},
    {"artist": "New Kids on the Block", "track": "You Got It (The Right Stuff)", "year": 1989},
    {"artist": "Cherrelle with Alexander O'Neal", "track": "Saturday Love", "year": 1986},
    {"artist": "Toni Basil", "track": "Mickey", "year": 1982},
    {"artist": "Connie Francis", "track": "Stupid Cupid", "year": 1958},
    {"artist": "Demi Lovato", "track": "Give Your Heart a Break", "year": 2012},
    {"artist": "Tommy Tutone", "track": "867-5309/Jenny", "year": 1982},
    {"artist": "Pharrell feat. Jay-Z", "track": "Frontin'", "year": 2003},
    {"artist": "Irene Cara", "track": "Flashdance... What a Feeling", "year": 1983},
    {"artist": "Lil Kim feat. Lil Cease", "track": "Crush on You", "year": 1997},
    {"artist": "Berlin", "track": "Take My Breath Away", "year": 1986},
    {"artist": "Alice Deejay", "track": "Better Off Alone", "year": 2000},
    {"artist": "Ella Mai", "track": "Boo'd Up", "year": 2018},
    {"artist": "The Dave Clark Five", "track": "Glad All Over", "year": 1964},
    {"artist": "Pretenders", "track": "Back on the Chain Gang", "year": 1983},
    {"artist": "Tony Bennett", "track": "I Left My Heart in San Francisco", "year": 1962},
    {"artist": "Real McCoy", "track": "Another Night", "year": 1994},
    {"artist": "The Romantics", "track": "What I Like About You", "year": 1980},
    {"artist": "Ciara feat. Petey Pablo", "track": "Goodies", "year": 2004},
    {"artist": "The Shangri-Las", "track": "Give Him a Great Big Kiss", "year": 1965},
    {"artist": "First Class", "track": "Beach Baby", "year": 1974},
    {"artist": "Debbie Gibson", "track": "Only in My Dreams", "year": 1987},
    {"artist": "Little Anthony and the Imperials", "track": "Tears on My Pillow", "year": 1958},
    {"artist": "Biz Markie", "track": "Just a Friend", "year": 1990},
    {"artist": "Nina Sky feat. Jibbs", "track": "Move Ya Body", "year": 2004},
    {"artist": "Right Said Fred", "track": "I'm Too Sexy", "year": 1992},
    {"artist": "Darlene Love", "track": "Christmas (Baby Please Come Home)", "year": 2022},
    {"artist": "Roddy Ricch", "track": "The Box", "year": 2020},
    {"artist": "Badfinger", "track": "No Matter What", "year": 1970},
    {"artist": "En Vogue", "track": "My Lovin' (You're Never Gonna Get It)", "year": 1992},
    {"artist": "Harold Melvin and the Blue Notes", "track": "The Love I Lost", "year": 1973},
    {"artist": "Usher", "track": "You Make Me Wanna…", "year": 1997},
    {"artist": "Luther Vandross", "track": "Never Too Much", "year": 1981},
    {"artist": "Cam'Ron feat. Juelz Santana, Freekey Zekey & Toya", "track": "Hey Ma", "year": 2002},
    {"artist": "Roxette", "track": "It Must Have Been Love", "year": 1990},
    {"artist": "Ohio Express", "track": "Yummy Yummy Yummy", "year": 1968},
    {"artist": "Billy Ray Cyrus", "track": "Achy Breaky Heart", "year": 1992},
    {"artist": "Cassie", "track": "Me & U", "year": 2006},
    {"artist": "Rob Base & DJ EZ-Rock", "track": "It Takes Two", "year": 1988},
    {"artist": "Stan Getz & Joao Gilberto", "track": "The Girl From Ipanema", "year": 1964},
    {"artist": "Bobby Brown", "track": "My Prerogative", "year": 1989},
    {"artist": "J Balvin & Willy William", "track": "Mi Gente", "year": 2017},
    {"artist": "The Angels", "track": "My Boyfriend's Back", "year": 1963},
    {"artist": "Olivia Newton-John", "track": "Physical", "year": 1981},
    {"artist": "Nelly Furtado feat. Timbaland", "track": "Promiscuous", "year": 2006},
    {"artist": "The Kid LAROI & Justin Bieber", "track": "Stay", "year": 2021},
    {"artist": "Dawn Penn", "track": "You Don't Love Me (No, No, No)", "year": 1994},
    {"artist": "New Radicals", "track": "You Get What You Give", "year": 1999},
    {"artist": "Todd Rundgren", "track": "I Saw the Light", "year": 1972},
    {"artist": "Clean Bandit feat. Jess Glynne", "track": "Rather Be", "year": 2014},
    {"artist": "The Outfield", "track": "Your Love", "year": 1986},
    {"artist": "Tyga", "track": "Rack City", "year": 2012},
    {"artist": "Laura Branigan", "track": "Gloria", "year": 1982},
    {"artist": "CeCe Peniston", "track": "Finally", "year": 1992},
    {"artist": "Modern English", "track": "I Melt With You", "year": 1983},
    {"artist": "Flo Rida feat. T-Pain", "track": "Low", "year": 2008},
    {"artist": "Sister Sledge", "track": "We Are Family", "year": 1979},
    {"artist": "Billy Joel", "track": "Uptown Girl", "year": 1983},
    {"artist": "House of Pain", "track": "Jump Around", "year": 1992},
    {"artist": "Janet Jackson", "track": "All for You", "year": 2001},
    {"artist": "Aretha Franklin", "track": "(You Make Me Feel Like) A Natural Woman", "year": 1967},
    {"artist": "Toni Braxton", "track": "You're Makin' Me High", "year": 1996},
    {"artist": "Joe Jackson", "track": "Is She Really Going Out With Him?", "year": 1979},
    {"artist": "Maroon 5", "track": "This Love", "year": 2004},
    {"artist": "Diana Ross", "track": "I'm Coming Out", "year": 1980},
    {"artist": "The 5th Dimension", "track": "Aquarius/Let the Sunshine In", "year": 1969},
    {"artist": "Walk the Moon", "track": "Shut Up and Dance", "year": 2015},
    {"artist": "Ice Cube", "track": "It Was a Good Day", "year": 1993},
    {"artist": "Thelma Houston", "track": "Don't Leave Me This Way", "year": 1977},
    {"artist": "Spiral Starecase", "track": "More Today Than Yesterday", "year": 1969},
    {"artist": "Dionne Warwick", "track": "I Say a Little Prayer", "year": 1967},
    {"artist": "LEN", "track": "Steal My Sunshine", "year": 1999},
    {"artist": "Sylvester", "track": "You Make Me Feel (Mighty Real)", "year": 1979},
    {"artist": "Jordin Sparks & Chris Brown", "track": "No Air", "year": 2008},
    {"artist": "Chief Keef feat. Lil Reese", "track": "I Don't Like", "year": 2012},
    {"artist": "Kim Carnes", "track": "Bette Davis Eyes", "year": 1981},
    {"artist": "Candi Staton", "track": "Young Hearts Run Free", "year": 1976},
    {"artist": "t.A.T.u.", "track": "All the Things She Said", "year": 2003},
    {"artist": "Alicia Keys", "track": "If I Ain't Got You", "year": 2004},
    {"artist": "The Righteous Brothers", "track": "You've Lost That Lovin' Feelin'", "year": 1965},
    {"artist": "Ike & Tina Turner", "track": "Proud Mary", "year": 1971},
    {"artist": "Bonnie Raitt", "track": "Something to Talk About", "year": 1991},
    {"artist": "Lana Del Rey vs. Cedric Gervais", "track": "Summertime Sadness", "year": 2013},
    {"artist": "Shannon", "track": "Let the Music Play", "year": 1984},
    {"artist": "Edison Lighthouse", "track": "Love Grows (Where My Rosemary Goes)", "year": 1970},
    {"artist": "Marc Cohn", "track": "Walking in Memphis", "year": 1991},
    {"artist": "Bananarama", "track": "Cruel Summer", "year": 1984},
    {"artist": "Daryl Hall & John Oates", "track": "She's Gone", "year": 1976},
    {"artist": "Snoop Dogg feat. Pharrell", "track": "Drop It Like It's Hot", "year": 2004},
    {"artist": "Labelle", "track": "Lady Marmalade", "year": 1975},
    {"artist": "The Marvelettes", "track": "Please Mr. Postman", "year": 1961},
    {"artist": "Donna Summer", "track": "Bad Girls", "year": 1979},
    {"artist": "Donna Lewis", "track": "I Love You Always Forever", "year": 1996},
    {"artist": "Wizkid feat. Tems", "track": "Essence", "year": 2021},
    {"artist": "LL Cool J", "track": "Mama Said Knock You Out", "year": 1991},
    {"artist": "Sheryl Crow", "track": "All I Wanna Do", "year": 1994},
    {"artist": "Odyssey", "track": "Native New Yorker", "year": 1978},
    {"artist": "Martha & The Vandellas", "track": "Dancing in the Street", "year": 1964},
    {"artist": "C+C Music Factory", "track": "Gonna Make You Sweat (Everybody Dance Now)", "year": 1991},
    {"artist": "Fountains of Wayne", "track": "Stacy's Mom", "year": 2003},
    {"artist": "Belinda Carlisle", "track": "Heaven Is a Place on Earth", "year": 1987},
    {"artist": "Stevie Wonder", "track": "My Cherie Amour", "year": 1969},
    {"artist": "Jean Knight", "track": "Mr. Big Stuff", "year": 1971},
    {"artist": "Bobby Darin", "track": "Beyond the Sea", "year": 1960},
    {"artist": "Pitbull feat. Ne-Yo, Afrojack & Nayer", "track": "Give Me Everything", "year": 2011},
    {"artist": "Chaka Khan", "track": "I Feel for You", "year": 1984},
    {"artist": "Nelly", "track": "Country Grammar (Hot Shit)", "year": 2000},
    {"artist": "Tom Jones", "track": "It's Not Unusual", "year": 1965},
    {"artist": "5 Seconds of Summer", "track": "She Looks So Perfect", "year": 2014},
    {"artist": "Chic", "track": "Le Freak", "year": 1978},
    {"artist": "Everly Brothers", "track": "All I Have to Do Is Dream", "year": 1958},
    {"artist": "Lisa Loeb", "track": "Stay (I Missed You)", "year": 1994},
    {"artist": "Johnny Cash", "track": "Ring of Fire", "year": 1963},
    {"artist": "Cardi B, J Balvin & Bad Bunny", "track": "I Like It", "year": 2018},
    {"artist": "Cher", "track": "If I Could Turn Back Time", "year": 1989},
    {"artist": "Jonas Brothers", "track": "Burnin' Up", "year": 2008},
    {"artist": "Tom Tom Club", "track": "Genius of Love", "year": 1981},
    {"artist": "Big Punisher feat. Joe", "track": "Still Not a Player", "year": 1998},
    {"artist": "Bay City Rollers", "track": "Saturday Night", "year": 1976},
    {"artist": "Carrie Underwood", "track": "Before He Cheats", "year": 2007},
    {"artist": "BTS", "track": "Dynamite", "year": 2020},
    {"artist": "New Order", "track": "Bizarre Love Triangle", "year": 1986},
    {"artist": "Katrina and the Waves", "track": "Walking on Sunshine", "year": 1985},
    {"artist": "Eagles", "track": "One of These Nights", "year": 1975},
    {"artist": "Selena", "track": "Dreaming of You", "year": 1995},
    {"artist": "Dion", "track": "Runaround Sue", "year": 1961},
    {"artist": "Salt-n-Pepa", "track": "Push It", "year": 1987},
    {"artist": "A Flock of Seagulls", "track": "I Ran (So Far Away)", "year": 1982},
    {"artist": "The Notorious B.I.G.", "track": "Big Poppa", "year": 1995},
    {"artist": "Queen", "track": "Crazy Little Thing Called Love", "year": 1980},
    {"artist": "Adina Howard", "track": "Freak Like Me", "year": 1995},
    {"artist": "P!nk", "track": "Raise Your Glass", "year": 2010},
    {"artist": "Rihanna feat. Drake", "track": "Work", "year": 2016},
    {"artist": "Lil Wayne feat. Static Major", "track": "Lollipop", "year": 2008},
    {"artist": "The Partridge Family", "track": "I Think I Love You", "year": 1970},
    {"artist": "Blink-182", "track": "All the Small Things", "year": 2000},
    {"artist": "Taylor Swift", "track": "Anti-Hero", "year": 2022},
    {"artist": "Elvis Presley", "track": "Suspicious Minds", "year": 1969},
    {"artist": "Prince and the Revolution", "track": "Raspberry Beret", "year": 1985},
    {"artist": "Paula Abdul", "track": "Straight Up", "year": 1988},
    {"artist": "Lil Jon & The East Side Boyz feat. Ying Yang Twins", "track": "Get Low", "year": 2003},
    {"artist": "James Brown and the Famous Flames", "track": "I Got You (I Feel Good)", "year": 1965},
    {"artist": "John Denver", "track": "Take Me Home, Country Roads", "year": 1971},
    {"artist": "The Box Tops", "track": "The Letter", "year": 1967},
    {"artist": "Etta James", "track": "At Last", "year": 1961},
    {"artist": "Gnarls Barkley", "track": "Crazy", "year": 2006},
    {"artist": "Gin Blossoms", "track": "Hey Jealousy", "year": 1993},
    {"artist": "Lesley Gore", "track": "It's My Party", "year": 1963},
    {"artist": "Calvin Harris feat. Frank Ocean & Migos", "track": "Slide", "year": 2017},
    {"artist": "Arthur Conley", "track": "Sweet Soul Music", "year": 1967},
    {"artist": "New Edition", "track": "Candy Girl", "year": 1983},
    {"artist": "R.E.M.", "track": "Losing My Religion", "year": 1991},
    {"artist": "Fergie feat. Ludacris", "track": "Glamorous", "year": 2007},
    {"artist": "Kris Kross", "track": "Jump", "year": 1992},
    {"artist": "Isley Brothers", "track": "That Lady", "year": 1973},
    {"artist": "B.J. Thomas", "track": "Raindrops Keep Fallin' on My Head", "year": 1969},
    {"artist": "Avicii", "track": "Levels", "year": 2012},
    {"artist": "Yvonne Elliman", "track": "If I Can't Have You", "year": 1978},
    {"artist": "Fatboy Slim", "track": "Praise You", "year": 1999},
    {"artist": "Sean Paul", "track": "Get Busy", "year": 2003},
    {"artist": "Simple Minds", "track": "Don't You (Forget About Me)", "year": 1985},
    {"artist": "Smash Mouth", "track": "All Star", "year": 1999},
    {"artist": "Taio Cruz", "track": "Dynamite", "year": 2010},
    {"artist": "The Captain & Tennille", "track": "Love Will Keep Us Together", "year": 1975},
    {"artist": "Lisa Lisa & Cult Jam with Full Force", "track": "I Wonder If I Take You Home", "year": 1985},
    {"artist": "Megan Thee Stallion feat. Beyoncé", "track": "Savage Remix", "year": 2020},
    {"artist": "The Emotions", "track": "Best of My Love", "year": 1977},
    {"artist": "Natalie Imbruglia", "track": "Torn", "year": 1998},
    {"artist": "Carl Carlton", "track": "Everlasting Love", "year": 1974},
    {"artist": "Sonny & Cher", "track": "I Got You Babe", "year": 1965},
    {"artist": "Jack Ü with Justin Bieber", "track": "Where Are Ü Now", "year": 2015},
    {"artist": "Def Leppard", "track": "Photograph", "year": 1983},
    {"artist": "Ed Sheeran", "track": "Thinking Out Loud", "year": 2014},
    {"artist": "Sir Mix-a-Lot", "track": "Baby Got Back", "year": 1992},
    {"artist": "Divinyls", "track": "I Touch Myself", "year": 1991},
    {"artist": "Lady A", "track": "Need You Now", "year": 2010},
    {"artist": "KC and the Sunshine Band", "track": "Boogie Shoes", "year": 1976},
    {"artist": "Dusty Springfield", "track": "I Only Want to Be With You", "year": 1964},
    {"artist": "Eve feat. Gwen Stefani", "track": "Let Me Blow Ya Mind", "year": 2001},
    {"artist": "Katy Perry", "track": "Hot N Cold", "year": 2008},
    {"artist": "Eminem", "track": "My Name Is", "year": 1999},
    {"artist": "10cc", "track": "I'm Not in Love", "year": 1975},
    {"artist": "Mark Morrison", "track": "Return of the Mack", "year": 1997},
    {"artist": "Go-Go's", "track": "Our Lips Are Sealed", "year": 1981},
    {"artist": "Natalie Cole", "track": "This Will Be", "year": 1975},
    {"artist": "Jennifer Lopez feat. Styles P & Jadakiss", "track": "Jenny From the Block", "year": 2002},
    {"artist": "The J. Geils Band", "track": "Centerfold", "year": 1982},
    {"artist": "Jimmy Eat World", "track": "The Middle", "year": 2002},
    {"artist": "Wilson Phillips", "track": "Hold On", "year": 1990},
    {"artist": "DJ Khaled feat. T-Pain, Ludacris, Snoop Dogg & Rick Ross", "track": "All I Do Is Win", "year": 2010},
    {"artist": "The Association", "track": "Windy", "year": 1967},
    {"artist": "Gwen Stefani", "track": "Hollaback Girl", "year": 2005},
    {"artist": "Seal", "track": "Kiss From a Rose", "year": 1995},
    {"artist": "Marvin Gaye", "track": "I Heard It Through the Grapevine", "year": 1968},
    {"artist": "Jay-Z feat. UGK", "track": "Big Pimpin'", "year": 2000},
    {"artist": "Peter Gabriel", "track": "Sledgehammer", "year": 1986},
    {"artist": "The Drifters", "track": "Under the Boardwalk", "year": 1964},
    {"artist": "Isaac Hayes", "track": "Theme From 'Shaft'", "year": 1971},
    {"artist": "Plain White T's", "track": "Hey There Delilah", "year": 2007},
    {"artist": "Jackie Wilson", "track": "(Your Love Keeps Lifting Me) Higher and Higher", "year": 1967},
    {"artist": "Annie Lennox", "track": "Walking on Broken Glass", "year": 1992},
    {"artist": "Lil Uzi Vert", "track": "XO Tour Llif3", "year": 2017},
    {"artist": "Kool & The Gang", "track": "Celebration", "year": 1981},
    {"artist": "Lipps Inc.", "track": "Funkytown", "year": 1980},
    {"artist": "Commodores", "track": "Brick House", "year": 1977},
    {"artist": "Adele", "track": "Someone Like You", "year": 2011},
    {"artist": "Paramore", "track": "Still Into You", "year": 2013},
    {"artist": "Sly & The Family Stone", "track": "Everyday People", "year": 1969},
    {"artist": "Drake", "track": "Best I Ever Had", "year": 2009},
    {"artist": "La Roux", "track": "Bulletproof", "year": 2010},
    {"artist": "Bob Seger", "track": "Night Moves", "year": 1977},
    {"artist": "Ghost Town DJ's", "track": "My Boo", "year": 2016},
    {"artist": "The Beatles", "track": "Hey Jude", "year": 1968},
    {"artist": "The Police", "track": "Every Breath You Take", "year": 1983},
    {"artist": "Montell Jordan", "track": "This Is How We Do It", "year": 1995},
    {"artist": "John Mellencamp", "track": "Jack & Diane", "year": 1982},
    {"artist": "Blue Swede", "track": "Hooked on a Feeling", "year": 1974},
    {"artist": "Louis Armstrong", "track": "What a Wonderful World", "year": 1988},
    {"artist": "Shakira feat. Wyclef Jean", "track": "Hips Don't Lie", "year": 2006},
    {"artist": "Lizzo", "track": "Truth Hurts", "year": 2019},
    {"artist": "The Supremes", "track": "You Can't Hurry Love", "year": 1966},
    {"artist": "Celine Dion", "track": "My Heart Will Go On", "year": 1998},
    {"artist": "Freda Payne", "track": "Band of Gold", "year": 1970},
    {"artist": "Lionel Richie", "track": "All Night Long (All Night)", "year": 1983},
    {"artist": "Fun. feat. Janelle Monáe", "track": "We Are Young", "year": 2012},
    {"artist": "Tracy Chapman", "track": "Fast Car", "year": 1988},
    {"artist": "Cornelius Brothers & Sister Rose", "track": "Too Late to Turn Back Now", "year": 1972},
    {"artist": "Shaggy feat. Ricardo \"RikRok\" Ducent", "track": "It Wasn't Me", "year": 2001},
    {"artist": "Depeche Mode", "track": "Enjoy the Silence", "year": 1990},
    {"artist": "Enrique Iglesias feat. Descemer Bueno & Gente de Zona", "track": "Bailando", "year": 2014},
    {"artist": "Simon & Garfunkel", "track": "Mrs. Robinson", "year": 1968},
    {"artist": "Wham!", "track": "Wake Me Up Before You Go-Go", "year": 1984},
    {"artist": "Britney Spears", "track": "Oops!…I Did It Again", "year": 2000},
    {"artist": "TLC", "track": "Waterfalls", "year": 1995},
    {"artist": "Cheap Trick", "track": "I Want You to Want Me", "year": 1979},
    {"artist": "Migos feat. Lil Uzi Vert", "track": "Bad and Boujee", "year": 2017},
    {"artist": "America", "track": "Sister Golden Hair", "year": 1975},
    {"artist": "Mary J. Blige", "track": "Real Love", "year": 1992},
    {"artist": "DMX", "track": "Party Up (Up in Here)", "year": 2000},
    {"artist": "Dua Lipa", "track": "Levitating", "year": 2021},
    {"artist": "Bee Gees", "track": "How Deep Is Your Love", "year": 1977},
    {"artist": "JoJo", "track": "Leave (Get Out)", "year": 2004},
    {"artist": "Pointer Sisters", "track": "I'm So Excited", "year": 1984},
    {"artist": "Turtles", "track": "Happy Together", "year": 1967},
    {"artist": "Frank Ocean", "track": "Thinkin Bout You", "year": 2012},
    {"artist": "Disclosure feat. Sam Smith", "track": "Latch", "year": 2014},
    {"artist": "The Crystals", "track": "Then He Kissed Me", "year": 1963},
    {"artist": "Lauryn Hill", "track": "Doo-Wop (That Thing)", "year": 1998},
    {"artist": "The Foundations", "track": "Build Me Up Buttercup", "year": 1969},
    {"artist": "David Bowie", "track": "Modern Love", "year": 1983},
    {"artist": "John Travolta & Olivia Newton-John", "track": "You're the One That I Want", "year": 1978},
    {"artist": "Chubby Checker", "track": "The Twist", "year": 1960},
    {"artist": "Ray Charles", "track": "Hit the Road Jack", "year": 1961},
    {"artist": "Rae Sremmurd feat. Gucci Mane", "track": "Black Beatles", "year": 2016},
    {"artist": "Fall Out Boy", "track": "Sugar, We're Going Down", "year": 2005},
    {"artist": "The Rolling Stones", "track": "Miss You", "year": 1978},
    {"artist": "Rick Astley", "track": "Never Gonna Give You Up", "year": 1988},
    {"artist": "The Chicks", "track": "Goodbye Earl", "year": 2000},
    {"artist": "The Cardigans", "track": "Lovefool", "year": 1997},
    {"artist": "Daddy Yankee", "track": "Gasolina", "year": 2005},
    {"artist": "David Guetta feat. Sia", "track": "Titanium", "year": 2012},
    {"artist": "Salt-n-Pepa", "track": "Shoop", "year": 1993},
    {"artist": "Neneh Cherry", "track": "Buffalo Stance", "year": 1989},
    {"artist": "Psy", "track": "Gangnam Style", "year": 2012},
    {"artist": "Corinne Bailey Rae", "track": "Put Your Records On", "year": 2006},
    {"artist": "Beck", "track": "Loser", "year": 1994},
    {"artist": "Bruce Springsteen", "track": "Dancing in the Dark", "year": 1984},
    {"artist": "Temptations", "track": "Just My Imagination (Running Away With Me)", "year": 1971},
    {"artist": "Daryl Hall & John Oates", "track": "You Make My Dreams", "year": 1981},
    {"artist": "The Cure", "track": "Just Like Heaven", "year": 1988},
    {"artist": "Kanye West feat. Jamie Foxx", "track": "Gold Digger", "year": 2005},
    {"artist": "Whitney Houston", "track": "How Will I Know", "year": 1986},
    {"artist": "Christina Aguilera", "track": "Genie in a Bottle", "year": 1999},
    {"artist": "Petula Clark", "track": "Downtown", "year": 1965},
    {"artist": "Charli XCX", "track": "Boom Clap", "year": 2014},
    {"artist": "Avril Lavigne", "track": "Sk8er Boi", "year": 2002},
    {"artist": "The Lovin' Spoonful", "track": "Do You Believe in Magic", "year": 1965},
    {"artist": "Ace of Base", "track": "The Sign", "year": 1994},
    {"artist": "SZA", "track": "Kill Bill", "year": 2023},
    {"artist": "The Spinners", "track": "Could It Be I'm Falling in Love?", "year": 1973},
    {"artist": "Aqua", "track": "Barbie Girl", "year": 1997},
    {"artist": "Carole King", "track": "It's Too Late", "year": 1971},
    {"artist": "Soulja Boy", "track": "Crank That (Soulja Boy)", "year": 2007},
    {"artist": "Joni Mitchell", "track": "Big Yellow Taxi", "year": 1970},
    {"artist": "Janet Jackson", "track": "That's the Way Love Goes", "year": 1993},
    {"artist": "Electric Light Orchestra", "track": "Don't Bring Me Down", "year": 1979},
    {"artist": "The Chainsmokers feat. Halsey", "track": "Closer", "year": 2016},
    {"artist": "The Zombies", "track": "She's Not There", "year": 1964},
    {"artist": "Guns N' Roses", "track": "Sweet Child o' Mine", "year": 1988},
    {"artist": "Cascada", "track": "Everytime We Touch", "year": 2006},
    {"artist": "Ginuwine", "track": "Pony", "year": 1996},
    {"artist": "Michael Jackson", "track": "Beat It", "year": 1983},
    {"artist": "The Bangles", "track": "Manic Monday", "year": 1986},
    {"artist": "Kylie Minogue", "track": "Can't Get You Out of My Head", "year": 2002},
    {"artist": "Santana feat. Rob Thomas", "track": "Smooth", "year": 1999},
    {"artist": "Foreigner", "track": "I Want to Know What Love Is", "year": 1985},
    {"artist": "Estelle feat. Kanye West", "track": "American Boy", "year": 2008},
    {"artist": "Philip Bailey With Phil Collins", "track": "Easy Lover", "year": 1985},
    {"artist": "Bad Bunny", "track": "Tití Me Preguntó", "year": 2022},
    {"artist": "The Knack", "track": "My Sharona", "year": 1979},
    {"artist": "Van Halen", "track": "Jump", "year": 1984},
    {"artist": "Mariah Carey", "track": "We Belong Together", "year": 2005},
    {"artist": "? and the Mysterians", "track": "96 Tears", "year": 1966},
    {"artist": "Post Malone", "track": "Circles", "year": 2019},
    {"artist": "Duran Duran", "track": "Hungry Like the Wolf", "year": 1983},
    {"artist": "Nelly", "track": "Hot in Herre", "year": 2002},
    {"artist": "Boston", "track": "More Than a Feeling", "year": 1976},
    {"artist": "Barry Manilow", "track": "Copacabana", "year": 1978},
    {"artist": "No Doubt", "track": "Just a Girl", "year": 1996},
    {"artist": "Dolly Parton", "track": "9 to 5", "year": 1981},
    {"artist": "Smokey Robinson & The Miracles", "track": "The Tears of a Clown", "year": 1970},
    {"artist": "Pet Shop Boys", "track": "West End Girls", "year": 1986},
    {"artist": "Tommy James and the Shondells", "track": "Crimson and Clover", "year": 1969},
    {"artist": "Juice WRLD", "track": "Lucid Dreams", "year": 2018},
    {"artist": "Madonna", "track": "Vogue", "year": 1990},
    {"artist": "Boyz II Men", "track": "I'll Make Love to You", "year": 1994},
    {"artist": "Elton John", "track": "Bennie and the Jets", "year": 1974},
    {"artist": "Juvenile feat. Mannie Fresh & Lil Wayne", "track": "Back That Azz Up", "year": 1999},
    {"artist": "Sam Cooke", "track": "Wonderful World", "year": 1960},
    {"artist": "Raspberries", "track": "Go All the Way", "year": 1972},
    {"artist": "Ricky Martin", "track": "Livin' La Vida Loca", "year": 1999},
    {"artist": "Bill Withers", "track": "Ain't No Sunshine", "year": 1971},
    {"artist": "Steve Lacy", "track": "Bad Habit", "year": 2022},
    {"artist": "Daft Punk", "track": "One More Time", "year": 2001},
    {"artist": "Sia", "track": "Chandelier", "year": 2014},
    {"artist": "Run-D.M.C.", "track": "It's Tricky", "year": 1987},
    {"artist": "The Jackson 5", "track": "ABC", "year": 1970},
    {"artist": "Doja Cat", "track": "Say So", "year": 2020},
    {"artist": "Dexy's Midnight Runners", "track": "Come on Eileen", "year": 1983},
    {"artist": "Carpenters", "track": "(They Long to Be) Close to You", "year": 1970},
    {"artist": "Robin S.", "track": "Show Me Love", "year": 1993},
    {"artist": "The Kingsmen", "track": "Louie Louie", "year": 1963},
    {"artist": "*NSYNC", "track": "Tearin' Up My Heart", "year": 1998},
    {"artist": "Beyoncé", "track": "Love on Top", "year": 2011},
    {"artist": "Coolio", "track": "Gangsta's Paradise", "year": 1995},
    {"artist": "Johnny Nash", "track": "I Can See Clearly Now", "year": 1972},
    {"artist": "Don Henley", "track": "The Boys of Summer", "year": 1985},
    {"artist": "Icona Pop feat. Charli XCX", "track": "I Love It", "year": 2013},
    {"artist": "The Kinks", "track": "You Really Got Me", "year": 1964},
    {"artist": "Taylor Swift", "track": "Blank Space", "year": 2014},
    {"artist": "Tina Turner", "track": "What's Love Got to Do With It", "year": 1984},
    {"artist": "Cher", "track": "Believe", "year": 1999},
    {"artist": "T-Pain feat. Yung Joc", "track": "Buy U a Drank (Shawty Snappin')", "year": 2007},
    {"artist": "Blondie", "track": "Call Me", "year": 1980},
    {"artist": "Miley Cyrus", "track": "Wrecking Ball", "year": 2013},
    {"artist": "The Archies", "track": "Sugar, Sugar", "year": 1969},
    {"artist": "Martha and the Vandellas", "track": "Heat Wave", "year": 1963},
    {"artist": "Missy Elliott", "track": "Get Ur Freak On", "year": 2001},
    {"artist": "Nick Lowe", "track": "Cruel to Be Kind", "year": 1979},
    {"artist": "Frankie Valli", "track": "Can't Take My Eyes Off You", "year": 1967},
    {"artist": "Eminem", "track": "Lose Yourself", "year": 2002},
    {"artist": "Kesha", "track": "Tik Tok", "year": 2010},
    {"artist": "Four Tops", "track": "I Can't Help Myself", "year": 1965},
    {"artist": "The Doobie Brothers", "track": "What a Fool Believes", "year": 1979},
    {"artist": "Bon Jovi", "track": "Livin' on a Prayer", "year": 1987},
    {"artist": "Alanis Morissette", "track": "You Oughta Know", "year": 1995},
    {"artist": "Coldplay", "track": "Viva La Vida", "year": 2008},
    {"artist": "Cardi B", "track": "Bodak Yellow (Money Moves)", "year": 2017},
    {"artist": "Ritchie Valens", "track": "La Bamba", "year": 1959},
    {"artist": "Eurythmics", "track": "Sweet Dreams (Are Made of This)", "year": 1983},
    {"artist": "Carly Simon", "track": "You're So Vain", "year": 1973},
    {"artist": "Billie Eilish", "track": "Bad Guy", "year": 2019},
    {"artist": "Third Eye Blind", "track": "Semi-Charmed Life", "year": 1997},
    {"artist": "Elvis Presley", "track": "Can't Help Falling in Love", "year": 1962},
    {"artist": "Fugees", "track": "Killing Me Softly", "year": 1996},
    {"artist": "Beyoncé", "track": "Single Ladies (Put a Ring on It)", "year": 2008},
    {"artist": "The Miracles", "track": "The Tracks of My Tears", "year": 1965},
    {"artist": "Justin Timberlake", "track": "SexyBack", "year": 2006},
    {"artist": "Lil Nas X feat. Billy Ray Cyrus", "track": "Old Town Road (Remix)", "year": 2019},
    {"artist": "Don McLean", "track": "American Pie", "year": 1972},
    {"artist": "The Beach Boys", "track": "God Only Knows", "year": 1966},
    {"artist": "Dionne Warwick", "track": "Walk on By", "year": 1964},
    {"artist": "Madonna", "track": "Borderline", "year": 1984},
    {"artist": "Prince", "track": "Little Red Corvette", "year": 1983},
    {"artist": "Snoop Dogg", "track": "Gin and Juice", "year": 1994},
    {"artist": "Lady Gaga", "track": "Born This Way", "year": 2011},
    {"artist": "M.I.A.", "track": "Paper Planes", "year": 2008},
    {"artist": "Daft Punk feat. Pharrell", "track": "Get Lucky", "year": 2013},
    {"artist": "Harry Styles", "track": "As It Was", "year": 2022},
    {"artist": "Bonnie Tyler", "track": "Total Eclipse of the Heart", "year": 1983},
    {"artist": "Tom Petty", "track": "Free Fallin'", "year": 1990},
    {"artist": "The Rolling Stones", "track": "(I Can't Get No) Satisfaction", "year": 1965},
    {"artist": "Jay-Z feat. Alicia Keys", "track": "Empire State of Mind", "year": 2009},
    {"artist": "Neil Diamond", "track": "Sweet Caroline", "year": 1969},
    {"artist": "Cyndi Lauper", "track": "Time After Time", "year": 1984},
    {"artist": "Brandy & Monica", "track": "The Boy Is Mine", "year": 1998},
    {"artist": "INXS", "track": "Need You Tonight", "year": 1988},
    {"artist": "Michael Jackson", "track": "Don't Stop ‘Til You Get Enough", "year": 1979},
    {"artist": "The Cars", "track": "Just What I Needed", "year": 1978},
    {"artist": "Lorde", "track": "Royals", "year": 2013},
    {"artist": "Nirvana", "track": "Smells Like Teen Spirit", "year": 1992},
    {"artist": "Nancy Sinatra", "track": "These Boots Are Made for Walkin'", "year": 1966},
    {"artist": "Huey Lewis & The News", "track": "The Power of Love", "year": 1985},
    {"artist": "Rihanna feat. Calvin Harris", "track": "We Found Love", "year": 2011},
    {"artist": "Jimmy Buffett", "track": "Margaritaville", "year": 1977},
    {"artist": "Toto", "track": "Africa", "year": 1983},
    {"artist": "George Michael", "track": "Faith", "year": 1987},
    {"artist": "The Black Eyed Peas", "track": "I Gotta Feeling", "year": 2009},
    {"artist": "Marvin Gaye", "track": "What's Going On", "year": 1971},
    {"artist": "Sugarhill Gang", "track": "Rapper's Delight", "year": 1980},
    {"artist": "Del Shannon", "track": "Runaway", "year": 1961},
    {"artist": "LMFAO feat. Lauren Bennett & GoonRock", "track": "Party Rock Anthem", "year": 2011},
    {"artist": "The Flamingos", "track": "I Only Have Eyes for You", "year": 1959},
    {"artist": "Mariah Carey", "track": "All I Want for Christmas Is You", "year": 1994},
    {"artist": "Naughty by Nature", "track": "O.P.P.", "year": 1991},
    {"artist": "The Beatles", "track": "Yesterday", "year": 1965},
    {"artist": "Vanessa Carlton", "track": "A Thousand Miles", "year": 2002},
    {"artist": "Fetty Wap", "track": "Trap Queen", "year": 2015},
    {"artist": "Shania Twain", "track": "Man! I Feel Like a Woman!", "year": 1999},
    {"artist": "BLACKstreet feat. Dr. Dre", "track": "No Diggity", "year": 1996},
    {"artist": "The Killers", "track": "Mr. Brightside", "year": 2004},
    {"artist": "Justin Bieber feat. Ludacris", "track": "Baby", "year": 2010},
    {"artist": "Janet Jackson", "track": "Miss You Much", "year": 1989},
    {"artist": "Sinéad O'Connor", "track": "Nothing Compares 2 U", "year": 1990},
    {"artist": "One Direction", "track": "What Makes You Beautiful", "year": 2011},
    {"artist": "Destiny's Child", "track": "Say My Name", "year": 2000},
    {"artist": "Luis Fonsi & Daddy Yankee", "track": "Despacito", "year": 2017},
    {"artist": "Stevie Wonder", "track": "You Are the Sunshine of My Life", "year": 1973},
    {"artist": "The Human League", "track": "Don't You Want Me", "year": 1982},
    {"artist": "Drake", "track": "Hotline Bling", "year": 2015},
    {"artist": "Aaliyah", "track": "Are You That Somebody?", "year": 1998},
    {"artist": "The Weeknd", "track": "Blinding Lights", "year": 2020},
    {"artist": "Sade", "track": "Smooth Operator", "year": 1985},
    {"artist": "Fine Young Cannibals", "track": "She Drives Me Crazy", "year": 1989},
    {"artist": "Mark Ronson feat. Bruno Mars", "track": "Uptown Funk!", "year": 2015},
    {"artist": "Miley Cyrus", "track": "Party in the U.S.A.", "year": 2009},
    {"artist": "Gladys Knight & The Pips", "track": "Midnight Train to Georgia", "year": 1973},
    {"artist": "Amy Winehouse", "track": "Rehab", "year": 2007},
    {"artist": "Olivia Rodrigo", "track": "Drivers License", "year": 2021},
    {"artist": "Van Morrison", "track": "Brown Eyed Girl", "year": 1967},
    {"artist": "Natasha Bedingfield", "track": "Unwritten", "year": 2005},
    {"artist": "The Notorious B.I.G. feat. Mase & Diddy", "track": "Mo Money Mo Problems", "year": 1997},
    {"artist": "Deee-Lite", "track": "Groove Is in the Heart", "year": 1990},
    {"artist": "Paul McCartney & Wings", "track": "Silly Love Songs", "year": 1976},
    {"artist": "Ariana Grande", "track": "Thank U, Next", "year": 2018},
    {"artist": "The Monkees", "track": "I'm a Believer", "year": 1966},
    {"artist": "Four Seasons", "track": "December 1963 (Oh What a Night)", "year": 1976},
    {"artist": "Cyndi Lauper", "track": "Girls Just Want to Have Fun", "year": 1984},
    {"artist": "Ben E. King", "track": "Stand by Me", "year": 1961},
    {"artist": "Hanson", "track": "MMMBop", "year": 1997},
    {"artist": "Whitney Houston", "track": "I Will Always Love You", "year": 1992},
    {"artist": "Roy Orbison and the Candy Men", "track": "Oh, Pretty Woman", "year": 1964},
    {"artist": "50 Cent", "track": "In Da Club", "year": 2003},
    {"artist": "*NSYNC", "track": "Bye Bye Bye", "year": 2000},
    {"artist": "Bell Biv DeVoe", "track": "Poison", "year": 1990},
    {"artist": "Rick Springfield", "track": "Jessie's Girl", "year": 1981},
    {"artist": "Elton John", "track": "Your Song", "year": 1971},
    {"artist": "Britney Spears", "track": "Toxic", "year": 2004},
    {"artist": "The Mamas & The Papas", "track": "California Dreamin'", "year": 1966},
    {"artist": "Journey", "track": "Don't Stop Believin'", "year": 1981},
    {"artist": "Rihanna feat. Jay-Z", "track": "Umbrella", "year": 2007},
    {"artist": "Gotye feat. Kimbra", "track": "Somebody That I Used to Know", "year": 2012},
    {"artist": "Oasis", "track": "Wonderwall", "year": 1995},
    {"artist": "Blondie", "track": "Heart of Glass", "year": 1979},
    {"artist": "Soft Cell", "track": "Tainted Love", "year": 1982},
    {"artist": "Dr. Dre feat. Snoop Dogg", "track": "Nuthin' But a 'G' Thang", "year": 1993},
    {"artist": "Otis Redding", "track": "(Sittin' On) The Dock of the Bay", "year": 1968},
    {"artist": "Donna Summer", "track": "Last Dance", "year": 1978},
    {"artist": "Taylor Swift", "track": "You Belong With Me", "year": 2009},
    {"artist": "The B-52s", "track": "Love Shack", "year": 1989},
    {"artist": "Looking Glass", "track": "Brandy (You're a Fine Girl)", "year": 1972},
    {"artist": "George Michael", "track": "Freedom '90", "year": 1990},
    {"artist": "Katy Perry", "track": "Teenage Dream", "year": 2010},
    {"artist": "Marvin Gaye & Tammi Terrell", "track": "Ain't No Mountain High Enough", "year": 1967},
    {"artist": "Spice Girls", "track": "Wannabe", "year": 1997},
    {"artist": "Gloria Gaynor", "track": "I Will Survive", "year": 1979},
    {"artist": "Al Green", "track": "Let's Stay Together", "year": 1972},
    {"artist": "The Shirelles", "track": "Will You Love Me Tomorrow", "year": 1960},
    {"artist": "The Bee Gees", "track": "Stayin' Alive", "year": 1978},
    {"artist": "Usher feat. Lil Jon & Ludacris", "track": "Yeah!", "year": 2004},
    {"artist": "Adele", "track": "Rolling in the Deep", "year": 2011},
    {"artist": "The Supremes", "track": "Where Did Our Love Go", "year": 1964},
    {"artist": "Tears for Fears", "track": "Everybody Wants to Rule the World", "year": 1985},
    {"artist": "The Isley Brothers", "track": "Shout", "year": 1959},
    {"artist": "a-ha", "track": "Take on Me", "year": 1985},
    {"artist": "The Beach Boys", "track": "Good Vibrations", "year": 1966},
    {"artist": "Lady Gaga", "track": "Bad Romance", "year": 2009},
    {"artist": "Jackson 5", "track": "I Want You Back", "year": 1970},
    {"artist": "Missy Elliott", "track": "Work It", "year": 2002},
    {"artist": "Aretha Franklin", "track": "Respect", "year": 1967},
    {"artist": "TLC", "track": "No Scrubs", "year": 1999},
    {"artist": "The Ronettes", "track": "Be My Baby", "year": 1963},
    {"artist": "Beyoncé feat. Jay-Z", "track": "Crazy in Love", "year": 2003},
    {"artist": "Fleetwood Mac", "track": "Dreams", "year": 1977},
    {"artist": "Earth, Wind & Fire", "track": "September", "year": 1978},
    {"artist": "Mariah Carey", "track": "Fantasy", "year": 1995},
    {"artist": "OutKast", "track": "Hey Ya!", "year": 2003},
    {"artist": "Nicki Minaj", "track": "Super Bass", "year": 2011},
    {"artist": "Britney Spears", "track": "...Baby One More Time", "year": 1999},
    {"artist": "Prince and the Revolution", "track": "Kiss", "year": 1986},
    {"artist": "The Beatles", "track": "I Want to Hold Your Hand", "year": 1964},
    {"artist": "2Pac feat. Dr. Dre", "track": "California Love", "year": 1996},
    {"artist": "Carly Rae Jepsen", "track": "Call Me Maybe", "year": 2012},
    {"artist": "Michael Jackson", "track": "Billie Jean", "year": 1983},
    {"artist": "Madonna", "track": "Like a Prayer", "year": 1989},
    {"artist": "Kelly Clarkson", "track": "Since U Been Gone", "year": 2005},
    {"artist": "Backstreet Boys", "track": "I Want It That Way", "year": 1999},
    {"artist": "The Temptations", "track": "My Girl", "year": 1965},
    {"artist": "ABBA", "track": "Dancing Queen", "year": 1976},
    {"artist": "Whitney Houston", "track": "I Wanna Dance With Somebody (Who Loves Me)", "year": 1987},
)


# ---------- בריכת ההגרלה ----------

# פריטי מצעד מלפני 1960 אינם נכנסים לבריכה. ה-Hot 100 מתחיל באוגוסט
# 1958, ומה שיש שם הוא מילוי מצעד של שנה וחצי — Topsy II, Gotta Travel
# On, The Chipmunk Song — שאין לו גרסאות טריילר. הקלאסיקות האמיתיות של
# שנות ה-50 (Elvis, Jerry Lee Lewis) נכנסות דרך הרשימות האצורות.
POOL_FIRST_CHART_YEAR = 1960


def famous_pool() -> tuple[dict, ...]:
    """שירים מוכרים דיים שסביר שקיימות להם גרסאות קאבר — לכפתור ההגרלה.

    נבנית ממה שכבר קיים ולא מרשימה נוספת לתחזק: נתוני המצעד ועל גביהם
    רשימות הפופ והרוק האצורות. **בלוז לא נכנס** — הבקשה היא שיר שסביר
    שיש לו קאבר, ולתקליטי הבלוז שברשימה יש הרבה פחות גרסאות כאלה מאשר
    ללהיטי הפופ והרוק.

    **העשור נכנס במלואו.** קודם נלקחו 40 הראשונים מכל עשור, וזה נראה
    כמו "רק המוכרים" אבל לא היה: הרשימות מדורגות לפי ביצועים במצעד, ושיר
    מ-1981 שהה במצעד הרבה יותר זמן משיר מ-1988 — ולכן החיתוך מחק **שנים
    שלמות מסוף כל עשור**. 1986 עד 1989 נעדרו מהבריכה לחלוטין, וכך גם
    1965, 1974-75 ו-1991. מתוך 780 רשומות מצעד נכנסו 280 בלבד.

    גם ה-cap לאמן אינו חל כאן: הוא סינון תצוגה (ראו `cap_by_artist`),
    ובבריכה הוא רק מנע הגרלה של להיט שלישי של אמן שיש לו כאלה.

    **`BILLBOARD_500_POP`** מוסיפה מקור שלישי, בלתי תלוי ב-Hot 100: כל
    שיר ברשימה מדורג בעצמו (500 עד 1), לא לפי משך שהייה במצעד — ולכן אינו
    סובל מההטיה שגזרה שנים שלמות מ-`chart_data`. חפיפה עם המקורות האחרים
    מנופה בסוף הפונקציה כרגיל.
    """
    entries: list[dict] = []
    for decade in chart_data.DECADE_HITS.values():
        entries.extend(entry for entry in decade
                       if entry["year"] >= POOL_FIRST_CHART_YEAR)
    entries.extend(POP_CLASSICS)
    entries.extend(ROCK_CLASSICS)
    entries.extend(BILLBOARD_500_POP)

    unique, seen = [], set()
    for entry in entries:
        key = (entry["artist"].strip().casefold(), entry["track"].strip().casefold())
        if key in seen:
            continue
        seen.add(key)
        unique.append(entry)
    return tuple(unique)
