"""רגרסיה על מקרה The Crown: קאבר שהופק לסדרה ואין בכותרת שלו אף מילת מפתח.

Fort Nowhere & Emma Allaway — "Bittersweet Symphony", ℗ Netflix Music LLC, 2022.
הכותרת היא שם השיר בלבד. הסימן היחיד במטא-דאטה הוא ז'אנר Soundtrack, וקודם
הוא היה שווה 10 נקודות בלבד — כך שהגרסה נקברה בין עשרות קאברים.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import covers
import search
import youtube

QUERY = "Bittersweet Symphony"

CROWN = {
    "artist": "Fort Nowhere & Emma Allaway", "track": "Bittersweet Symphony",
    "album": "Bittersweet Symphony", "genre": "Soundtrack", "year": "2022",
    "preview_url": "http://p", "duration_sec": 240, "source": "iTunes", "uid": "crown",
}
VERVE = {
    "artist": "The Verve", "track": "Bitter Sweet Symphony", "album": "Urban Hymns",
    "genre": "Alternative", "year": "1997",
    "preview_url": "http://p", "duration_sec": 350, "source": "iTunes", "uid": "verve",
}
PLAIN_COVER = {
    "artist": "Some Wedding Band", "track": "Bittersweet Symphony", "album": "Covers",
    "genre": "Pop", "year": "2011",
    "preview_url": "http://p", "duration_sec": 300, "source": "iTunes", "uid": "plain",
}

YOUTUBE_DESCRIPTION = """Provided to YouTube by IIP-DDS
Bittersweet Symphony · The Crown · Fort Nowhere · Emma Allaway
Bittersweet Symphony
℗ Netflix Music, LLC
Released on: 2022-10-20
Composer, Lyricist: Richard Ashcroft
Auto-generated by YouTube."""


def test_the_title_alone_gives_nothing_away():
    """למה הזיהוי לפי כותרת לא יכול היה לעבוד כאן."""
    assert not search.has_epic_title(CROWN)


def test_soundtrack_genre_is_the_signal():
    assert search.is_soundtrack(CROWN)
    assert search.is_trailer_indicator(CROWN)
    assert not search.is_trailer_indicator(VERVE)
    assert not search.is_trailer_indicator(PLAIN_COVER)


def test_the_show_version_outranks_the_original_and_a_plain_cover():
    crown = search.score_track(CROWN, QUERY)
    assert crown > search.score_track(VERVE, QUERY)
    assert crown > search.score_track(PLAIN_COVER, QUERY)


def test_soundtrack_queries_are_actually_sent():
    queries = search.build_queries(QUERY)
    assert f"{QUERY} soundtrack" in queries
    assert f"{QUERY} official soundtrack" in queries


def test_the_show_version_is_listed_first(monkeypatch):
    """הדרישה: 'זה צריך להיות למעלה'."""
    pool = [PLAIN_COVER, VERVE, CROWN]
    monkeypatch.setattr(covers.search_module, "search_covers", lambda *a, **k: pool)
    results, _ = covers.find_epic_versions(QUERY)
    assert results[0]["artist"] == "Fort Nowhere & Emma Allaway"
    assert results[0]["trailer_indicator"] is True


def test_the_plain_cover_is_still_listed(monkeypatch):
    """סימן טריילר מקדם, לא מסנן."""
    monkeypatch.setattr(covers.search_module, "search_covers",
                        lambda *a, **k: [PLAIN_COVER, CROWN])
    results, _ = covers.find_epic_versions(QUERY)
    assert {t["artist"] for t in results} == {
        "Fort Nowhere & Emma Allaway", "Some Wedding Band"}


def test_youtube_recognizes_official_show_music():
    """התיאור האוטומטי נושא ℗ של חברת ההפקה, בלי המילה trailer בשום מקום."""
    assert "trailer" not in YOUTUBE_DESCRIPTION.lower()
    assert youtube.looks_like_trailer_use(YOUTUBE_DESCRIPTION)


def test_a_plain_official_video_is_not_evidence():
    assert not youtube.looks_like_trailer_use(
        "The Verve - Bitter Sweet Symphony (Official Video)")
    assert not youtube.looks_like_trailer_use(
        "Provided to YouTube by Universal Music Group\nBitter Sweet Symphony · The Verve")


# ---------- סמני שם אלבום: season / series / ost / from the / trailer ----------

def _album(name, genre="Pop"):
    return {"artist": "X", "track": "Bittersweet Symphony", "album": name,
            "genre": genre, "preview_url": "http://p", "uid": "u"}


def test_apple_album_names_are_recognized():
    for name in [
        "The Crown: Season 5 (Soundtrack from the Netflix Series)",
        "The Crown S5 (OST)",
        "Bittersweet Symphony (From the Motion Picture)",
        "Wednesday (Original Series Soundtrack)",
        "Epic Trailer Covers Vol 3",
    ]:
        assert search.has_production_album(_album(name)), name


def test_ordinary_albums_are_not_recognized():
    for name in ["Urban Hymns", "Greatest Hits", "Ghost Stories",
                 "Frost and Fire", "Lost Highway", "Four Seasons"]:
        assert not search.has_production_album(_album(name)), name


def test_ost_needs_a_full_word_boundary():
    """הטעות שכבר נעשתה פעם עם 'cover' בתוך 'Covered'."""
    for name in ["Ghost Stories", "Frost and Fire", "Lost Highway", "Costello Live"]:
        assert not search.has_production_album(_album(name)), name
    assert search.has_production_album(_album("The Crown (OST)"))


def test_season_does_not_match_seasons():
    assert not search.has_production_album(_album("Four Seasons"))
    assert search.has_production_album(_album("Bridgerton Season 3"))


def test_markers_are_checked_on_the_album_not_the_song_title():
    """שיר בשם 'Season' אינו מוזיקה של סדרה; אלבום בשם כזה כן."""
    song_named_season = {"artist": "X", "track": "Season", "album": "Debut",
                         "genre": "Pop", "preview_url": "http://p", "uid": "u"}
    assert not search.has_production_album(song_named_season)


def test_show_album_is_detected_without_a_soundtrack_genre():
    """הפער שנסגר: קודם הזיהוי היה תלוי בז'אנר בלבד."""
    crown = _album("The Crown S5 (OST)", genre="Pop")
    assert not search.is_soundtrack(crown)
    assert search.is_trailer_indicator(crown)


def test_indicators_name_which_signal_matched():
    assert search.trailer_indicators(_album("The Crown S5 (OST)")) == ["אלבום של סדרה/סרט"]
    assert search.trailer_indicators(_album("Urban Hymns", genre="Alternative")) == []
    both = search.trailer_indicators(
        _album("Epic Trailer Covers Vol 3", genre="Soundtrack"))
    assert "כותרת אפית" in both and "ז'אנר פסקול" in both


def test_show_album_outranks_the_original():
    crown = _album("The Crown S5 (OST)", genre="Pop")
    verve = {"artist": "The Verve", "track": "Bitter Sweet Symphony",
             "album": "Urban Hymns", "genre": "Alternative",
             "preview_url": "http://p", "uid": "v"}
    assert search.score_track(crown, QUERY) > search.score_track(verve, QUERY)


# ---------- trailerized ----------

def test_trailerized_in_the_track_title():
    assert search.has_epic_title(
        {"track": "Zombie (Trailerized Version)", "album": "Covers"})


def test_trailerized_in_the_album_name():
    """הפער: דפוס האלבום היה \\btrailer\\b סגור משני הצדדים ולכן פספס אותו."""
    assert search.has_production_album(_album("Trailerized Covers"))
    assert search.has_production_album(_album("Trailerized"))


def test_trailerized_is_an_indicator_from_either_field():
    assert search.is_trailer_indicator(
        {"track": "Zombie (Trailerized Version)", "album": "Covers", "genre": "Pop"})
    assert search.is_trailer_indicator(
        {"track": "Zombie", "album": "Trailerized Covers", "genre": "Pop"})


def test_trailerized_does_not_loosen_ordinary_albums():
    for name in ["Greatest Hits", "Urban Hymns", "Trail of Dead"]:
        assert not search.has_production_album(_album(name)), name
