"""רגרסיה על מקרה The Crown: קאבר שהופק לסדרה ואין בכותרת שלו אף מילת מפתח.

Fort Nowhere & Emma Allaway — "Bittersweet Symphony", ℗ Netflix Music LLC, 2022.
הכותרת היא שם השיר בלבד. הסימן היחיד במטא-דאטה הוא ז'אנר Soundtrack, וקודם
הוא היה שווה 10 נקודות בלבד — כך שהגרסה נקברה בין עשרות קאברים.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import covers
import search
import youtube

QUERY = "Bittersweet Symphony"

CROWN = {
    "artist": "Fort Nowhere & Emma Allaway", "track": "Bittersweet Symphony",
    "album": "Bittersweet Symphony", "genre": "Soundtrack", "year": "2022",
    "preview_url": "http://p", "duration_sec": 240, "source": "iTunes", "uid": "crown",
}
VERVE = {
    "artist": "The Verve", "track": "Bitter Sweet Symphony", "album": "Urban Hymns",
    "genre": "Alternative", "year": "1997",
    "preview_url": "http://p", "duration_sec": 350, "source": "iTunes", "uid": "verve",
}
PLAIN_COVER = {
    "artist": "Some Wedding Band", "track": "Bittersweet Symphony", "album": "Covers",
    "genre": "Pop", "year": "2011",
    "preview_url": "http://p", "duration_sec": 300, "source": "iTunes", "uid": "plain",
}

YOUTUBE_DESCRIPTION = """Provided to YouTube by IIP-DDS
Bittersweet Symphony · The Crown · Fort Nowhere · Emma Allaway
Bittersweet Symphony
℗ Netflix Music, LLC
Released on: 2022-10-20
Composer, Lyricist: Richard Ashcroft
Auto-generated by YouTube."""


def test_the_title_alone_gives_nothing_away():
    """למה הזיהוי לפי כותרת לא יכול היה לעבוד כאן."""
    assert not search.has_epic_title(CROWN)


def test_soundtrack_genre_is_the_signal():
    assert search.is_soundtrack(CROWN)
    assert search.is_trailer_indicator(CROWN)
    assert not search.is_trailer_indicator(VERVE)
    assert not search.is_trailer_indicator(PLAIN_COVER)


def test_the_show_version_outranks_the_original_and_a_plain_cover():
    crown = search.score_track(CROWN, QUERY)
    assert crown > search.score_track(VERVE, QUERY)
    assert crown > search.score_track(PLAIN_COVER, QUERY)


def test_soundtrack_queries_are_actually_sent():
    queries = search.build_queries(QUERY)
    assert f"{QUERY} soundtrack" in queries
    assert f"{QUERY} official soundtrack" in queries


def test_the_show_version_is_listed_first(monkeypatch):
    """הדרישה: 'זה צריך להיות למעלה'."""
    pool = [PLAIN_COVER, VERVE, CROWN]
    monkeypatch.setattr(covers.search_module, "search_covers", lambda *a, **k: pool)
    results, _ = covers.find_epic_versions(QUERY)
    assert results[0]["artist"] == "Fort Nowhere & Emma Allaway"
    assert results[0]["trailer_indicator"] is True


def test_the_plain_cover_is_still_listed(monkeypatch):
    """סימן טריילר מקדם, לא מסנן."""
    monkeypatch.setattr(covers.search_module, "search_covers",
                        lambda *a, **k: [PLAIN_COVER, CROWN])
    results, _ = covers.find_epic_versions(QUERY)
    assert {t["artist"] for t in results} == {
        "Fort Nowhere & Emma Allaway", "Some Wedding Band"}


def test_youtube_recognizes_official_show_music():
    """התיאור האוטומטי נושא ℗ של חברת ההפקה, בלי המילה trailer בשום מקום."""
    assert "trailer" not in YOUTUBE_DESCRIPTION.lower()
    assert youtube.looks_like_trailer_use(YOUTUBE_DESCRIPTION)


def test_a_plain_official_video_is_not_evidence():
    assert not youtube.looks_like_trailer_use(
        "The Verve - Bitter Sweet Symphony (Official Video)")
    assert not youtube.looks_like_trailer_use(
        "Provided to YouTube by Universal Music Group\nBitter Sweet Symphony · The Verve")
